import { createLesson } from './shared.js'

const buildTopic = ({
  id,
  name,
  subtopics = [],
  difficultyRange = [5, 6],
  problemMix = 'mixed',
  questionCountRange = [4, 5],
  lessons = [],
}) => ({
  id,
  name,
  subtopics,
  difficultyRange,
  problemMix,
  questionCountRange,
  lessons: lessons.map((lesson, index) =>
    createLesson({
      topicId: id,
      index: index + 1,
      ...lesson,
      problemMix: lesson.problemMix || problemMix,
      subtopics: lesson.subtopics || [],
    }),
  ),
})

const grade2 = {
  id: 'grade-2',
  gradeNumber: 2,
  name: '2do Secundaria - Matematicas (Alto Rendimiento)',
  objective:
    'Consolidar el pensamiento algebraico, dominar proporcionalidad avanzada, fortalecer geometria y comenzar analisis funcional basico.',
  areas: [
    {
      id: 'aritmetica-avanzada',
      name: 'I. Aritmetica Avanzada',
      topics: [
        buildTopic({
          id: 'potencias-propiedades',
          name: 'Potencias y Propiedades',
          subtopics: [
            'Leyes de exponentes',
            'Potencias de base negativa',
            'Potencias de 10',
            'Aplicacion en crecimiento poblacional simple',
          ],
          difficultyRange: [5, 6],
          problemMix: 'mixed',
          questionCountRange: [4, 5],
          lessons: [
            {
              title: 'Leyes de exponentes',
              difficulty: 5,
              questionCount: 4,
              problemMix: 'mixed',
              subtopics: ['leyes de exponentes'],
              skills: ['potencias', 'leyes', 'calculo'],
            },
            {
              title: 'Base negativa y potencias de 10',
              difficulty: 6,
              questionCount: 4,
              problemMix: 'mixed',
              subtopics: ['potencias de base negativa', 'potencias de 10'],
              skills: ['base-negativa', 'potencias-de-10', 'analisis'],
            },
            {
              title: 'Crecimiento poblacional simple con potencias',
              difficulty: 6,
              questionCount: 5,
              problemMix: 'mixed',
              subtopics: ['aplicacion en crecimiento poblacional simple'],
              skills: ['crecimiento', 'modelacion', 'potencias'],
            },
          ],
        }),
        buildTopic({
          id: 'raices-cuadradas-cubicas',
          name: 'Raices Cuadradas y Cubicas',
          subtopics: ['Raiz exacta', 'Aproximacion', 'Aplicaciones geometricas'],
          difficultyRange: [5, 6],
          problemMix: 'mixed',
          questionCountRange: [4, 5],
          lessons: [
            {
              title: 'Raices exactas cuadradas y cubicas',
              difficulty: 5,
              questionCount: 4,
              problemMix: 'mixed',
              subtopics: ['raiz exacta'],
              skills: ['raiz-cuadrada', 'raiz-cubica', 'exactitud'],
            },
            {
              title: 'Aproximacion de raices',
              difficulty: 6,
              questionCount: 4,
              problemMix: 'mixed',
              subtopics: ['aproximacion'],
              skills: ['aproximacion', 'estimacion', 'raices'],
            },
            {
              title: 'Aplicaciones geometricas de raices',
              difficulty: 6,
              questionCount: 5,
              problemMix: 'mixed',
              subtopics: ['aplicaciones geometricas'],
              skills: ['geometria', 'raices', 'aplicacion'],
            },
          ],
        }),
        buildTopic({
          id: 'notacion-cientifica',
          name: 'Notacion Cientifica',
          subtopics: ['Conversion', 'Operaciones', 'Aplicacion en ciencia'],
          difficultyRange: [6, 6],
          problemMix: 'mixed',
          questionCountRange: [4, 5],
          lessons: [
            {
              title: 'Conversion a notacion cientifica',
              difficulty: 6,
              questionCount: 4,
              problemMix: 'mixed',
              subtopics: ['conversion'],
              skills: ['conversion', 'notacion-cientifica'],
            },
            {
              title: 'Operaciones con notacion cientifica',
              difficulty: 6,
              questionCount: 5,
              problemMix: 'mixed',
              subtopics: ['operaciones'],
              skills: ['operaciones', 'exponentes', 'notacion-cientifica'],
            },
            {
              title: 'Aplicacion cientifica de notacion',
              difficulty: 6,
              questionCount: 5,
              problemMix: 'mixed',
              subtopics: ['aplicacion en ciencia'],
              skills: ['ciencia', 'modelacion', 'notacion-cientifica'],
            },
          ],
        }),
        buildTopic({
          id: 'proporcionalidad-compuesta',
          name: 'Proporcionalidad Compuesta',
          subtopics: ['Regla de tres compuesta', 'Velocidad-tiempo-distancia', 'Escalas'],
          difficultyRange: [7, 8],
          problemMix: 'mixed',
          questionCountRange: [5, 5],
          lessons: [
            {
              title: 'Regla de tres compuesta',
              difficulty: 7,
              questionCount: 5,
              problemMix: 'mixed',
              subtopics: ['regla de tres compuesta'],
              skills: ['proporcionalidad', 'regla-de-tres', 'analisis'],
            },
            {
              title: 'Velocidad, tiempo y distancia',
              difficulty: 7,
              questionCount: 5,
              problemMix: 'mixed',
              subtopics: ['velocidad-tiempo-distancia'],
              skills: ['movimiento', 'proporcionalidad', 'modelacion'],
            },
            {
              title: 'Escalas y proporcionalidad aplicada',
              difficulty: 8,
              questionCount: 5,
              problemMix: 'mixed',
              subtopics: ['escalas'],
              skills: ['escalas', 'conversion', 'modelacion'],
            },
          ],
        }),
        buildTopic({
          id: 'porcentajes-avanzados',
          name: 'Porcentajes Avanzados',
          subtopics: ['Aumentos sucesivos', 'Descuentos', 'Interes simple'],
          difficultyRange: [7, 8],
          problemMix: 'mixed',
          questionCountRange: [5, 5],
          lessons: [
            {
              title: 'Aumentos y descuentos sucesivos',
              difficulty: 7,
              questionCount: 5,
              problemMix: 'mixed',
              subtopics: ['aumentos sucesivos', 'descuentos'],
              skills: ['porcentajes', 'cambios-sucesivos', 'comercial'],
            },
            {
              title: 'Interes simple aplicado',
              difficulty: 8,
              questionCount: 5,
              problemMix: 'mixed',
              subtopics: ['interes simple'],
              skills: ['interes-simple', 'finanzas', 'modelacion'],
            },
          ],
        }),
      ],
    },
    {
      id: 'algebra',
      name: 'II. Algebra',
      topics: [
        buildTopic({
          id: 'polinomios',
          name: 'Polinomios',
          subtopics: ['Suma y resta', 'Multiplicacion', 'Valor numerico'],
          difficultyRange: [5, 6],
          problemMix: 'mixed',
          questionCountRange: [4, 5],
          lessons: [
            {
              title: 'Suma y resta de polinomios',
              difficulty: 5,
              questionCount: 4,
              problemMix: 'mixed',
              subtopics: ['suma y resta'],
              skills: ['polinomios', 'terminos-semejantes'],
            },
            {
              title: 'Multiplicacion de polinomios',
              difficulty: 5,
              questionCount: 4,
              problemMix: 'mixed',
              subtopics: ['multiplicacion'],
              skills: ['polinomios', 'multiplicacion'],
            },
            {
              title: 'Valor numerico de polinomios',
              difficulty: 6,
              questionCount: 5,
              problemMix: 'mixed',
              subtopics: ['valor numerico'],
              skills: ['evaluacion', 'sustitucion', 'polinomios'],
            },
          ],
        }),
        buildTopic({
          id: 'productos-notables',
          name: 'Productos Notables',
          subtopics: ['(a + b)^2', '(a - b)^2', '(a + b)(a - b)'],
          difficultyRange: [6, 6],
          problemMix: 'mixed',
          questionCountRange: [4, 5],
          lessons: [
            {
              title: 'Cuadrado de una suma y de una diferencia',
              difficulty: 6,
              questionCount: 4,
              problemMix: 'mixed',
              subtopics: ['(a + b)^2', '(a - b)^2'],
              skills: ['productos-notables', 'cuadrados'],
            },
            {
              title: 'Suma por diferencia',
              difficulty: 6,
              questionCount: 4,
              problemMix: 'mixed',
              subtopics: ['(a + b)(a - b)'],
              skills: ['productos-notables', 'diferencia-de-cuadrados'],
            },
            {
              title: 'Aplicacion de productos notables',
              difficulty: 6,
              questionCount: 5,
              problemMix: 'mixed',
              subtopics: ['aplicacion'],
              skills: ['productos-notables', 'modelacion'],
            },
          ],
        }),
        buildTopic({
          id: 'factorizacion-basica',
          name: 'Factorizacion Basica',
          subtopics: ['Factor comun', 'Diferencia de cuadrados', 'Trinomio simple'],
          difficultyRange: [7, 8],
          problemMix: 'mixed',
          questionCountRange: [5, 5],
          lessons: [
            {
              title: 'Factor comun',
              difficulty: 7,
              questionCount: 5,
              problemMix: 'mixed',
              subtopics: ['factor comun'],
              skills: ['factorizacion', 'factor-comun'],
            },
            {
              title: 'Diferencia de cuadrados',
              difficulty: 7,
              questionCount: 5,
              problemMix: 'mixed',
              subtopics: ['diferencia de cuadrados'],
              skills: ['factorizacion', 'diferencia-de-cuadrados'],
            },
            {
              title: 'Trinomio simple aplicado',
              difficulty: 8,
              questionCount: 5,
              problemMix: 'mixed',
              subtopics: ['trinomio simple'],
              skills: ['factorizacion', 'trinomio', 'modelacion'],
            },
          ],
        }),
        buildTopic({
          id: 'ecuaciones-lineales-dos-pasos',
          name: 'Ecuaciones Lineales con Dos Pasos',
          subtopics: ['Despeje con dos operaciones', 'Modelacion con contexto'],
          difficultyRange: [6, 6],
          problemMix: 'mixed',
          questionCountRange: [4, 5],
          lessons: [
            {
              title: 'Ecuaciones lineales de dos pasos',
              difficulty: 6,
              questionCount: 4,
              problemMix: 'mixed',
              subtopics: ['despeje con dos operaciones'],
              skills: ['ecuaciones', 'despeje'],
            },
            {
              title: 'Ecuaciones lineales en contexto',
              difficulty: 6,
              questionCount: 5,
              problemMix: 'mixed',
              subtopics: ['modelacion con contexto'],
              skills: ['ecuaciones', 'contexto', 'modelacion'],
            },
          ],
        }),
        buildTopic({
          id: 'sistemas-ecuaciones',
          name: 'Sistemas de Ecuaciones',
          subtopics: ['Metodo grafico', 'Metodo de sustitucion', 'Modelacion con contexto'],
          difficultyRange: [7, 8],
          problemMix: 'mixed',
          questionCountRange: [5, 5],
          lessons: [
            {
              title: 'Interpretacion geometrica del sistema',
              difficulty: 7,
              questionCount: 5,
              problemMix: 'mixed',
              subtopics: ['metodo grafico'],
              skills: ['sistemas', 'grafico', 'interpretacion'],
            },
            {
              title: 'Sistemas por sustitucion',
              difficulty: 7,
              questionCount: 5,
              problemMix: 'mixed',
              subtopics: ['metodo de sustitucion'],
              skills: ['sistemas', 'sustitucion'],
            },
            {
              title: 'Sistemas con modelacion contextual',
              difficulty: 8,
              questionCount: 5,
              problemMix: 'mixed',
              subtopics: ['modelacion con contexto'],
              skills: ['sistemas', 'modelacion', 'contexto'],
            },
          ],
        }),
      ],
    },
    {
      id: 'geometria',
      name: 'III. Geometria',
      topics: [
        buildTopic({
          id: 'teorema-de-pitagoras',
          name: 'Teorema de Pitagoras',
          subtopics: ['Aplicacion directa', 'Problemas contextualizados'],
          difficultyRange: [6, 6],
          problemMix: 'mixed',
          questionCountRange: [4, 5],
          lessons: [
            {
              title: 'Aplicacion directa del teorema de Pitagoras',
              difficulty: 6,
              questionCount: 4,
              problemMix: 'mixed',
              subtopics: ['aplicacion directa'],
              skills: ['pitagoras', 'triangulos-rectangulos'],
            },
            {
              title: 'Pitagoras en contexto',
              difficulty: 6,
              questionCount: 5,
              problemMix: 'mixed',
              subtopics: ['problemas contextualizados'],
              skills: ['pitagoras', 'contexto', 'modelacion'],
            },
          ],
        }),
        buildTopic({
          id: 'areas-compuestas',
          name: 'Areas Compuestas',
          subtopics: ['Figuras combinadas', 'Problemas reales (terrenos y planos)'],
          difficultyRange: [7, 8],
          problemMix: 'mixed',
          questionCountRange: [5, 5],
          lessons: [
            {
              title: 'Areas de figuras combinadas',
              difficulty: 7,
              questionCount: 5,
              problemMix: 'mixed',
              subtopics: ['figuras combinadas'],
              skills: ['areas', 'composicion'],
            },
            {
              title: 'Areas compuestas en terrenos y planos',
              difficulty: 8,
              questionCount: 5,
              problemMix: 'mixed',
              subtopics: ['problemas reales'],
              skills: ['areas', 'terrenos', 'modelacion'],
            },
          ],
        }),
        buildTopic({
          id: 'semejanza-de-triangulos',
          name: 'Semejanza de Triangulos',
          subtopics: ['Razon de semejanza', 'Aplicacion con medidas faltantes'],
          difficultyRange: [7, 8],
          problemMix: 'mixed',
          questionCountRange: [5, 5],
          lessons: [
            {
              title: 'Razon y criterios de semejanza',
              difficulty: 7,
              questionCount: 5,
              problemMix: 'mixed',
              subtopics: ['razon de semejanza'],
              skills: ['semejanza', 'proporciones'],
            },
            {
              title: 'Semejanza aplicada',
              difficulty: 8,
              questionCount: 5,
              problemMix: 'mixed',
              subtopics: ['aplicacion con medidas faltantes'],
              skills: ['semejanza', 'modelacion', 'medidas'],
            },
          ],
        }),
      ],
    },
    {
      id: 'estadistica-probabilidad',
      name: 'IV. Estadistica y Probabilidad',
      topics: [
        buildTopic({
          id: 'media-mediana-moda-rango',
          name: 'Media, Mediana, Moda y Rango',
          subtopics: ['Media', 'Mediana', 'Moda', 'Rango'],
          difficultyRange: [5, 6],
          problemMix: 'mixed',
          questionCountRange: [4, 5],
          lessons: [
            {
              title: 'Media y mediana',
              difficulty: 5,
              questionCount: 4,
              problemMix: 'mixed',
              subtopics: ['media', 'mediana'],
              skills: ['estadistica', 'tendencia-central'],
            },
            {
              title: 'Moda y rango aplicados',
              difficulty: 6,
              questionCount: 5,
              problemMix: 'mixed',
              subtopics: ['moda', 'rango'],
              skills: ['estadistica', 'dispersion', 'analisis'],
            },
          ],
        }),
        buildTopic({
          id: 'probabilidad-compuesta-basica',
          name: 'Probabilidad Compuesta Basica',
          subtopics: ['Eventos independientes', 'Arbol de probabilidad'],
          difficultyRange: [7, 8],
          problemMix: 'mixed',
          questionCountRange: [5, 5],
          lessons: [
            {
              title: 'Eventos independientes',
              difficulty: 7,
              questionCount: 5,
              problemMix: 'mixed',
              subtopics: ['eventos independientes'],
              skills: ['probabilidad', 'independencia'],
            },
            {
              title: 'Arbol de probabilidad aplicado',
              difficulty: 8,
              questionCount: 5,
              problemMix: 'mixed',
              subtopics: ['arbol de probabilidad'],
              skills: ['probabilidad', 'arbol', 'modelacion'],
            },
          ],
        }),
      ],
    },
    {
      id: 'introduccion-funciones',
      name: 'V. Introduccion a Funciones',
      topics: [
        buildTopic({
          id: 'funcion-lineal-basica',
          name: 'Funcion Lineal Basica',
          subtopics: ['y = mx + b', 'Interpretacion grafica', 'Pendiente', 'Modelacion economica simple'],
          difficultyRange: [7, 8],
          problemMix: 'mixed',
          questionCountRange: [5, 5],
          lessons: [
            {
              title: 'Forma y = mx + b y pendiente',
              difficulty: 7,
              questionCount: 5,
              problemMix: 'mixed',
              subtopics: ['y = mx + b', 'pendiente'],
              skills: ['funcion-lineal', 'pendiente'],
            },
            {
              title: 'Interpretacion grafica de funcion lineal',
              difficulty: 7,
              questionCount: 5,
              problemMix: 'mixed',
              subtopics: ['interpretacion grafica'],
              skills: ['funcion-lineal', 'grafica', 'analisis'],
            },
            {
              title: 'Modelacion economica con funcion lineal',
              difficulty: 8,
              questionCount: 5,
              problemMix: 'mixed',
              subtopics: ['modelacion economica simple'],
              skills: ['funcion-lineal', 'modelacion', 'economia'],
            },
          ],
        }),
      ],
    },
  ],
  finalExam: {
    id: 'grade-2-final-exam',
    name: 'Examen Final 2do Secundaria (Alto Rendimiento)',
    questionRange: [70, 70],
    passingScore: 0.78,
    xpMultiplier: 2,
    aiHelpAllowed: false,
    sections: [
      {
        id: 'aritmetica-avanzada',
        name: 'Aritmetica Avanzada',
        count: 18,
        topicIds: [
          'potencias-propiedades',
          'raices-cuadradas-cubicas',
          'notacion-cientifica',
          'proporcionalidad-compuesta',
          'porcentajes-avanzados',
        ],
      },
      {
        id: 'algebra',
        name: 'Algebra',
        count: 20,
        topicIds: [
          'polinomios',
          'productos-notables',
          'factorizacion-basica',
          'ecuaciones-lineales-dos-pasos',
          'sistemas-ecuaciones',
        ],
      },
      {
        id: 'geometria',
        name: 'Geometria',
        count: 15,
        topicIds: ['teorema-de-pitagoras', 'areas-compuestas', 'semejanza-de-triangulos'],
      },
      {
        id: 'estadistica-probabilidad',
        name: 'Estadistica y Probabilidad',
        count: 10,
        topicIds: ['media-mediana-moda-rango', 'probabilidad-compuesta-basica'],
      },
      {
        id: 'funciones',
        name: 'Funciones',
        count: 7,
        topicIds: ['funcion-lineal-basica'],
      },
    ],
    distribution: [
      { topicId: 'potencias-propiedades', count: 4, difficultyRange: [5, 6] },
      { topicId: 'raices-cuadradas-cubicas', count: 4, difficultyRange: [5, 6] },
      { topicId: 'notacion-cientifica', count: 3, difficultyRange: [6, 6] },
      { topicId: 'proporcionalidad-compuesta', count: 4, difficultyRange: [7, 8] },
      { topicId: 'porcentajes-avanzados', count: 3, difficultyRange: [7, 8] },
      { topicId: 'polinomios', count: 4, difficultyRange: [5, 6] },
      { topicId: 'productos-notables', count: 4, difficultyRange: [6, 6] },
      { topicId: 'factorizacion-basica', count: 4, difficultyRange: [7, 8] },
      { topicId: 'ecuaciones-lineales-dos-pasos', count: 4, difficultyRange: [6, 6] },
      { topicId: 'sistemas-ecuaciones', count: 4, difficultyRange: [7, 8] },
      { topicId: 'teorema-de-pitagoras', count: 5, difficultyRange: [6, 6] },
      { topicId: 'areas-compuestas', count: 5, difficultyRange: [7, 8] },
      { topicId: 'semejanza-de-triangulos', count: 5, difficultyRange: [7, 8] },
      { topicId: 'media-mediana-moda-rango', count: 5, difficultyRange: [5, 6] },
      { topicId: 'probabilidad-compuesta-basica', count: 5, difficultyRange: [7, 8] },
      { topicId: 'funcion-lineal-basica', count: 7, difficultyRange: [7, 8] },
    ],
    mixDistribution: [
      { mix: 'contextualized', count: 28 },
      { mix: 'mechanical', count: 28 },
      { mix: 'advanced-modeling', count: 14 },
    ],
  },
}

export default grade2
