import { buildLessonsFromOutline } from './shared.js'

const topic = (id, name, outline) => ({
  id,
  name,
  lessons: buildLessonsFromOutline(id, outline, 5),
  skeleton: true,
})

const grade4 = {
  id: 'grade-4',
  gradeNumber: 4,
  name: '4to Secundaria',
  areas: [
    {
      id: 'algebra',
      name: 'Algebra',
      topics: [
        topic('funcion-cuadratica', 'Funcion Cuadratica', [
          'Forma general ax^2 + bx + c',
          'Resolucion por factorizacion',
          'Formula general',
          'Discriminante',
          'Naturaleza de las raices',
          'Vertice de la parabola',
          'Eje de simetria',
          'Grafica de la parabola',
          'Maximos y minimos',
          'Modelacion de problemas fisicos',
          'Problemas aplicados',
          'Examen',
        ]),
        topic('funciones-polinomicas', 'Funciones Polinomicas', [
          'Grado de un polinomio',
          'Comportamiento al infinito',
          'Division de polinomios',
          'Teorema del residuo',
          'Teorema del factor',
          'Raices racionales',
          'Aplicaciones',
          'Examen',
        ]),
        topic('logaritmos', 'Logaritmos', [
          'Concepto de logaritmo',
          'Relacion con exponenciales',
          'Propiedades de logaritmos',
          'Cambio de base',
          'Ecuaciones logaritmicas',
          'Ecuaciones exponenciales',
          'Aplicaciones cientificas',
          'Problemas combinados',
          'Examen',
        ]),
      ],
    },
    {
      id: 'geometria',
      name: 'Geometria',
      topics: [
        topic('geometria-analitica', 'Geometria Analitica', [
          'Plano cartesiano avanzado',
          'Distancia entre dos puntos',
          'Punto medio',
          'Pendiente entre dos puntos',
          'Ecuacion de la recta',
          'Rectas paralelas y perpendiculares',
          'Interseccion de rectas',
          'Circunferencia (ecuacion general)',
          'Problemas aplicados',
          'Examen',
        ]),
        topic('trigonometria', 'Trigonometria', [
          'Razones trigonometricas',
          'Circunferencia unitaria',
          'Angulos notables',
          'Identidades trigonometricas basicas',
          'Resolucion de triangulos rectangulos',
          'Ley de senos',
          'Ley de cosenos',
          'Problemas de altura y distancia',
          'Identidades fundamentales',
          'Ecuaciones trigonometricas basicas',
          'Problemas aplicados',
          'Examen',
        ]),
      ],
    },
    {
      id: 'estadistica-probabilidad',
      name: 'Estadistica y Probabilidad',
      topics: [
        topic('estadistica', 'Estadistica', [
          'Varianza',
          'Desviacion estandar',
          'Interpretacion de dispersion',
          'Diagramas de caja',
          'Histogramas',
          'Distribuciones simples',
          'Comparacion de datos',
          'Problemas aplicados',
          'Examen',
        ]),
        topic('probabilidad', 'Probabilidad', [
          'Regla de adicion',
          'Regla de multiplicacion',
          'Probabilidad condicional',
          'Eventos dependientes',
          'Combinaciones basicas',
          'Permutaciones basicas',
          'Problemas aplicados',
          'Examen',
        ]),
      ],
    },
    {
      id: 'aritmetica-avanzada',
      name: 'Aritmetica Avanzada',
      topics: [
        topic('numeros-reales', 'Numeros Reales', [
          'Conjunto de los reales',
          'Intervalos',
          'Inecuaciones lineales',
          'Inecuaciones cuadraticas',
          'Valor absoluto',
          'Problemas aplicados',
          'Examen',
        ]),
      ],
    },
    {
      id: 'medicion-aplicaciones',
      name: 'Medicion y Aplicaciones',
      topics: [
        topic('movimiento-rectilineo-uniforme', 'Movimiento Rectilineo Uniforme', [
          'Formula velocidad',
          'Tiempo',
          'Distancia',
          'Problemas combinados',
          'Graficas posicion-tiempo',
          'Examen',
        ]),
      ],
    },
  ],
  finalExam: {
    id: 'grade-4-final-exam',
    name: 'Examen Final 4to Secundaria',
    questionRange: [60, 70],
    passingScore: 0.7,
    xpMultiplier: 2,
    aiHelpAllowed: false,
    distribution: [
      { topicId: 'funcion-cuadratica', count: 8, difficultyRange: [4, 5] },
      { topicId: 'funciones-polinomicas', count: 6, difficultyRange: [4, 5] },
      { topicId: 'logaritmos', count: 6, difficultyRange: [4, 5] },
      { topicId: 'geometria-analitica', count: 8, difficultyRange: [4, 5] },
      { topicId: 'trigonometria', count: 10, difficultyRange: [4, 5] },
      { topicId: 'estadistica', count: 6, difficultyRange: [3, 5] },
      { topicId: 'probabilidad', count: 6, difficultyRange: [4, 5] },
      { topicId: 'numeros-reales', count: 10, difficultyRange: [4, 5] },
      { topicId: 'movimiento-rectilineo-uniforme', count: 10, difficultyRange: [4, 5] },
    ],
  },
}

export default grade4
