import { buildLessonsFromOutline } from './shared.js'

const topic = (id, name, outline) => ({
  id,
  name,
  lessons: buildLessonsFromOutline(id, outline, 4),
  skeleton: true,
})

const grade2 = {
  id: 'grade-2',
  gradeNumber: 2,
  name: '2do Secundaria',
  areas: [
    {
      id: 'aritmetica',
      name: 'Aritmetica',
      topics: [
        topic('numeros-enteros', 'Numeros Enteros', [
          'Recta numerica con enteros',
          'Valor absoluto',
          'Suma de enteros',
          'Resta de enteros',
          'Multiplicacion de enteros',
          'Division de enteros',
          'Operaciones combinadas',
          'Problemas aplicados',
          'Examen',
        ]),
        topic('potencias-y-raices', 'Potencias y Raices', [
          'Concepto de potencia',
          'Potencias de base entera',
          'Propiedades de las potencias',
          'Potencias con exponente negativo',
          'Raiz cuadrada exacta',
          'Raiz cuadrada aproximada',
          'Problemas aplicados',
          'Examen',
        ]),
        topic('proporcionalidad', 'Proporcionalidad', [
          'Razon',
          'Proporcion',
          'Regla de tres simple directa',
          'Regla de tres inversa',
          'Porcentajes basicos',
          'Aumentos y descuentos',
          'Problemas comerciales',
          'Examen',
        ]),
      ],
    },
    {
      id: 'algebra',
      name: 'Algebra',
      topics: [
        topic('expresiones-algebraicas-avanzadas', 'Expresiones Algebraicas Avanzadas', [
          'Terminos semejantes',
          'Reduccion de terminos',
          'Multiplicacion de monomios',
          'Multiplicacion de polinomio por monomio',
          'Productos notables (introduccion)',
          'Evaluacion con valores negativos',
          'Problemas aplicados',
          'Examen',
        ]),
        topic('ecuaciones-primer-grado', 'Ecuaciones de Primer Grado', [
          'Ecuaciones con parentesis',
          'Ecuaciones con fracciones',
          'Ecuaciones con decimales',
          'Ecuaciones con enteros negativos',
          'Problemas de edades',
          'Problemas de movimiento',
          'Problemas comerciales',
          'Repaso',
          'Examen',
        ]),
        topic('sistemas-ecuaciones-intro', 'Sistemas de Ecuaciones (Introduccion)', [
          'Concepto de sistema',
          'Metodo de sustitucion',
          'Metodo de igualacion',
          'Metodo grafico',
          'Problemas aplicados',
          'Verificacion',
          'Examen',
        ]),
      ],
    },
    {
      id: 'geometria',
      name: 'Geometria',
      topics: [
        topic('triangulos', 'Triangulos', [
          'Clasificacion',
          'Suma de angulos internos',
          'Angulos exteriores',
          'Teorema de Pitagoras (introduccion)',
          'Aplicaciones basicas',
          'Area avanzada',
          'Problemas aplicados',
          'Examen',
        ]),
        topic('cuadrilateros-poligonos', 'Cuadrilateros y Poligonos', [
          'Propiedades',
          'Poligonos regulares',
          'Perimetro avanzado',
          'Area de paralelogramo',
          'Area de trapecio',
          'Problemas aplicados',
          'Examen',
        ]),
        topic('geometria-del-espacio', 'Geometria del Espacio', [
          'Prismas',
          'Piramides',
          'Volumen',
          'Area lateral y total',
          'Problemas aplicados',
          'Examen',
        ]),
      ],
    },
    {
      id: 'estadistica-probabilidad',
      name: 'Estadistica y Probabilidad',
      topics: [
        topic('estadistica', 'Estadistica', [
          'Poblacion y muestra',
          'Tabla de frecuencia absoluta',
          'Frecuencia relativa',
          'Media',
          'Mediana',
          'Moda',
          'Examen',
        ]),
        topic('probabilidad', 'Probabilidad', [
          'Espacio muestral',
          'Probabilidad simple',
          'Probabilidad de eventos compuestos simples',
          'Experimentos con dados y monedas',
          'Problemas aplicados',
          'Examen',
        ]),
      ],
    },
    {
      id: 'medicion',
      name: 'Medicion',
      topics: [
        topic('conversion-unidades-compuestas', 'Conversion de Unidades Compuestas', [
          'Longitud',
          'Superficie',
          'Volumen',
          'Tiempo',
          'Velocidad basica',
          'Examen',
        ]),
      ],
    },
  ],
  finalExam: {
    id: 'grade-2-final-exam',
    name: 'Examen Final 2do Secundaria',
    questionRange: [40, 50],
    passingScore: 0.7,
    xpMultiplier: 2,
    aiHelpAllowed: false,
    distribution: [
      { topicId: 'numeros-enteros', count: 3, difficultyRange: [3, 4] },
      { topicId: 'potencias-y-raices', count: 3, difficultyRange: [3, 4] },
      { topicId: 'proporcionalidad', count: 4, difficultyRange: [3, 4] },
      { topicId: 'ecuaciones-primer-grado', count: 5, difficultyRange: [3, 5] },
      { topicId: 'sistemas-ecuaciones-intro', count: 3, difficultyRange: [3, 5] },
      { topicId: 'expresiones-algebraicas-avanzadas', count: 4, difficultyRange: [3, 5] },
      { topicId: 'triangulos', count: 3, difficultyRange: [3, 4] },
      { topicId: 'cuadrilateros-poligonos', count: 3, difficultyRange: [3, 4] },
      { topicId: 'geometria-del-espacio', count: 4, difficultyRange: [3, 5] },
      { topicId: 'estadistica', count: 4, difficultyRange: [3, 4] },
      { topicId: 'probabilidad', count: 4, difficultyRange: [3, 4] },
      { topicId: 'conversion-unidades-compuestas', count: 6, difficultyRange: [3, 4] },
    ],
  },
}

export default grade2
