import { buildLessonsFromOutline } from './shared.js'

const topic = (id, name, outline) => ({
  id,
  name,
  lessons: buildLessonsFromOutline(id, outline, 4),
  skeleton: true,
})

const grade3 = {
  id: 'grade-3',
  gradeNumber: 3,
  name: '3ro Secundaria',
  areas: [
    {
      id: 'aritmetica-avanzada',
      name: 'Aritmetica Avanzada',
      topics: [
        topic('numeros-racionales', 'Numeros Racionales', [
          'Concepto de numero racional',
          'Conversion decimal a fraccion y viceversa',
          'Operaciones con racionales',
          'Operaciones combinadas',
          'Jerarquia avanzada',
          'Potencias con fracciones',
          'Raices con fracciones',
          'Problemas financieros',
          'Problemas con magnitudes',
          'Examen',
        ]),
        topic('porcentajes-avanzados', 'Porcentajes Avanzados', [
          'Porcentaje de una cantidad',
          'Aumento porcentual',
          'Descuento porcentual',
          'Interes simple',
          'Problemas comerciales',
          'Problemas financieros combinados',
          'Repaso',
          'Examen',
        ]),
      ],
    },
    {
      id: 'algebra',
      name: 'Algebra',
      topics: [
        topic('productos-notables', 'Productos Notables', [
          'Cuadrado de binomio',
          'Suma por diferencia',
          'Binomios con termino comun',
          'Cubo de binomio (introduccion)',
          'Aplicaciones',
          'Simplificacion algebraica',
          'Problemas aplicados',
          'Examen',
        ]),
        topic('factorizacion', 'Factorizacion', [
          'Factor comun',
          'Factor comun por agrupacion',
          'Diferencia de cuadrados',
          'Trinomio cuadrado perfecto',
          'Trinomio simple',
          'Trinomio general',
          'Suma y diferencia de cubos',
          'Aplicaciones',
          'Problemas algebraicos',
          'Examen',
        ]),
        topic('sistemas-ecuaciones', 'Sistemas de Ecuaciones', [
          'Metodo de sustitucion avanzado',
          'Metodo de reduccion avanzado',
          'Metodo grafico analitico',
          'Sistemas con fracciones',
          'Sistemas con decimales',
          'Problemas de edades',
          'Problemas de mezcla',
          'Problemas comerciales',
          'Examen',
        ]),
        topic('funciones', 'Funciones', [
          'Concepto formal de funcion',
          'Dominio y rango',
          'Funcion lineal',
          'Pendiente',
          'Interseccion con ejes',
          'Representacion grafica',
          'Problemas de modelacion',
          'Interpretacion de graficos',
          'Examen',
        ]),
      ],
    },
    {
      id: 'geometria',
      name: 'Geometria',
      topics: [
        topic('teorema-de-pitagoras', 'Teorema de Pitagoras', [
          'Demostracion intuitiva',
          'Calculo de hipotenusa',
          'Calculo de cateto',
          'Aplicaciones reales',
          'Problemas combinados',
          'Examen',
        ]),
        topic('semejanza-de-triangulos', 'Semejanza de Triangulos', [
          'Criterios de semejanza',
          'Razones de semejanza',
          'Teorema de Tales',
          'Aplicaciones',
          'Problemas geometricos',
          'Problemas con sombras',
          'Examen',
        ]),
        topic('geometria-del-espacio-avanzada', 'Geometria del Espacio', [
          'Prismas',
          'Piramides',
          'Cilindros',
          'Conos',
          'Esferas',
          'Area total',
          'Volumen',
          'Examen',
        ]),
      ],
    },
    {
      id: 'estadistica-probabilidad',
      name: 'Estadistica y Probabilidad',
      topics: [
        topic('estadistica-descriptiva', 'Estadistica Descriptiva', [
          'Poblacion y muestra',
          'Frecuencia acumulada',
          'Media',
          'Mediana',
          'Moda',
          'Rango',
          'Interpretacion de graficos',
          'Examen',
        ]),
        topic('probabilidad-compuesta', 'Probabilidad', [
          'Probabilidad simple',
          'Probabilidad compuesta',
          'Eventos independientes',
          'Regla del complemento',
          'Diagramas de arbol',
          'Problemas aplicados',
          'Examen',
        ]),
      ],
    },
    {
      id: 'medicion',
      name: 'Medicion',
      topics: [
        topic('magnitudes-proporcionales', 'Magnitudes Proporcionales', [
          'Proporcionalidad directa',
          'Proporcionalidad inversa',
          'Velocidad',
          'Densidad',
          'Problemas aplicados',
          'Examen',
        ]),
      ],
    },
  ],
  finalExam: {
    id: 'grade-3-final-exam',
    name: 'Examen Final 3ro Secundaria',
    questionRange: [50, 60],
    passingScore: 0.7,
    xpMultiplier: 2,
    aiHelpAllowed: false,
    distribution: [
      { topicId: 'numeros-racionales', count: 6, difficultyRange: [3, 5] },
      { topicId: 'porcentajes-avanzados', count: 4, difficultyRange: [3, 5] },
      { topicId: 'productos-notables', count: 4, difficultyRange: [3, 5] },
      { topicId: 'factorizacion', count: 5, difficultyRange: [3, 5] },
      { topicId: 'sistemas-ecuaciones', count: 4, difficultyRange: [3, 5] },
      { topicId: 'funciones', count: 5, difficultyRange: [3, 5] },
      { topicId: 'teorema-de-pitagoras', count: 4, difficultyRange: [3, 5] },
      { topicId: 'semejanza-de-triangulos', count: 4, difficultyRange: [3, 5] },
      { topicId: 'geometria-del-espacio-avanzada', count: 4, difficultyRange: [3, 5] },
      { topicId: 'estadistica-descriptiva', count: 5, difficultyRange: [3, 4] },
      { topicId: 'probabilidad-compuesta', count: 5, difficultyRange: [3, 5] },
      { topicId: 'magnitudes-proporcionales', count: 8, difficultyRange: [3, 4] },
    ],
  },
}

export default grade3
