import { createLesson } from './shared.js'

const buildTopic = ({
  id,
  name,
  subtopics = [],
  difficultyRange = [6, 7],
  problemMix = 'mixed',
  questionCountRange = [4, 5],
  lessons = [],
}) => ({
  id,
  name,
  subtopics,
  difficultyRange,
  problemMix,
  questionCountRange,
  lessons: lessons.map((lesson, index) =>
    createLesson({
      topicId: id,
      index: index + 1,
      ...lesson,
      problemMix: lesson.problemMix || problemMix,
      subtopics: lesson.subtopics || [],
    }),
  ),
})

const grade3 = {
  id: 'grade-3',
  gradeNumber: 3,
  name: '3ro Secundaria - Matematica (Alto Rendimiento)',
  objective:
    'Desarrollar pensamiento algebraico estructural, analisis funcional y capacidad de modelacion matematica.',
  areas: [
    {
      id: 'algebra-avanzada',
      name: 'I. Algebra Avanzada',
      topics: [
        buildTopic({
          id: 'productos-notables-completos',
          name: 'Productos Notables Completos',
          subtopics: ['Cubo de binomio', 'Binomios conjugados', 'Aplicaciones geometricas'],
          difficultyRange: [6, 6],
          problemMix: 'mixed',
          questionCountRange: [4, 5],
          lessons: [
            {
              title: 'Cubo de binomio',
              difficulty: 6,
              questionCount: 4,
              problemMix: 'mixed',
              subtopics: ['cubo de binomio'],
              skills: ['productos-notables', 'cubo', 'algebra'],
            },
            {
              title: 'Binomios conjugados',
              difficulty: 6,
              questionCount: 4,
              problemMix: 'mixed',
              subtopics: ['binomios conjugados'],
              skills: ['conjugados', 'diferencia-de-cuadrados'],
            },
            {
              title: 'Aplicaciones geometricas de notables',
              difficulty: 6,
              questionCount: 5,
              problemMix: 'mixed',
              subtopics: ['aplicaciones geometricas'],
              skills: ['geometria', 'modelacion', 'productos-notables'],
            },
          ],
        }),
        buildTopic({
          id: 'factorizacion-completa',
          name: 'Factorizacion Completa',
          subtopics: [
            'Factor comun',
            'Diferencia de cuadrados',
            'Trinomio general',
            'Suma/diferencia de cubos',
            'Factorizacion combinada',
          ],
          difficultyRange: [7, 9],
          problemMix: 'mixed',
          questionCountRange: [5, 5],
          lessons: [
            {
              title: 'Factor comun y diferencia de cuadrados',
              difficulty: 7,
              questionCount: 5,
              problemMix: 'mixed',
              subtopics: ['factor comun', 'diferencia de cuadrados'],
              skills: ['factorizacion', 'factor-comun', 'diferencia-cuadrados'],
            },
            {
              title: 'Trinomio general y cubos',
              difficulty: 8,
              questionCount: 5,
              problemMix: 'mixed',
              subtopics: ['trinomio general', 'suma/diferencia de cubos'],
              skills: ['trinomio', 'cubos', 'factorizacion'],
            },
            {
              title: 'Factorizacion combinada aplicada',
              difficulty: 9,
              questionCount: 5,
              problemMix: 'mixed',
              subtopics: ['factorizacion combinada'],
              skills: ['factorizacion', 'estrategia', 'modelacion'],
            },
          ],
        }),
        buildTopic({
          id: 'fracciones-algebraicas',
          name: 'Fracciones Algebraicas',
          subtopics: ['Simplificacion', 'Operaciones', 'Restricciones'],
          difficultyRange: [7, 9],
          problemMix: 'mixed',
          questionCountRange: [5, 5],
          lessons: [
            {
              title: 'Simplificacion de fracciones algebraicas',
              difficulty: 7,
              questionCount: 5,
              problemMix: 'mixed',
              subtopics: ['simplificacion'],
              skills: ['fracciones-algebraicas', 'simplificacion'],
            },
            {
              title: 'Operaciones con fracciones algebraicas',
              difficulty: 8,
              questionCount: 5,
              problemMix: 'mixed',
              subtopics: ['operaciones'],
              skills: ['fracciones-algebraicas', 'operaciones'],
            },
            {
              title: 'Restricciones y contexto',
              difficulty: 9,
              questionCount: 5,
              problemMix: 'mixed',
              subtopics: ['restricciones'],
              skills: ['restricciones', 'dominio', 'modelacion'],
            },
          ],
        }),
        buildTopic({
          id: 'ecuaciones-cuadraticas',
          name: 'Ecuaciones Cuadraticas',
          subtopics: ['Factorizacion', 'Formula general', 'Discriminante', 'Aplicaciones reales'],
          difficultyRange: [8, 9],
          problemMix: 'mixed',
          questionCountRange: [5, 5],
          lessons: [
            {
              title: 'Resolucion por factorizacion',
              difficulty: 8,
              questionCount: 5,
              problemMix: 'mixed',
              subtopics: ['factorizacion'],
              skills: ['ecuaciones-cuadraticas', 'factorizacion'],
            },
            {
              title: 'Formula general y discriminante',
              difficulty: 9,
              questionCount: 5,
              problemMix: 'mixed',
              subtopics: ['formula general', 'discriminante'],
              skills: ['formula-general', 'discriminante', 'analisis'],
            },
            {
              title: 'Aplicaciones reales cuadraticas',
              difficulty: 9,
              questionCount: 5,
              problemMix: 'mixed',
              subtopics: ['aplicaciones reales'],
              skills: ['modelacion', 'cuadratica', 'contexto'],
            },
          ],
        }),
        buildTopic({
          id: 'sistemas-ecuaciones-2x2-formal',
          name: 'Sistemas de Ecuaciones 2x2 (Formal)',
          subtopics: ['Sustitucion', 'Igualacion', 'Reduccion', 'Modelacion economica'],
          difficultyRange: [7, 8],
          problemMix: 'mixed',
          questionCountRange: [5, 5],
          lessons: [
            {
              title: 'Sistemas por sustitucion e igualacion',
              difficulty: 7,
              questionCount: 5,
              problemMix: 'mixed',
              subtopics: ['sustitucion', 'igualacion'],
              skills: ['sistemas', 'sustitucion', 'igualacion'],
            },
            {
              title: 'Sistemas por reduccion',
              difficulty: 8,
              questionCount: 5,
              problemMix: 'mixed',
              subtopics: ['reduccion'],
              skills: ['sistemas', 'reduccion'],
            },
            {
              title: 'Modelacion economica con sistemas',
              difficulty: 8,
              questionCount: 5,
              problemMix: 'mixed',
              subtopics: ['modelacion economica'],
              skills: ['sistemas', 'economia', 'modelacion'],
            },
          ],
        }),
      ],
    },
    {
      id: 'funciones',
      name: 'II. Funciones',
      topics: [
        buildTopic({
          id: 'funcion-lineal-formal',
          name: 'Funcion Lineal Formal',
          subtopics: ['Pendiente', 'Interseccion', 'Interpretacion grafica', 'Problemas de variacion'],
          difficultyRange: [6, 7],
          problemMix: 'mixed',
          questionCountRange: [4, 5],
          lessons: [
            {
              title: 'Pendiente e interseccion',
              difficulty: 6,
              questionCount: 4,
              problemMix: 'mixed',
              subtopics: ['pendiente', 'interseccion'],
              skills: ['funcion-lineal', 'pendiente', 'intercepto'],
            },
            {
              title: 'Interpretacion grafica lineal',
              difficulty: 7,
              questionCount: 5,
              problemMix: 'mixed',
              subtopics: ['interpretacion grafica'],
              skills: ['grafica', 'funcion-lineal', 'analisis'],
            },
            {
              title: 'Variacion lineal aplicada',
              difficulty: 7,
              questionCount: 5,
              problemMix: 'mixed',
              subtopics: ['problemas de variacion'],
              skills: ['variacion', 'modelacion', 'funcion-lineal'],
            },
          ],
        }),
        buildTopic({
          id: 'funcion-cuadratica',
          name: 'Funcion Cuadratica',
          subtopics: ['Forma canonica', 'Vertice', 'Grafica', 'Maximos y minimos', 'Modelacion'],
          difficultyRange: [8, 9],
          problemMix: 'mixed',
          questionCountRange: [5, 5],
          lessons: [
            {
              title: 'Forma canonica y vertice',
              difficulty: 8,
              questionCount: 5,
              problemMix: 'mixed',
              subtopics: ['forma canonica', 'vertice'],
              skills: ['funcion-cuadratica', 'vertice'],
            },
            {
              title: 'Grafica y extremos',
              difficulty: 9,
              questionCount: 5,
              problemMix: 'mixed',
              subtopics: ['grafica', 'maximos y minimos'],
              skills: ['funcion-cuadratica', 'grafica', 'optimizacion'],
            },
            {
              title: 'Modelacion cuadratica basica',
              difficulty: 9,
              questionCount: 5,
              problemMix: 'mixed',
              subtopics: ['modelacion (optimizacion basica)'],
              skills: ['modelacion', 'optimizacion', 'cuadratica'],
            },
          ],
        }),
      ],
    },
    {
      id: 'geometria',
      name: 'III. Geometria',
      topics: [
        buildTopic({
          id: 'semejanza-triangulos-formal',
          name: 'Semejanza de Triangulos (Formal)',
          subtopics: ['Criterios de semejanza', 'Teorema de Thales', 'Escalas'],
          difficultyRange: [7, 8],
          problemMix: 'mixed',
          questionCountRange: [5, 5],
          lessons: [
            {
              title: 'Criterios de semejanza',
              difficulty: 7,
              questionCount: 5,
              problemMix: 'mixed',
              subtopics: ['criterios de semejanza'],
              skills: ['semejanza', 'criterios'],
            },
            {
              title: 'Teorema de Thales',
              difficulty: 8,
              questionCount: 5,
              problemMix: 'mixed',
              subtopics: ['teorema de thales'],
              skills: ['thales', 'proporciones', 'geometria'],
            },
            {
              title: 'Escalas con semejanza',
              difficulty: 8,
              questionCount: 5,
              problemMix: 'mixed',
              subtopics: ['escalas'],
              skills: ['escalas', 'semejanza', 'modelacion'],
            },
          ],
        }),
        buildTopic({
          id: 'pitagoras-ampliado',
          name: 'Teorema de Pitagoras Ampliado',
          subtopics: ['Distancia en el plano', 'Aplicacion combinada'],
          difficultyRange: [6, 7],
          problemMix: 'mixed',
          questionCountRange: [4, 5],
          lessons: [
            {
              title: 'Pitagoras y distancia en el plano',
              difficulty: 6,
              questionCount: 4,
              problemMix: 'mixed',
              subtopics: ['distancia en el plano'],
              skills: ['pitagoras', 'plano-cartesiano'],
            },
            {
              title: 'Aplicaciones combinadas de Pitagoras',
              difficulty: 7,
              questionCount: 5,
              problemMix: 'mixed',
              subtopics: ['aplicacion combinada'],
              skills: ['pitagoras', 'modelacion', 'geometria'],
            },
          ],
        }),
        buildTopic({
          id: 'geometria-analitica-basica',
          name: 'Geometria Analitica Basica',
          subtopics: ['Distancia entre dos puntos', 'Punto medio', 'Pendiente entre puntos'],
          difficultyRange: [8, 9],
          problemMix: 'mixed',
          questionCountRange: [5, 5],
          lessons: [
            {
              title: 'Distancia entre dos puntos',
              difficulty: 8,
              questionCount: 5,
              problemMix: 'mixed',
              subtopics: ['distancia entre dos puntos'],
              skills: ['distancia', 'geometria-analitica'],
            },
            {
              title: 'Punto medio',
              difficulty: 8,
              questionCount: 5,
              problemMix: 'mixed',
              subtopics: ['punto medio'],
              skills: ['punto-medio', 'geometria-analitica'],
            },
            {
              title: 'Pendiente entre puntos',
              difficulty: 9,
              questionCount: 5,
              problemMix: 'mixed',
              subtopics: ['pendiente entre puntos'],
              skills: ['pendiente', 'geometria-analitica', 'modelacion'],
            },
          ],
        }),
      ],
    },
    {
      id: 'estadistica-probabilidad',
      name: 'IV. Estadistica y Probabilidad',
      topics: [
        buildTopic({
          id: 'estadistica-descriptiva-ampliada',
          name: 'Estadistica Descriptiva Ampliada',
          subtopics: ['Varianza basica', 'Interpretacion de graficos', 'Analisis comparativo'],
          difficultyRange: [6, 7],
          problemMix: 'mixed',
          questionCountRange: [4, 5],
          lessons: [
            {
              title: 'Varianza basica',
              difficulty: 6,
              questionCount: 4,
              problemMix: 'mixed',
              subtopics: ['varianza basica'],
              skills: ['estadistica', 'varianza'],
            },
            {
              title: 'Interpretacion de graficos',
              difficulty: 7,
              questionCount: 5,
              problemMix: 'mixed',
              subtopics: ['interpretacion de graficos'],
              skills: ['graficos', 'analisis'],
            },
            {
              title: 'Analisis comparativo de datos',
              difficulty: 7,
              questionCount: 5,
              problemMix: 'mixed',
              subtopics: ['analisis comparativo'],
              skills: ['comparacion', 'estadistica', 'interpretacion'],
            },
          ],
        }),
        buildTopic({
          id: 'probabilidad-compuesta-formal',
          name: 'Probabilidad Compuesta Formal',
          subtopics: ['Eventos dependientes', 'Probabilidad condicional basica', 'Diagramas de arbol'],
          difficultyRange: [8, 9],
          problemMix: 'mixed',
          questionCountRange: [5, 5],
          lessons: [
            {
              title: 'Eventos dependientes',
              difficulty: 8,
              questionCount: 5,
              problemMix: 'mixed',
              subtopics: ['eventos dependientes'],
              skills: ['probabilidad', 'dependencia'],
            },
            {
              title: 'Probabilidad condicional',
              difficulty: 9,
              questionCount: 5,
              problemMix: 'mixed',
              subtopics: ['probabilidad condicional basica'],
              skills: ['condicional', 'probabilidad', 'analisis'],
            },
            {
              title: 'Diagramas de arbol formales',
              difficulty: 9,
              questionCount: 5,
              problemMix: 'mixed',
              subtopics: ['diagramas de arbol'],
              skills: ['arbol', 'probabilidad', 'modelacion'],
            },
          ],
        }),
      ],
    },
  ],
  finalExam: {
    id: 'grade-3-final-exam',
    name: 'Examen Final 3ro Secundaria (Alto Rendimiento)',
    questionRange: [80, 80],
    passingScore: 0.8,
    xpMultiplier: 2,
    aiHelpAllowed: false,
    sections: [
      {
        id: 'algebra',
        name: 'Algebra',
        count: 30,
        topicIds: [
          'productos-notables-completos',
          'factorizacion-completa',
          'fracciones-algebraicas',
          'ecuaciones-cuadraticas',
          'sistemas-ecuaciones-2x2-formal',
        ],
      },
      {
        id: 'funciones',
        name: 'Funciones',
        count: 15,
        topicIds: ['funcion-lineal-formal', 'funcion-cuadratica'],
      },
      {
        id: 'geometria',
        name: 'Geometria',
        count: 15,
        topicIds: ['semejanza-triangulos-formal', 'pitagoras-ampliado', 'geometria-analitica-basica'],
      },
      {
        id: 'estadistica-probabilidad',
        name: 'Estadistica y Probabilidad',
        count: 10,
        topicIds: ['estadistica-descriptiva-ampliada', 'probabilidad-compuesta-formal'],
      },
      {
        id: 'modelacion-integrada',
        name: 'Modelacion Integrada',
        count: 10,
        topicIds: ['modelacion-integrada'],
      },
    ],
    distribution: [
      { topicId: 'productos-notables-completos', count: 6, difficultyRange: [6, 6] },
      { topicId: 'factorizacion-completa', count: 6, difficultyRange: [7, 9] },
      { topicId: 'fracciones-algebraicas', count: 6, difficultyRange: [7, 9] },
      { topicId: 'ecuaciones-cuadraticas', count: 6, difficultyRange: [8, 9] },
      { topicId: 'sistemas-ecuaciones-2x2-formal', count: 6, difficultyRange: [7, 8] },
      { topicId: 'funcion-lineal-formal', count: 7, difficultyRange: [6, 7] },
      { topicId: 'funcion-cuadratica', count: 8, difficultyRange: [8, 9] },
      { topicId: 'semejanza-triangulos-formal', count: 5, difficultyRange: [7, 8] },
      { topicId: 'pitagoras-ampliado', count: 5, difficultyRange: [6, 7] },
      { topicId: 'geometria-analitica-basica', count: 5, difficultyRange: [8, 9] },
      { topicId: 'estadistica-descriptiva-ampliada', count: 5, difficultyRange: [6, 7] },
      { topicId: 'probabilidad-compuesta-formal', count: 5, difficultyRange: [8, 9] },
      { topicId: 'modelacion-integrada', count: 10, difficultyRange: [8, 9] },
    ],
    mixDistribution: [
      { mix: 'mechanical', count: 28 },
      { mix: 'contextualized', count: 36 },
      { mix: 'advanced-modeling', count: 16 },
    ],
  },
}

export default grade3
