import { createLesson } from './shared.js'

const topic = (id, name, lessonDefs) => ({
  id,
  name,
  lessons: lessonDefs.map((lessonDef, index) =>
    createLesson({
      topicId: id,
      index: index + 1,
      ...lessonDef,
    }),
  ),
})

const grade1 = {
  id: 'grade-1',
  gradeNumber: 1,
  name: '1ro Secundaria',
  areas: [
    {
      id: 'aritmetica',
      name: 'Aritmetica',
      topics: [
        topic('numeros-naturales', 'Numeros Naturales', [
          {
            title: 'Problemas solo con suma',
            type: 'practice',
            difficulty: 1,
            skills: ['suma', 'problemas-cotidianos', 'lectura-de-datos'],
            xpReward: 14,
          },
          {
            title: 'Problemas solo con resta',
            type: 'practice',
            difficulty: 1,
            skills: ['resta', 'cantidades-restantes', 'diferencias'],
            xpReward: 14,
          },
          {
            title: 'Problemas solo con multiplicacion',
            type: 'practice',
            difficulty: 2,
            skills: ['multiplicacion', 'grupos-iguales', 'tablas'],
            xpReward: 18,
          },
          {
            title: 'Problemas solo con division',
            type: 'practice',
            difficulty: 2,
            skills: ['division', 'reparto-exacto', 'relacion-inversa'],
            xpReward: 18,
          },
          {
            title: 'Operaciones combinadas',
            type: 'practice',
            difficulty: 3,
            skills: ['jerarquia-de-operaciones', 'parentesis', 'calculo-mixto'],
            xpReward: 24,
          },
          {
            title: 'Repaso general',
            type: 'practice',
            difficulty: 3,
            skills: ['fluidez-operativa', 'estrategia', 'autocorreccion'],
            xpReward: 22,
          },
          {
            title: 'Examen del tema',
            type: 'exam',
            difficulty: 4,
            skills: ['evaluacion-integral', 'precision', 'tiempo-controlado'],
            xpReward: 70,
          },
        ]),
        topic('divisibilidad', 'Divisibilidad', [
          {
            title: 'Multiplos',
            type: 'practice',
            difficulty: 1,
            skills: ['multiplos', 'patrones', 'conteo'],
            xpReward: 14,
          },
          {
            title: 'Divisores',
            type: 'practice',
            difficulty: 2,
            skills: ['divisores', 'factorizacion-basica', 'validacion'],
            xpReward: 18,
          },
          {
            title: 'Criterios de divisibilidad (2,3,5,10)',
            type: 'practice',
            difficulty: 2,
            skills: ['criterios-divisibilidad', 'descarte-rapido', 'analisis'],
            xpReward: 18,
          },
          {
            title: 'Numeros primos y compuestos',
            type: 'practice',
            difficulty: 3,
            skills: ['primos', 'compuestos', 'clasificacion-numerica'],
            xpReward: 22,
          },
          {
            title: 'Problemas aplicados',
            type: 'practice',
            difficulty: 3,
            skills: ['modelado', 'divisibilidad-aplicada', 'razonamiento'],
            xpReward: 24,
          },
          {
            title: 'Examen',
            type: 'exam',
            difficulty: 4,
            skills: ['evaluacion-divisibilidad', 'precision', 'analisis'],
            xpReward: 68,
          },
        ]),
        topic('fracciones', 'Fracciones', [
          {
            title: 'Elementos de la fraccion',
            type: 'practice',
            difficulty: 1,
            skills: ['numerador', 'denominador', 'interpretacion'],
            xpReward: 14,
          },
          {
            title: 'Representacion grafica',
            type: 'practice',
            difficulty: 1,
            skills: ['modelado-visual', 'partes-del-todo', 'equivalencia-visual'],
            xpReward: 14,
          },
          {
            title: 'Fracciones equivalentes',
            type: 'practice',
            difficulty: 2,
            skills: ['equivalencia', 'simplificacion', 'amplificacion'],
            xpReward: 18,
          },
          {
            title: 'Comparacion',
            type: 'practice',
            difficulty: 2,
            skills: ['comparacion', 'denominador-comun', 'orden'],
            xpReward: 18,
          },
          {
            title: 'Suma y resta',
            type: 'practice',
            difficulty: 3,
            skills: ['suma-fracciones', 'resta-fracciones', 'mcm'],
            xpReward: 24,
          },
          {
            title: 'Multiplicacion',
            type: 'practice',
            difficulty: 3,
            skills: ['producto-fracciones', 'simplificacion-previa', 'reduccion'],
            xpReward: 24,
          },
          {
            title: 'Problemas aplicados',
            type: 'practice',
            difficulty: 3,
            skills: ['fracciones-en-contexto', 'modelado', 'decision-operacion'],
            xpReward: 24,
          },
          {
            title: 'Examen',
            type: 'exam',
            difficulty: 4,
            skills: ['evaluacion-fracciones', 'precision', 'razonamiento'],
            xpReward: 72,
          },
        ]),
      ],
    },
    {
      id: 'geometria',
      name: 'Geometria',
      topics: [
        topic('figuras-planas', 'Figuras Planas', [
          {
            title: 'Clasificacion de triangulos',
            type: 'practice',
            difficulty: 1,
            skills: ['triangulos', 'clasificacion-por-lados', 'clasificacion-por-angulos'],
            xpReward: 14,
          },
          {
            title: 'Cuadrilateros',
            type: 'practice',
            difficulty: 2,
            skills: ['cuadrilateros', 'propiedades', 'identificacion'],
            xpReward: 18,
          },
          {
            title: 'Perimetro',
            type: 'practice',
            difficulty: 2,
            skills: ['perimetro', 'suma-de-lados', 'unidad-lineal'],
            xpReward: 18,
          },
          {
            title: 'Area de cuadrado y rectangulo',
            type: 'practice',
            difficulty: 2,
            skills: ['area-cuadrado', 'area-rectangulo', 'unidades-cuadradas'],
            xpReward: 20,
          },
          {
            title: 'Area de triangulo',
            type: 'practice',
            difficulty: 3,
            skills: ['area-triangulo', 'base-altura', 'division-entre-dos'],
            xpReward: 24,
          },
          {
            title: 'Problemas aplicados',
            type: 'practice',
            difficulty: 3,
            skills: ['geometria-aplicada', 'perimetro-y-area', 'modelado'],
            xpReward: 24,
          },
          {
            title: 'Examen',
            type: 'exam',
            difficulty: 4,
            skills: ['evaluacion-geometria-plana', 'precision', 'analisis'],
            xpReward: 70,
          },
        ]),
        topic('angulos', 'Angulos', [
          {
            title: 'Tipos de angulos',
            type: 'practice',
            difficulty: 1,
            skills: ['agudo', 'recto', 'obtuso'],
            xpReward: 14,
          },
          {
            title: 'Medicion',
            type: 'practice',
            difficulty: 2,
            skills: ['medicion-con-transportador', 'estimacion', 'grados'],
            xpReward: 18,
          },
          {
            title: 'Complementarios y suplementarios',
            type: 'practice',
            difficulty: 3,
            skills: ['angulo-complementario', 'angulo-suplementario', 'suma-de-angulos'],
            xpReward: 24,
          },
          {
            title: 'Problemas geometricos',
            type: 'practice',
            difficulty: 3,
            skills: ['angulos-en-figuras', 'deduccion', 'resolucion'],
            xpReward: 24,
          },
          {
            title: 'Examen',
            type: 'exam',
            difficulty: 4,
            skills: ['evaluacion-angulos', 'precision', 'argumentacion'],
            xpReward: 66,
          },
        ]),
      ],
    },
    {
      id: 'algebra',
      name: 'Algebra',
      topics: [
        topic('expresiones-algebraicas', 'Expresiones Algebraicas', [
          {
            title: 'Concepto de variable',
            type: 'practice',
            difficulty: 1,
            skills: ['variable', 'simbolo', 'significado'],
            xpReward: 14,
          },
          {
            title: 'Traduccion verbal a algebraico',
            type: 'practice',
            difficulty: 2,
            skills: ['traduccion', 'expresion-algebraica', 'lectura-matematica'],
            xpReward: 18,
          },
          {
            title: 'Evaluacion de expresiones',
            type: 'practice',
            difficulty: 2,
            skills: ['sustitucion', 'operaciones', 'orden'],
            xpReward: 18,
          },
          {
            title: 'Simplificacion',
            type: 'practice',
            difficulty: 3,
            skills: ['terminos-semejantes', 'reduccion', 'simplificacion'],
            xpReward: 24,
          },
          {
            title: 'Problemas aplicados',
            type: 'practice',
            difficulty: 3,
            skills: ['modelado-algebraico', 'interpretacion', 'resolucion'],
            xpReward: 24,
          },
          {
            title: 'Examen',
            type: 'exam',
            difficulty: 4,
            skills: ['evaluacion-expresiones', 'precision', 'consistencia'],
            xpReward: 68,
          },
        ]),
        topic('ecuaciones-basicas', 'Ecuaciones Basicas', [
          {
            title: 'x + a = b',
            type: 'practice',
            difficulty: 2,
            skills: ['ecuacion-lineal', 'operacion-inversa', 'despeje'],
            xpReward: 18,
          },
          {
            title: 'ax = b',
            type: 'practice',
            difficulty: 2,
            skills: ['ecuacion-lineal', 'division', 'despeje'],
            xpReward: 18,
          },
          {
            title: 'Ecuaciones con dos operaciones',
            type: 'practice',
            difficulty: 3,
            skills: ['ecuacion-dos-pasos', 'prioridad', 'despeje'],
            xpReward: 24,
          },
          {
            title: 'Problemas escritos',
            type: 'practice',
            difficulty: 3,
            skills: ['modelado-verbal', 'planteamiento', 'solucion'],
            xpReward: 24,
          },
          {
            title: 'Repaso',
            type: 'practice',
            difficulty: 3,
            skills: ['fluidez', 'verificacion', 'autoevaluacion'],
            xpReward: 22,
          },
          {
            title: 'Examen',
            type: 'exam',
            difficulty: 4,
            skills: ['evaluacion-ecuaciones', 'precision', 'tiempo-controlado'],
            xpReward: 68,
          },
        ]),
      ],
    },
    {
      id: 'estadistica-probabilidad',
      name: 'Estadistica y Probabilidad',
      topics: [
        topic('estadistica', 'Estadistica', [
          {
            title: 'Recoleccion de datos',
            type: 'practice',
            difficulty: 1,
            skills: ['datos', 'muestra-basica', 'registro'],
            xpReward: 14,
          },
          {
            title: 'Tabla de frecuencia',
            type: 'practice',
            difficulty: 2,
            skills: ['frecuencia', 'conteo', 'organizacion'],
            xpReward: 18,
          },
          {
            title: 'Grafico de barras',
            type: 'practice',
            difficulty: 2,
            skills: ['lectura-grafica', 'representacion', 'comparacion'],
            xpReward: 18,
          },
          {
            title: 'Media aritmetica',
            type: 'practice',
            difficulty: 3,
            skills: ['media', 'suma', 'division'],
            xpReward: 24,
          },
          {
            title: 'Examen',
            type: 'exam',
            difficulty: 4,
            skills: ['evaluacion-estadistica', 'interpretacion', 'precision'],
            xpReward: 64,
          },
        ]),
        topic('probabilidad', 'Probabilidad', [
          {
            title: 'Experimento aleatorio',
            type: 'practice',
            difficulty: 1,
            skills: ['azar', 'evento', 'experimento'],
            xpReward: 14,
          },
          {
            title: 'Espacio muestral',
            type: 'practice',
            difficulty: 2,
            skills: ['espacio-muestral', 'conteo-casos', 'eventos'],
            xpReward: 18,
          },
          {
            title: 'Probabilidad simple',
            type: 'practice',
            difficulty: 3,
            skills: ['probabilidad-simple', 'casos-favorables', 'casos-posibles'],
            xpReward: 24,
          },
          {
            title: 'Examen',
            type: 'exam',
            difficulty: 4,
            skills: ['evaluacion-probabilidad', 'razonamiento', 'precision'],
            xpReward: 62,
          },
        ]),
      ],
    },
    {
      id: 'medicion',
      name: 'Medicion',
      topics: [
        topic('unidades-de-medida', 'Unidades de Medida', [
          {
            title: 'Longitud',
            type: 'practice',
            difficulty: 1,
            skills: ['longitud', 'metro', 'conversion-basica'],
            xpReward: 14,
          },
          {
            title: 'Masa',
            type: 'practice',
            difficulty: 1,
            skills: ['masa', 'gramo', 'kilogramo'],
            xpReward: 14,
          },
          {
            title: 'Capacidad',
            type: 'practice',
            difficulty: 2,
            skills: ['capacidad', 'litro', 'mililitro'],
            xpReward: 18,
          },
          {
            title: 'Conversion de unidades',
            type: 'practice',
            difficulty: 3,
            skills: ['conversion', 'factores-de-conversion', 'equivalencias'],
            xpReward: 24,
          },
          {
            title: 'Problemas aplicados',
            type: 'practice',
            difficulty: 3,
            skills: ['medicion-en-contexto', 'seleccion-de-unidad', 'estimacion'],
            xpReward: 24,
          },
          {
            title: 'Examen',
            type: 'exam',
            difficulty: 4,
            skills: ['evaluacion-medicion', 'precision', 'aplicacion'],
            xpReward: 66,
          },
        ]),
      ],
    },
  ],
  finalExam: {
    id: 'grade-1-final-exam',
    name: 'Examen Final 1ro Secundaria',
    questionRange: [30, 40],
    passingScore: 0.7,
    xpMultiplier: 2,
    aiHelpAllowed: false,
    distribution: [
      { topicId: 'numeros-naturales', count: 4, difficultyRange: [3, 4] },
      { topicId: 'divisibilidad', count: 2, difficultyRange: [2, 4] },
      { topicId: 'fracciones', count: 2, difficultyRange: [3, 4] },
      { topicId: 'figuras-planas', count: 4, difficultyRange: [2, 4] },
      { topicId: 'angulos', count: 2, difficultyRange: [2, 4] },
      { topicId: 'ecuaciones-basicas', count: 3, difficultyRange: [2, 4] },
      { topicId: 'expresiones-algebraicas', count: 3, difficultyRange: [2, 4] },
      { topicId: 'estadistica', count: 3, difficultyRange: [2, 4] },
      { topicId: 'probabilidad', count: 2, difficultyRange: [2, 4] },
      { topicId: 'unidades-de-medida', count: 5, difficultyRange: [2, 4] },
    ],
  },
}

export default grade1
