import grade1 from './grade1.js'
import grade2 from './grade2.js'
import grade3 from './grade3.js'
import grade4 from './grade4.js'
import grade5 from './grade5.js'
import { findTopicInGrade } from './shared.js'

const BRANCH_NAME_MAP = {
  aritmetica: 'Aritmetica',
  algebra: 'Algebra',
  geometria: 'Geometria',
  'estadistica-probabilidad': 'Estadistica y Probabilidad',
  medicion: 'Medicion',
  calculo: 'Calculo',
  integrador: 'Integrador',
}

const deepClone = (value) => JSON.parse(JSON.stringify(value))

const slugify = (value) => {
  return String(value ?? '')
    .trim()
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '')
}

const countLessonsInGrade = (grade) => {
  return (grade?.areas || []).reduce((areaTotal, area) => {
    const topicTotal = (area?.topics || []).reduce((acc, topic) => acc + (topic?.lessons?.length || 0), 0)
    return areaTotal + topicTotal
  }, 0)
}

const buildProgressId = ({ gradeId, topicId, lessonId }) => `${gradeId}:${topicId}:${lessonId}`
const buildLessonRouteId = ({ gradeId, topicId, lessonId }) => `${gradeId}~${topicId}~${lessonId}`

const resolveExpansionTargetTopic = (grade) => {
  const areas = grade?.areas || []
  if (!areas.length) return null

  const integratorArea = areas.find((area) => String(area.id || '').toLowerCase().includes('integrador'))
  const targetArea = integratorArea || areas[areas.length - 1]
  const topics = targetArea?.topics || []

  if (!topics.length) {
    const fallbackTopic = {
      id: `${targetArea.id}-consolidacion`,
      name: 'Consolidacion',
      lessons: [],
    }
    targetArea.topics = [fallbackTopic]
    return fallbackTopic
  }

  return topics[topics.length - 1]
}

const appendAutoReinforcementLesson = (grade, sequence) => {
  const targetTopic = resolveExpansionTargetTopic(grade)
  if (!targetTopic) return null

  const existingLessonIds = new Set((targetTopic.lessons || []).map((lesson) => String(lesson.id)))
  let lessonId = `${targetTopic.id}-refuerzo-${sequence}`
  let cursor = sequence
  while (existingLessonIds.has(lessonId)) {
    cursor += 1
    lessonId = `${targetTopic.id}-refuerzo-${cursor}`
  }

  const lesson = {
    id: lessonId,
    title: `Taller de consolidacion ${grade.gradeNumber}.${cursor}`,
    type: 'practice',
    difficulty: Math.max(2, Math.min(5, Number(grade.gradeNumber || 1))),
    skills: ['consolidacion', 'aplicacion', 'razonamiento'],
    xpReward: 18 + Number(grade.gradeNumber || 1) * 3,
    autoGenerated: true,
  }

  targetTopic.lessons = [...(targetTopic.lessons || []), lesson]
  return lesson
}

const enforceIncreasingLessonCounts = (sourceGrades = []) => {
  const grades = sourceGrades
    .map((grade) => deepClone(grade))
    .sort((a, b) => Number(a.gradeNumber || 0) - Number(b.gradeNumber || 0))

  let previousCount = -1

  for (const grade of grades) {
    const addedLessons = []
    let lessonCount = countLessonsInGrade(grade)
    let sequence = 1

    while (lessonCount <= previousCount) {
      const inserted = appendAutoReinforcementLesson(grade, sequence)
      if (!inserted) break
      addedLessons.push(inserted.id)
      lessonCount += 1
      sequence += 1
    }

    grade.lessonCount = lessonCount
    grade.autoExpandedLessons = addedLessons
    previousCount = lessonCount
  }

  return grades
}

const resolveBranchId = (area) => {
  const bucket = `${area?.id || ''} ${area?.name || ''}`.toLowerCase()
  if (bucket.includes('algebra')) return 'algebra'
  if (bucket.includes('geometria') || bucket.includes('trigonometr')) return 'geometria'
  if (bucket.includes('estadistica') || bucket.includes('probabilidad')) return 'estadistica-probabilidad'
  if (bucket.includes('aritmetica')) return 'aritmetica'
  if (bucket.includes('medicion')) return 'medicion'
  if (bucket.includes('calculo')) return 'calculo'
  if (bucket.includes('integrador')) return 'integrador'
  return slugify(area?.id || area?.name || 'rama')
}

const buildBranchCollection = (grades = []) => {
  const branchMap = new Map()

  for (const grade of grades) {
    for (const area of grade?.areas || []) {
      const branchId = resolveBranchId(area)
      if (!branchMap.has(branchId)) {
        branchMap.set(branchId, {
          id: branchId,
          name: BRANCH_NAME_MAP[branchId] || area?.name || branchId,
          description: `Modulo por rama: ${BRANCH_NAME_MAP[branchId] || area?.name || branchId}`,
          lessonCount: 0,
          gradeIds: new Set(),
          modules: [],
        })
      }

      const branch = branchMap.get(branchId)
      branch.gradeIds.add(grade.id)

      const module = {
        id: `${grade.id}:${area.id}`,
        gradeId: grade.id,
        gradeNumber: Number(grade.gradeNumber || 0),
        gradeName: grade.name || grade.id,
        areaId: area.id,
        areaName: area.name || area.id,
        lessonCount: 0,
        topics: [],
      }

      for (const topic of area?.topics || []) {
        const lessons = (topic?.lessons || []).map((lesson) => {
          const progressId = buildProgressId({
            gradeId: grade.id,
            topicId: topic.id,
            lessonId: lesson.id,
          })

          return {
            ...lesson,
            gradeId: grade.id,
            gradeNumber: Number(grade.gradeNumber || 0),
            gradeName: grade.name || grade.id,
            areaId: area.id,
            areaName: area.name || area.id,
            topicId: topic.id,
            topicName: topic.name || topic.id,
            progressId,
            routeId: buildLessonRouteId({
              gradeId: grade.id,
              topicId: topic.id,
              lessonId: lesson.id,
            }),
          }
        })

        module.lessonCount += lessons.length
        module.topics.push({
          id: topic.id,
          name: topic.name || topic.id,
          lessonCount: lessons.length,
          lessons,
        })
      }

      if (module.lessonCount > 0) {
        module.topics.sort((a, b) => a.name.localeCompare(b.name))
        branch.modules.push(module)
        branch.lessonCount += module.lessonCount
      }
    }
  }

  return [...branchMap.values()]
    .map((branch) => ({
      ...branch,
      gradeCount: branch.gradeIds.size,
      gradeIds: [...branch.gradeIds],
      modules: branch.modules.sort((a, b) => a.gradeNumber - b.gradeNumber || a.areaName.localeCompare(b.areaName)),
    }))
    .sort((a, b) => a.name.localeCompare(b.name))
}

export const CURRICULUM_GRADES = enforceIncreasingLessonCounts([grade1, grade2, grade3, grade4, grade5])

export const CURRICULUM_BRANCHES = buildBranchCollection(CURRICULUM_GRADES)

export const getQuestionTypeByDifficulty = (difficulty) => {
  return Number(difficulty) >= 3 ? 'input' : 'multiple-choice'
}

const gradeIndexById = new Map()
const gradeIndexByNumber = new Map()
const branchIndexById = new Map()

for (const grade of CURRICULUM_GRADES) {
  gradeIndexById.set(grade.id, grade)
  gradeIndexByNumber.set(Number(grade.gradeNumber), grade)
}

for (const branch of CURRICULUM_BRANCHES) {
  branchIndexById.set(branch.id, branch)
}

const parseGradeKey = (grade) => {
  if (grade == null) return null

  if (typeof grade === 'number') return Number.isFinite(grade) ? Math.floor(grade) : null

  const asString = String(grade).trim().toLowerCase()
  if (!asString) return null

  if (/^grade-\d+$/.test(asString)) {
    const asId = gradeIndexById.get(asString)
    return asId ? Number(asId.gradeNumber) : null
  }

  const numericMatch = asString.match(/\d+/)
  if (!numericMatch) return null
  const parsed = Number(numericMatch[0])
  return Number.isFinite(parsed) ? Math.floor(parsed) : null
}

export const getGradeCurriculum = (grade) => {
  const parsed = parseGradeKey(grade)
  if (!parsed) return null
  return gradeIndexByNumber.get(parsed) || null
}

export const getTopicByGradeAndId = (grade, topicId) => {
  const gradeData = getGradeCurriculum(grade)
  if (!gradeData) return null
  return findTopicInGrade(gradeData, topicId)
}

export const getFinalExamBlueprint = (grade) => {
  const gradeData = getGradeCurriculum(grade)
  return gradeData?.finalExam || null
}

export const getCurriculumBranch = (branchId) => {
  const key = String(branchId ?? '').trim().toLowerCase()
  if (!key) return null
  return branchIndexById.get(key) || null
}

export const CURRICULUM_INDEX = {
  byId: gradeIndexById,
  byNumber: gradeIndexByNumber,
  branchById: branchIndexById,
}
