export const CURRICULUM = [
  {
    id: 'nivel-1-fundamentos',
    level: 1,
    title: 'Nivel 1 - Fundamentos',
    lessons: [
      {
        id: 'n1-sumas',
        title: 'Sumas',
        description: 'Construye fluidez en sumas simples y con llevadas.',
        subtopics: ['suma sin llevadas', 'suma con llevadas', 'suma en contexto'],
        difficulty: 1,
        questionTypes: ['multiple-choice'],
      },
      {
        id: 'n1-restas',
        title: 'Restas',
        description: 'Practica restas directas y con reagrupacion.',
        subtopics: ['resta simple', 'resta con llevadas', 'verificacion con suma'],
        difficulty: 1,
        questionTypes: ['multiple-choice'],
      },
      {
        id: 'n1-multiplicaciones',
        title: 'Multiplicaciones',
        description: 'Refuerza tablas y estrategias de producto.',
        subtopics: ['tablas basicas', 'propiedad distributiva', 'estimacion'],
        difficulty: 2,
        questionTypes: ['multiple-choice'],
      },
      {
        id: 'n1-divisiones',
        title: 'Divisiones',
        description: 'Resuelve divisiones exactas y con residuo.',
        subtopics: ['division exacta', 'division con residuo', 'relacion con multiplicacion'],
        difficulty: 2,
        questionTypes: ['multiple-choice'],
      },
      {
        id: 'n1-orden-operaciones',
        title: 'Orden de operaciones',
        description: 'Aplica jerarquia de operaciones en expresiones mixtas.',
        subtopics: ['parentesis', 'multiplicacion y division', 'suma y resta'],
        difficulty: 3,
        questionTypes: ['input'],
      },
    ],
  },
  {
    id: 'nivel-2-fracciones-decimales',
    level: 2,
    title: 'Nivel 2 - Fracciones y Decimales',
    lessons: [
      {
        id: 'n2-fracciones-basicas',
        title: 'Fracciones basicas',
        description: 'Interpreta numerador, denominador y equivalencias.',
        subtopics: ['partes del todo', 'fracciones equivalentes', 'comparacion'],
        difficulty: 1,
        questionTypes: ['multiple-choice'],
      },
      {
        id: 'n2-simplificacion-fracciones',
        title: 'Simplificacion',
        description: 'Reduce fracciones a su minima expresion.',
        subtopics: ['mcd', 'fracciones irreducibles', 'verificacion'],
        difficulty: 2,
        questionTypes: ['multiple-choice'],
      },
      {
        id: 'n2-operaciones-fracciones',
        title: 'Operaciones con fracciones',
        description: 'Suma, resta, multiplica y divide fracciones.',
        subtopics: ['denominador comun', 'producto de fracciones', 'division por reciproco'],
        difficulty: 3,
        questionTypes: ['input'],
      },
      {
        id: 'n2-decimales',
        title: 'Decimales',
        description: 'Opera con numeros decimales con precision.',
        subtopics: ['valor posicional', 'suma y resta decimal', 'multiplicacion decimal'],
        difficulty: 2,
        questionTypes: ['multiple-choice'],
      },
      {
        id: 'n2-conversion-fraccion-decimal',
        title: 'Conversion fraccion-decimal',
        description: 'Convierte entre representaciones de una misma cantidad.',
        subtopics: ['fraccion a decimal', 'decimal a fraccion', 'fracciones periodicas'],
        difficulty: 3,
        questionTypes: ['input'],
      },
    ],
  },
  {
    id: 'nivel-3-proporciones-porcentajes',
    level: 3,
    title: 'Nivel 3 - Proporciones y Porcentajes',
    lessons: [
      {
        id: 'n3-regla-de-tres',
        title: 'Regla de tres',
        description: 'Resuelve problemas proporcionales directos.',
        subtopics: ['proporciones', 'despeje', 'validacion'],
        difficulty: 2,
        questionTypes: ['multiple-choice'],
      },
      {
        id: 'n3-porcentajes',
        title: 'Porcentajes',
        description: 'Calcula porcentajes sobre cantidades.',
        subtopics: ['porcentaje de un numero', 'aumento porcentual', 'disminucion porcentual'],
        difficulty: 2,
        questionTypes: ['multiple-choice'],
      },
      {
        id: 'n3-aumentos-descuentos',
        title: 'Aumentos y descuentos',
        description: 'Aplica variaciones de precio y valor.',
        subtopics: ['descuento simple', 'aumento simple', 'precio final'],
        difficulty: 3,
        questionTypes: ['input'],
      },
      {
        id: 'n3-interes-simple',
        title: 'Interes simple',
        description: 'Modela intereses simples en problemas financieros basicos.',
        subtopics: ['capital', 'tasa', 'tiempo'],
        difficulty: 3,
        questionTypes: ['input'],
      },
    ],
  },
  {
    id: 'nivel-4-algebra-basica',
    level: 4,
    title: 'Nivel 4 - Algebra Basica',
    lessons: [
      {
        id: 'n4-expresiones-algebraicas',
        title: 'Expresiones algebraicas',
        description: 'Identifica terminos, coeficientes y variables.',
        subtopics: ['terminos semejantes', 'coeficientes', 'evaluacion'],
        difficulty: 2,
        questionTypes: ['multiple-choice'],
      },
      {
        id: 'n4-ecuaciones-1-paso',
        title: 'Ecuaciones de 1 paso',
        description: 'Resuelve ecuaciones simples aplicando operacion inversa.',
        subtopics: ['sumar/restar', 'multiplicar/dividir', 'comprobacion'],
        difficulty: 2,
        questionTypes: ['multiple-choice'],
      },
      {
        id: 'n4-ecuaciones-2-pasos',
        title: 'Ecuaciones de 2 pasos',
        description: 'Resuelve ecuaciones lineales en dos movimientos.',
        subtopics: ['despeje progresivo', 'orden de operaciones', 'verificacion'],
        difficulty: 3,
        questionTypes: ['input'],
      },
      {
        id: 'n4-problemas-incognitas',
        title: 'Problemas con incognitas',
        description: 'Traduce enunciados a ecuaciones y resuelve.',
        subtopics: ['modelado', 'planteamiento', 'interpretacion de resultados'],
        difficulty: 3,
        questionTypes: ['input'],
      },
    ],
  },
  {
    id: 'nivel-5-pensamiento-matematico',
    level: 5,
    title: 'Nivel 5 - Pensamiento Matematico',
    lessons: [
      {
        id: 'n5-problemas-verbales',
        title: 'Problemas verbales',
        description: 'Extrae datos y diseña estrategias de resolucion.',
        subtopics: ['lectura matematica', 'identificacion de datos', 'plan de solucion'],
        difficulty: 3,
        questionTypes: ['input'],
      },
      {
        id: 'n5-razonamiento-logico',
        title: 'Razonamiento logico',
        description: 'Ejercita inferencias y consistencia de argumentos.',
        subtopics: ['deduccion', 'condicionales', 'contraejemplos'],
        difficulty: 3,
        questionTypes: ['input'],
      },
      {
        id: 'n5-patrones',
        title: 'Patrones',
        description: 'Detecta regularidades numericas y algebraicas.',
        subtopics: ['secuencias', 'reglas de formacion', 'prediccion'],
        difficulty: 3,
        questionTypes: ['input'],
      },
    ],
  },
]

export const getQuestionTypeByDifficulty = (difficulty) => {
  return Number(difficulty) >= 3 ? 'input' : 'multiple-choice'
}
