import { buildLessonsFromOutline } from '../core/shared.js'

const topic = (id, name, outline) => ({
  id,
  name,
  lessons: buildLessonsFromOutline(id, outline, 5),
  skeleton: true,
})

const grade5 = {
  id: 'grade-5',
  gradeNumber: 5,
  name: '5to Secundaria',
  areas: [
    {
      id: 'algebra-avanzada',
      name: 'Algebra Avanzada',
      topics: [
        topic('funciones-avanzadas', 'Funciones Avanzadas', [
          'Clasificacion de funciones',
          'Dominio y rango avanzado',
          'Funciones racionales',
          'Asintotas',
          'Transformaciones de funciones',
          'Composicion de funciones',
          'Funcion inversa',
          'Funcion exponencial',
          'Funcion logaritmica',
          'Modelacion matematica',
          'Problemas integradores',
          'Examen',
        ]),
        topic('matrices-y-determinantes', 'Matrices y Determinantes', [
          'Concepto de matriz',
          'Operaciones con matrices',
          'Multiplicacion de matrices',
          'Determinante 2x2',
          'Determinante 3x3',
          'Regla de Cramer',
          'Sistemas con matrices',
          'Problemas aplicados',
          'Repaso',
          'Examen',
        ]),
        topic('numeros-complejos', 'Numeros Complejos', [
          'Unidad imaginaria',
          'Forma binomica',
          'Operaciones basicas',
          'Potencias de i',
          'Forma polar (introduccion)',
          'Problemas algebraicos',
          'Aplicaciones',
          'Examen',
        ]),
      ],
    },
    {
      id: 'geometria-trigonometria',
      name: 'Geometria y Trigonometria',
      topics: [
        topic('trigonometria-avanzada', 'Trigonometria Avanzada', [
          'Identidades trigonometricas',
          'Identidades dobles y mitad',
          'Ecuaciones trigonometricas',
          'Graficas trigonometricas',
          'Funciones seno y coseno',
          'Funcion tangente',
          'Aplicaciones fisicas',
          'Problemas combinados',
          'Modelacion periodica',
          'Repaso avanzado',
          'Problemas tipo admision',
          'Examen',
        ]),
        topic('geometria-analitica-avanzada', 'Geometria Analitica Avanzada', [
          'Parabola (forma canonica)',
          'Elipse',
          'Hiperbola',
          'Traslacion de ejes',
          'Interseccion recta-conica',
          'Problemas aplicados',
          'Analisis grafico',
          'Repaso',
          'Examen',
        ]),
      ],
    },
    {
      id: 'estadistica-probabilidad-avanzada',
      name: 'Estadistica y Probabilidad Avanzada',
      topics: [
        topic('combinatoria', 'Combinatoria', [
          'Principio multiplicativo',
          'Permutaciones',
          'Combinaciones',
          'Variaciones',
          'Problemas con restricciones',
          'Problemas tipo examen',
          'Probabilidad combinatoria',
          'Repaso',
          'Examen',
        ]),
        topic('probabilidad-avanzada', 'Probabilidad Avanzada', [
          'Probabilidad condicional avanzada',
          'Teorema de Bayes (introduccion)',
          'Variables aleatorias discretas',
          'Esperanza matematica',
          'Distribucion binomial (introduccion)',
          'Problemas aplicados',
          'Repaso',
          'Examen',
        ]),
      ],
    },
    {
      id: 'calculo-introduccion',
      name: 'Introduccion al Calculo',
      topics: [
        topic('limites', 'Limites', [
          'Concepto intuitivo',
          'Limites algebraicos',
          'Limites con factorizacion',
          'Limites con racionalizacion',
          'Limites laterales',
          'Continuidad',
          'Problemas aplicados',
          'Examen',
        ]),
        topic('derivada-introduccion', 'Derivada (Introduccion)', [
          'Concepto de razon de cambio',
          'Definicion basica',
          'Derivada de potencia',
          'Derivada de polinomios',
          'Aplicacion a recta tangente',
          'Maximos y minimos basicos',
          'Problemas aplicados',
          'Examen',
        ]),
      ],
    },
    {
      id: 'integrador',
      name: 'Problemas Integradores',
      topics: [
        topic('problemas-integradores', 'Problemas Integradores', [
          'Modelacion matematica',
          'Problemas tipo admision',
          'Examen integrador',
        ]),
      ],
    },
  ],
  finalExam: {
    id: 'grade-5-final-exam',
    name: 'Examen Final 5to Secundaria',
    questionRange: [70, 80],
    passingScore: 0.7,
    xpMultiplier: 2,
    aiHelpAllowed: false,
    distribution: [
      { topicId: 'funciones-avanzadas', count: 8, difficultyRange: [4, 5] },
      { topicId: 'matrices-y-determinantes', count: 6, difficultyRange: [4, 5] },
      { topicId: 'numeros-complejos', count: 6, difficultyRange: [4, 5] },
      { topicId: 'trigonometria-avanzada', count: 10, difficultyRange: [4, 5] },
      { topicId: 'geometria-analitica-avanzada', count: 10, difficultyRange: [4, 5] },
      { topicId: 'combinatoria', count: 8, difficultyRange: [4, 5] },
      { topicId: 'probabilidad-avanzada', count: 7, difficultyRange: [4, 5] },
      { topicId: 'limites', count: 8, difficultyRange: [4, 5] },
      { topicId: 'derivada-introduccion', count: 7, difficultyRange: [4, 5] },
      { topicId: 'problemas-integradores', count: 10, difficultyRange: [4, 5] },
    ],
  },
}

export default grade5
