import { createLesson } from '../core/shared.js'

const buildTopic = ({
  id,
  name,
  subtopics = [],
  difficultyRange = [5, 6],
  problemMix = 'mixed',
  questionCountRange = [4, 5],
  lessons = [],
}) => ({
  id,
  name,
  subtopics,
  difficultyRange,
  problemMix,
  questionCountRange,
  lessons: lessons.map((lesson, index) =>
    createLesson({
      topicId: id,
      index: index + 1,
      ...lesson,
      problemMix: lesson.problemMix || problemMix,
      subtopics: lesson.subtopics || [],
    }),
  ),
})

const grade2 = {
  id: 'grade-2',
  gradeNumber: 2,
  name: '2do Secundaria - Matematicas (Alto Rendimiento)',
  objective:
    'Consolidar pensamiento algebraico avanzado, funciones, sistemas, ecuaciones e inecuaciones con modelacion matematica de nivel elite.',
  areas: [
    {
      id: 'aritmetica-avanzada',
      name: 'I. Aritmetica Avanzada',
      topics: [
        buildTopic({
          id: 'potencias-propiedades',
          name: 'Potencias y Propiedades',
          subtopics: [
            'Leyes de exponentes',
            'Potencias de base negativa',
            'Potencias de 10',
            'Aplicacion en crecimiento poblacional simple',
          ],
          difficultyRange: [5, 6],
          problemMix: 'mixed',
          questionCountRange: [4, 5],
          lessons: [
            {
              title: 'Leyes de exponentes',
              difficulty: 5,
              questionCount: 4,
              problemMix: 'mixed',
              subtopics: ['leyes de exponentes'],
              skills: ['potencias', 'leyes', 'calculo'],
            },
            {
              title: 'Base negativa y potencias de 10',
              difficulty: 6,
              questionCount: 4,
              problemMix: 'mixed',
              subtopics: ['potencias de base negativa', 'potencias de 10'],
              skills: ['base-negativa', 'potencias-de-10', 'analisis'],
            },
            {
              title: 'Crecimiento poblacional simple con potencias',
              difficulty: 6,
              questionCount: 5,
              problemMix: 'mixed',
              subtopics: ['aplicacion en crecimiento poblacional simple'],
              skills: ['crecimiento', 'modelacion', 'potencias'],
            },
          ],
        }),
        buildTopic({
          id: 'raices-cuadradas-cubicas',
          name: 'Raices Cuadradas y Cubicas',
          subtopics: ['Raiz exacta', 'Aproximacion', 'Aplicaciones geometricas'],
          difficultyRange: [5, 6],
          problemMix: 'mixed',
          questionCountRange: [4, 5],
          lessons: [
            {
              title: 'Raices exactas cuadradas y cubicas',
              difficulty: 5,
              questionCount: 4,
              problemMix: 'mixed',
              subtopics: ['raiz exacta'],
              skills: ['raiz-cuadrada', 'raiz-cubica', 'exactitud'],
            },
            {
              title: 'Aproximacion de raices',
              difficulty: 6,
              questionCount: 4,
              problemMix: 'mixed',
              subtopics: ['aproximacion'],
              skills: ['aproximacion', 'estimacion', 'raices'],
            },
            {
              title: 'Aplicaciones geometricas de raices',
              difficulty: 6,
              questionCount: 5,
              problemMix: 'mixed',
              subtopics: ['aplicaciones geometricas'],
              skills: ['geometria', 'raices', 'aplicacion'],
            },
          ],
        }),
        buildTopic({
          id: 'notacion-cientifica',
          name: 'Notacion Cientifica',
          subtopics: ['Conversion', 'Operaciones', 'Aplicacion en ciencia'],
          difficultyRange: [6, 6],
          problemMix: 'mixed',
          questionCountRange: [4, 5],
          lessons: [
            {
              title: 'Conversion a notacion cientifica',
              difficulty: 6,
              questionCount: 4,
              problemMix: 'mixed',
              subtopics: ['conversion'],
              skills: ['conversion', 'notacion-cientifica'],
            },
            {
              title: 'Operaciones con notacion cientifica',
              difficulty: 6,
              questionCount: 5,
              problemMix: 'mixed',
              subtopics: ['operaciones'],
              skills: ['operaciones', 'exponentes', 'notacion-cientifica'],
            },
            {
              title: 'Aplicacion cientifica de notacion',
              difficulty: 6,
              questionCount: 5,
              problemMix: 'mixed',
              subtopics: ['aplicacion en ciencia'],
              skills: ['ciencia', 'modelacion', 'notacion-cientifica'],
            },
          ],
        }),
        buildTopic({
          id: 'proporcionalidad-compuesta',
          name: 'Proporcionalidad Compuesta',
          subtopics: ['Regla de tres compuesta', 'Velocidad-tiempo-distancia', 'Escalas'],
          difficultyRange: [7, 8],
          problemMix: 'mixed',
          questionCountRange: [5, 5],
          lessons: [
            {
              title: 'Regla de tres compuesta',
              difficulty: 7,
              questionCount: 5,
              problemMix: 'mixed',
              subtopics: ['regla de tres compuesta'],
              skills: ['proporcionalidad', 'regla-de-tres', 'analisis'],
            },
            {
              title: 'Velocidad, tiempo y distancia',
              difficulty: 7,
              questionCount: 5,
              problemMix: 'mixed',
              subtopics: ['velocidad-tiempo-distancia'],
              skills: ['movimiento', 'proporcionalidad', 'modelacion'],
            },
            {
              title: 'Escalas y proporcionalidad aplicada',
              difficulty: 8,
              questionCount: 5,
              problemMix: 'mixed',
              subtopics: ['escalas'],
              skills: ['escalas', 'conversion', 'modelacion'],
            },
          ],
        }),
        buildTopic({
          id: 'porcentajes-avanzados',
          name: 'Porcentajes Avanzados',
          subtopics: ['Aumentos sucesivos', 'Descuentos', 'Interes simple'],
          difficultyRange: [7, 8],
          problemMix: 'mixed',
          questionCountRange: [5, 5],
          lessons: [
            {
              title: 'Aumentos y descuentos sucesivos',
              difficulty: 7,
              questionCount: 5,
              problemMix: 'mixed',
              subtopics: ['aumentos sucesivos', 'descuentos'],
              skills: ['porcentajes', 'cambios-sucesivos', 'comercial'],
            },
            {
              title: 'Interes simple aplicado',
              difficulty: 8,
              questionCount: 5,
              problemMix: 'mixed',
              subtopics: ['interes simple'],
              skills: ['interes-simple', 'finanzas', 'modelacion'],
            },
          ],
        }),
      ],
    },
    {
      id: 'algebra',
      name: 'II. Algebra',
      topics: [
        buildTopic({
          id: 'polinomios',
          name: 'Polinomios',
          subtopics: ['Suma y resta', 'Multiplicacion', 'Valor numerico'],
          difficultyRange: [5, 6],
          problemMix: 'mixed',
          questionCountRange: [4, 5],
          lessons: [
            {
              title: 'Suma y resta de polinomios',
              difficulty: 5,
              questionCount: 4,
              problemMix: 'mixed',
              subtopics: ['suma y resta'],
              skills: ['polinomios', 'terminos-semejantes'],
            },
            {
              title: 'Multiplicacion de polinomios',
              difficulty: 5,
              questionCount: 4,
              problemMix: 'mixed',
              subtopics: ['multiplicacion'],
              skills: ['polinomios', 'multiplicacion'],
            },
            {
              title: 'Valor numerico de polinomios',
              difficulty: 6,
              questionCount: 5,
              problemMix: 'mixed',
              subtopics: ['valor numerico'],
              skills: ['evaluacion', 'sustitucion', 'polinomios'],
            },
          ],
        }),
        buildTopic({
          id: 'productos-notables',
          name: 'Productos Notables',
          subtopics: ['(a + b)^2', '(a - b)^2', '(a + b)(a - b)'],
          difficultyRange: [6, 6],
          problemMix: 'mixed',
          questionCountRange: [4, 5],
          lessons: [
            {
              title: 'Cuadrado de una suma y de una diferencia',
              difficulty: 6,
              questionCount: 4,
              problemMix: 'mixed',
              subtopics: ['(a + b)^2', '(a - b)^2'],
              skills: ['productos-notables', 'cuadrados'],
            },
            {
              title: 'Suma por diferencia',
              difficulty: 6,
              questionCount: 4,
              problemMix: 'mixed',
              subtopics: ['(a + b)(a - b)'],
              skills: ['productos-notables', 'diferencia-de-cuadrados'],
            },
            {
              title: 'Aplicacion de productos notables',
              difficulty: 6,
              questionCount: 5,
              problemMix: 'mixed',
              subtopics: ['aplicacion'],
              skills: ['productos-notables', 'modelacion'],
            },
          ],
        }),
        buildTopic({
          id: 'factorizacion-basica',
          name: 'Factorizacion Basica',
          subtopics: ['Factor comun', 'Diferencia de cuadrados', 'Trinomio simple'],
          difficultyRange: [7, 8],
          problemMix: 'mixed',
          questionCountRange: [5, 5],
          lessons: [
            {
              title: 'Factor comun',
              difficulty: 7,
              questionCount: 5,
              problemMix: 'mixed',
              subtopics: ['factor comun'],
              skills: ['factorizacion', 'factor-comun'],
            },
            {
              title: 'Diferencia de cuadrados',
              difficulty: 7,
              questionCount: 5,
              problemMix: 'mixed',
              subtopics: ['diferencia de cuadrados'],
              skills: ['factorizacion', 'diferencia-de-cuadrados'],
            },
            {
              title: 'Trinomio simple aplicado',
              difficulty: 8,
              questionCount: 5,
              problemMix: 'mixed',
              subtopics: ['trinomio simple'],
              skills: ['factorizacion', 'trinomio', 'modelacion'],
            },
          ],
        }),
        buildTopic({
          id: 'ecuaciones-lineales-dos-pasos',
          name: 'Ecuaciones Lineales con Dos Pasos',
          subtopics: ['Despeje con dos operaciones', 'Modelacion con contexto'],
          difficultyRange: [6, 6],
          problemMix: 'mixed',
          questionCountRange: [4, 5],
          lessons: [
            {
              title: 'Ecuaciones lineales de dos pasos',
              difficulty: 6,
              questionCount: 4,
              problemMix: 'mixed',
              subtopics: ['despeje con dos operaciones'],
              skills: ['ecuaciones', 'despeje'],
            },
            {
              title: 'Ecuaciones lineales en contexto',
              difficulty: 6,
              questionCount: 5,
              problemMix: 'mixed',
              subtopics: ['modelacion con contexto'],
              skills: ['ecuaciones', 'contexto', 'modelacion'],
            },
          ],
        }),
        buildTopic({
          id: 'sistemas-ecuaciones',
          name: 'Sistemas de Ecuaciones',
          subtopics: ['Metodo grafico', 'Metodo de sustitucion', 'Modelacion con contexto'],
          difficultyRange: [7, 8],
          problemMix: 'mixed',
          questionCountRange: [5, 5],
          lessons: [
            {
              title: 'Interpretacion geometrica del sistema',
              difficulty: 7,
              questionCount: 5,
              problemMix: 'mixed',
              subtopics: ['metodo grafico'],
              skills: ['sistemas', 'grafico', 'interpretacion'],
            },
            {
              title: 'Sistemas por sustitucion',
              difficulty: 7,
              questionCount: 5,
              problemMix: 'mixed',
              subtopics: ['metodo de sustitucion'],
              skills: ['sistemas', 'sustitucion'],
            },
            {
              title: 'Sistemas con modelacion contextual',
              difficulty: 8,
              questionCount: 5,
              problemMix: 'mixed',
              subtopics: ['modelacion con contexto'],
              skills: ['sistemas', 'modelacion', 'contexto'],
            },
          ],
        }),
      ],
    },
    {
      id: 'geometria',
      name: 'III. Geometria',
      topics: [
        buildTopic({
          id: 'teorema-de-pitagoras',
          name: 'Teorema de Pitagoras',
          subtopics: ['Aplicacion directa', 'Problemas contextualizados'],
          difficultyRange: [6, 6],
          problemMix: 'mixed',
          questionCountRange: [4, 5],
          lessons: [
            {
              title: 'Aplicacion directa del teorema de Pitagoras',
              difficulty: 6,
              questionCount: 4,
              problemMix: 'mixed',
              subtopics: ['aplicacion directa'],
              skills: ['pitagoras', 'triangulos-rectangulos'],
            },
            {
              title: 'Pitagoras en contexto',
              difficulty: 6,
              questionCount: 5,
              problemMix: 'mixed',
              subtopics: ['problemas contextualizados'],
              skills: ['pitagoras', 'contexto', 'modelacion'],
            },
          ],
        }),
        buildTopic({
          id: 'areas-compuestas',
          name: 'Areas Compuestas',
          subtopics: ['Figuras combinadas', 'Problemas reales (terrenos y planos)'],
          difficultyRange: [7, 8],
          problemMix: 'mixed',
          questionCountRange: [5, 5],
          lessons: [
            {
              title: 'Areas de figuras combinadas',
              difficulty: 7,
              questionCount: 5,
              problemMix: 'mixed',
              subtopics: ['figuras combinadas'],
              skills: ['areas', 'composicion'],
            },
            {
              title: 'Areas compuestas en terrenos y planos',
              difficulty: 8,
              questionCount: 5,
              problemMix: 'mixed',
              subtopics: ['problemas reales'],
              skills: ['areas', 'terrenos', 'modelacion'],
            },
          ],
        }),
        buildTopic({
          id: 'semejanza-de-triangulos',
          name: 'Semejanza de Triangulos',
          subtopics: ['Razon de semejanza', 'Aplicacion con medidas faltantes'],
          difficultyRange: [7, 8],
          problemMix: 'mixed',
          questionCountRange: [5, 5],
          lessons: [
            {
              title: 'Razon y criterios de semejanza',
              difficulty: 7,
              questionCount: 5,
              problemMix: 'mixed',
              subtopics: ['razon de semejanza'],
              skills: ['semejanza', 'proporciones'],
            },
            {
              title: 'Semejanza aplicada',
              difficulty: 8,
              questionCount: 5,
              problemMix: 'mixed',
              subtopics: ['aplicacion con medidas faltantes'],
              skills: ['semejanza', 'modelacion', 'medidas'],
            },
          ],
        }),
      ],
    },
    {
      id: 'estadistica-probabilidad',
      name: 'IV. Estadistica y Probabilidad',
      topics: [
        buildTopic({
          id: 'media-mediana-moda-rango',
          name: 'Media, Mediana, Moda y Rango',
          subtopics: ['Media', 'Mediana', 'Moda', 'Rango'],
          difficultyRange: [5, 6],
          problemMix: 'mixed',
          questionCountRange: [4, 5],
          lessons: [
            {
              title: 'Media y mediana',
              difficulty: 5,
              questionCount: 4,
              problemMix: 'mixed',
              subtopics: ['media', 'mediana'],
              skills: ['estadistica', 'tendencia-central'],
            },
            {
              title: 'Moda y rango aplicados',
              difficulty: 6,
              questionCount: 5,
              problemMix: 'mixed',
              subtopics: ['moda', 'rango'],
              skills: ['estadistica', 'dispersion', 'analisis'],
            },
          ],
        }),
        buildTopic({
          id: 'probabilidad-compuesta-basica',
          name: 'Probabilidad Compuesta Basica',
          subtopics: ['Eventos independientes', 'Arbol de probabilidad'],
          difficultyRange: [7, 8],
          problemMix: 'mixed',
          questionCountRange: [5, 5],
          lessons: [
            {
              title: 'Eventos independientes',
              difficulty: 7,
              questionCount: 5,
              problemMix: 'mixed',
              subtopics: ['eventos independientes'],
              skills: ['probabilidad', 'independencia'],
            },
            {
              title: 'Arbol de probabilidad aplicado',
              difficulty: 8,
              questionCount: 5,
              problemMix: 'mixed',
              subtopics: ['arbol de probabilidad'],
              skills: ['probabilidad', 'arbol', 'modelacion'],
            },
          ],
        }),
      ],
    },
    {
      id: 'introduccion-funciones',
      name: 'V. Introduccion a Funciones',
      topics: [
        buildTopic({
          id: 'funcion-lineal-basica',
          name: 'Funcion Lineal Basica',
          subtopics: ['y = mx + b', 'Interpretacion grafica', 'Pendiente', 'Modelacion economica simple'],
          difficultyRange: [7, 8],
          problemMix: 'mixed',
          questionCountRange: [5, 5],
          lessons: [
            {
              title: 'Forma y = mx + b y pendiente',
              difficulty: 7,
              questionCount: 5,
              problemMix: 'mixed',
              subtopics: ['y = mx + b', 'pendiente'],
              skills: ['funcion-lineal', 'pendiente'],
            },
            {
              title: 'Interpretacion grafica de funcion lineal',
              difficulty: 7,
              questionCount: 5,
              problemMix: 'mixed',
              subtopics: ['interpretacion grafica'],
              skills: ['funcion-lineal', 'grafica', 'analisis'],
            },
            {
              title: 'Modelacion economica con funcion lineal',
              difficulty: 8,
              questionCount: 5,
              problemMix: 'mixed',
              subtopics: ['modelacion economica simple'],
              skills: ['funcion-lineal', 'modelacion', 'economia'],
            },
          ],
        }),
      ],
    },
    {
      id: 'funciones-modelacion-cuadratica-profunda',
      name: 'II Bimestre - Funciones y Modelacion Cuadratica Profunda',
      topics: [
        buildTopic({
          id: 'funcion-cuadratica-analisis-estructural-completo',
          name: 'Unidad 1 - Funcion Cuadratica y Analisis Estructural Completo',
          subtopics: [
            'Analisis algebraico',
            'Representacion grafica rigurosa',
            'Vertice y eje de simetria',
            'Forma factorizada y forma canonica',
            'Interpretacion contextual avanzada',
          ],
          difficultyRange: [9, 10],
          problemMix: 'mixed',
          questionCountRange: [5, 6],
          lessons: [
            {
              title: 'Concepto formal de funcion cuadratica',
              difficulty: 9,
              questionCount: 5,
              subtopics: ['forma general ax^2 + bx + c', 'coeficiente principal', 'comparacion con lineal'],
              skills: ['funcion-cuadratica', 'forma-general', 'clasificacion'],
            },
            {
              title: 'Concavidad y coeficiente principal',
              difficulty: 9,
              questionCount: 5,
              subtopics: ['concavidad positiva y negativa', 'apertura', 'interpretacion grafica'],
              skills: ['concavidad', 'coeficiente-principal', 'analisis-grafico'],
            },
            {
              title: 'Intersecciones con el eje x',
              difficulty: 9,
              questionCount: 5,
              subtopics: ['f(x)=0', 'factorizacion', 'numero de soluciones reales'],
              skills: ['raices-cuadraticas', 'intersecciones-x', 'factorizacion'],
            },
            {
              title: 'Vertice mediante factorizacion',
              difficulty: 10,
              questionCount: 6,
              subtopics: ['promedio de raices', 'eje de simetria', 'vertice'],
              skills: ['vertice', 'eje-simetria', 'factorizacion'],
            },
            {
              title: 'Forma canonica (completando cuadrados)',
              difficulty: 10,
              questionCount: 6,
              subtopics: ['transformacion a (x-h)^2 + k', 'interpretacion del vertice'],
              skills: ['forma-canonica', 'completar-cuadrados', 'vertice'],
            },
            {
              title: 'Representacion grafica estructurada',
              difficulty: 10,
              questionCount: 6,
              subtopics: ['vertice', 'raices', 'intercepto en y', 'tabla de valores'],
              skills: ['grafica-parabola', 'representacion', 'analisis-estructural'],
            },
            {
              title: 'Maximos y minimos',
              difficulty: 10,
              questionCount: 6,
              subtopics: ['punto extremo', 'concavidad', 'analisis contextual'],
              skills: ['maximos-minimos', 'vertice', 'interpretacion'],
            },
            {
              title: 'Intervalos de crecimiento y decrecimiento',
              difficulty: 10,
              questionCount: 6,
              subtopics: ['comportamiento alrededor del vertice', 'analisis cualitativo'],
              skills: ['crecimiento', 'decrecimiento', 'analisis-funcional'],
            },
            {
              title: 'Comparacion de funciones cuadraticas',
              difficulty: 10,
              questionCount: 6,
              subtopics: ['traslaciones', 'escala vertical', 'efecto de coeficientes'],
              skills: ['comparacion-funciones', 'transformaciones', 'coeficientes'],
            },
            {
              title: 'Modelacion cuadratica aplicada I',
              difficulty: 10,
              questionCount: 6,
              problemMix: 'contextualized',
              subtopics: ['problemas de area', 'trayectorias verticales'],
              skills: ['modelacion-cuadratica', 'aplicaciones', 'interpretacion-fisica'],
            },
            {
              title: 'Modelacion cuadratica aplicada II',
              difficulty: 10,
              questionCount: 6,
              problemMix: 'contextualized',
              subtopics: ['optimizacion con restriccion', 'coherencia del modelo'],
              skills: ['optimizacion-cuadratica', 'modelacion', 'coherencia'],
            },
            {
              title: 'Integracion estructural avanzada',
              difficulty: 10,
              questionCount: 6,
              subtopics: ['formas general/factorizada/canonica', 'analisis grafico y modelacion'],
              skills: ['integracion-cuadratica', 'dominio-estructural', 'argumentacion'],
            },
          ],
        }),
        buildTopic({
          id: 'transformaciones-y-composicion-de-funciones',
          name: 'Unidad 2 - Transformaciones y Composicion de Funciones',
          subtopics: [
            'Traslaciones verticales y horizontales',
            'Reflexiones',
            'Escalamientos',
            'Composicion de funciones',
            'Analisis estructural comparativo',
          ],
          difficultyRange: [9, 10],
          problemMix: 'mixed',
          questionCountRange: [5, 6],
          lessons: [
            {
              title: 'Traslaciones verticales',
              difficulty: 9,
              questionCount: 5,
              subtopics: ['f(x)+k', 'desplazamiento vertical', 'impacto en vertice'],
              skills: ['traslacion-vertical', 'transformaciones'],
            },
            {
              title: 'Traslaciones horizontales',
              difficulty: 9,
              questionCount: 5,
              subtopics: ['f(x-h)', 'desplazamiento lateral'],
              skills: ['traslacion-horizontal', 'transformaciones'],
            },
            {
              title: 'Reflexiones respecto al eje x',
              difficulty: 9,
              questionCount: 5,
              subtopics: ['multiplicacion por -1', 'cambio de concavidad'],
              skills: ['reflexion', 'concavidad'],
            },
            {
              title: 'Escalamiento vertical',
              difficulty: 9,
              questionCount: 5,
              subtopics: ['coeficiente multiplicador', 'apertura de parabola'],
              skills: ['escalamiento-vertical', 'coeficiente-principal'],
            },
            {
              title: 'Transformaciones combinadas',
              difficulty: 10,
              questionCount: 6,
              subtopics: ['traslacion y reflexion', 'orden de aplicacion'],
              skills: ['transformaciones-combinadas', 'coherencia-algebraica'],
            },
            {
              title: 'Comparacion de funciones transformadas',
              difficulty: 10,
              questionCount: 6,
              subtopics: ['analisis simultaneo de parabolas', 'relacion algebra-grafica'],
              skills: ['comparacion-grafica', 'analisis-estructural'],
            },
            {
              title: 'Introduccion a composicion de funciones',
              difficulty: 10,
              questionCount: 6,
              subtopics: ['f(g(x))', 'sustitucion estructural'],
              skills: ['composicion-funciones', 'sustitucion'],
            },
            {
              title: 'Composicion cuadratica-lineal',
              difficulty: 10,
              questionCount: 6,
              subtopics: ['composicion lineal-cuadratica', 'expansion estructural'],
              skills: ['composicion-mixta', 'expansion'],
            },
            {
              title: 'Dominio en funciones transformadas',
              difficulty: 10,
              questionCount: 6,
              subtopics: ['restricciones algebraicas', 'dominio natural'],
              skills: ['dominio-funcional', 'restricciones'],
            },
            {
              title: 'Modelacion con transformaciones',
              difficulty: 10,
              questionCount: 6,
              problemMix: 'contextualized',
              subtopics: ['desplazamientos fisicos', 'comparacion de escenarios'],
              skills: ['modelacion-transformaciones', 'interpretacion'],
            },
            {
              title: 'Analisis estructural comparativo profundo',
              difficulty: 10,
              questionCount: 6,
              subtopics: ['forma general vs transformada', 'relacion coeficientes-grafico'],
              skills: ['analisis-comparativo', 'representaciones'],
            },
            {
              title: 'Integracion funcional avanzada',
              difficulty: 10,
              questionCount: 6,
              subtopics: ['transformaciones', 'composicion', 'dominio', 'interpretacion grafica'],
              skills: ['integracion-funcional', 'dominio-completo'],
            },
          ],
        }),
        buildTopic({
          id: 'sistemas-no-lineales-y-analisis-grafico-avanzado',
          name: 'Unidad 3 - Sistemas No Lineales y Analisis Grafico Avanzado',
          subtopics: [
            'Sistema lineal-cuadratico',
            'Interseccion recta-parabola',
            'Numero de soluciones',
            'Analisis de parametros',
            'Modelacion con funciones multiples',
          ],
          difficultyRange: [9, 10],
          problemMix: 'mixed',
          questionCountRange: [5, 6],
          lessons: [
            {
              title: 'Repaso de sistemas lineales estructurales',
              difficulty: 9,
              questionCount: 5,
              subtopics: ['interseccion de rectas', 'sustitucion', 'analisis grafico basico'],
              skills: ['sistemas-lineales', 'sustitucion', 'interpretacion-grafica'],
            },
            {
              title: 'Introduccion a sistemas no lineales',
              difficulty: 9,
              questionCount: 5,
              subtopics: ['lineal-cuadratico', 'reduccion a ecuacion cuadratica'],
              skills: ['sistemas-no-lineales', 'reduccion'],
            },
            {
              title: 'Interpretacion geometrica recta-parabola',
              difficulty: 9,
              questionCount: 5,
              subtopics: ['numero de intersecciones', 'soluciones reales'],
              skills: ['intersecciones', 'interpretacion-geometrica'],
            },
            {
              title: 'Casos: dos, una o ninguna solucion',
              difficulty: 10,
              questionCount: 6,
              subtopics: ['discriminante', 'tangencia', 'condiciones de solucion'],
              skills: ['discriminante', 'numero-soluciones', 'analisis'],
            },
            {
              title: 'Sistemas cuadratico-cuadratico basicos',
              difficulty: 10,
              questionCount: 6,
              subtopics: ['sustitucion entre parabolas', 'reduccion estructural'],
              skills: ['sistema-cuadratico', 'sustitucion', 'coherencia'],
            },
            {
              title: 'Analisis grafico comparativo multiple',
              difficulty: 10,
              questionCount: 6,
              subtopics: ['comparacion simultanea de funciones', 'regiones relevantes'],
              skills: ['analisis-grafico-multiple', 'comparacion'],
            },
            {
              title: 'Modelacion con interseccion de funciones',
              difficulty: 10,
              questionCount: 6,
              problemMix: 'contextualized',
              subtopics: ['punto de equilibrio', 'cruce de trayectorias'],
              skills: ['modelacion-interseccion', 'equilibrio'],
            },
            {
              title: 'Restricciones combinadas lineal-cuadratica',
              difficulty: 10,
              questionCount: 6,
              subtopics: ['sistemas con inecuaciones', 'region solucion'],
              skills: ['restricciones-combinadas', 'region-solucion'],
            },
            {
              title: 'Optimizacion con intersecciones',
              difficulty: 10,
              questionCount: 6,
              subtopics: ['puntos criticos', 'comparacion de escenarios'],
              skills: ['optimizacion', 'intersecciones'],
            },
            {
              title: 'Parametros en sistemas no lineales',
              difficulty: 10,
              questionCount: 6,
              subtopics: ['existencia de soluciones', 'analisis por parametro'],
              skills: ['parametros', 'condiciones-solucion'],
            },
            {
              title: 'Modelacion avanzada multietapa',
              difficulty: 10,
              questionCount: 6,
              problemMix: 'contextualized',
              subtopics: ['combinacion de funciones', 'restricciones multiples'],
              skills: ['modelacion-multietapa', 'funciones-multiples'],
            },
            {
              title: 'Integracion no lineal avanzada',
              difficulty: 10,
              questionCount: 6,
              subtopics: ['sistemas mixtos', 'analisis grafico', 'optimizacion', 'modelacion compleja'],
              skills: ['integracion-no-lineal', 'dominio-elite'],
            },
          ],
        }),
        buildTopic({
          id: 'modelacion-cuadratica-aplicada-y-pensamiento-estrategico',
          name: 'Unidad 4 - Modelacion Cuadratica Aplicada y Pensamiento Estrategico',
          subtopics: [
            'Interpretacion de parametros',
            'Trayectorias y contextos reales',
            'Maximos y minimos aplicados',
            'Optimizacion',
            'Argumentacion matematica formal',
          ],
          difficultyRange: [9, 10],
          problemMix: 'mixed',
          questionCountRange: [5, 6],
          lessons: [
            {
              title: 'Interpretacion contextual de la forma general',
              difficulty: 9,
              questionCount: 5,
              subtopics: ['significado de coeficientes', 'concavidad', 'crecimiento y decrecimiento'],
              skills: ['interpretacion-parametros', 'forma-general'],
            },
            {
              title: 'Modelacion de trayectorias',
              difficulty: 9,
              questionCount: 5,
              problemMix: 'contextualized',
              subtopics: ['movimiento parabolico', 'altura maxima', 'tiempo de impacto'],
              skills: ['trayectorias', 'modelacion-fisica'],
            },
            {
              title: 'Forma vertice en contexto aplicado',
              difficulty: 9,
              questionCount: 5,
              subtopics: ['uso estrategico de forma canonica', 'maximo o minimo directo'],
              skills: ['forma-vertice', 'aplicacion'],
            },
            {
              title: 'Problemas de optimizacion basica',
              difficulty: 10,
              questionCount: 6,
              subtopics: ['maximos y minimos', 'evaluacion del vertice'],
              skills: ['optimizacion-basica', 'vertice'],
            },
            {
              title: 'Comparacion de modelos cuadraticos',
              difficulty: 10,
              questionCount: 6,
              problemMix: 'contextualized',
              subtopics: ['dos funciones en mismo contexto', 'toma de decisiones'],
              skills: ['comparacion-modelos', 'decision'],
            },
            {
              title: 'Modelacion con restricciones reales',
              difficulty: 10,
              questionCount: 6,
              problemMix: 'contextualized',
              subtopics: ['dominio contextual', 'limitaciones fisicas', 'validez matematica'],
              skills: ['restricciones-reales', 'validez-modelo'],
            },
            {
              title: 'Analisis estrategico multietapa',
              difficulty: 10,
              questionCount: 6,
              subtopics: ['descomposicion del problema', 'modelado por etapas'],
              skills: ['analisis-multietapa', 'estrategia'],
            },
            {
              title: 'Optimizacion con condiciones adicionales',
              difficulty: 10,
              questionCount: 6,
              subtopics: ['restricciones extra', 'comparacion de escenarios'],
              skills: ['optimizacion-restringida', 'justificacion'],
            },
            {
              title: 'Parametros en modelos aplicados',
              difficulty: 10,
              questionCount: 6,
              subtopics: ['variacion de coeficientes', 'analisis condicional'],
              skills: ['parametros-modelo', 'sensibilidad'],
            },
            {
              title: 'Modelacion inversa',
              difficulty: 10,
              questionCount: 6,
              subtopics: ['construccion de funcion desde datos', 'validacion del modelo'],
              skills: ['modelacion-inversa', 'ajuste-funcional'],
            },
            {
              title: 'Integracion funcional completa',
              difficulty: 10,
              questionCount: 6,
              subtopics: ['transformaciones', 'sistemas', 'optimizacion', 'interpretacion grafica'],
              skills: ['integracion-funcional', 'resolucion-estructurada'],
            },
            {
              title: 'Modelacion estrategica avanzada',
              difficulty: 10,
              questionCount: 6,
              problemMix: 'contextualized',
              subtopics: ['problemas abiertos', 'comparacion de soluciones', 'argumentacion formal'],
              skills: ['modelacion-estrategica', 'argumentacion', 'nivel-elite'],
            },
          ],
        }),
      ],
    },
    {
      id: 'algebra-iii-bimestre-potencias-radicales',
      name: 'III Bimestre - Potenciacion, Radicales y Estructura Algebraica',
      topics: [
        buildTopic({
          id: 'potencias-y-leyes-de-los-exponentes',
          name: 'Unidad 1 - Potencias y Leyes de los Exponentes',
          subtopics: [
            'Propiedades de los exponentes',
            'Potencias con base entera y racional',
            'Exponentes negativos',
            'Notacion cientifica',
            'Simplificacion estructurada',
          ],
          difficultyRange: [8, 10],
          problemMix: 'mixed',
          questionCountRange: [5, 6],
          lessons: [
            {
              title: 'Potencias como multiplicacion repetida',
              difficulty: 8,
              questionCount: 5,
              subtopics: ['base y exponente', 'interpretacion numerica', 'crecimiento exponencial simple'],
              skills: ['potencias', 'base-exponente', 'interpretacion'],
            },
            {
              title: 'Producto de potencias de igual base',
              difficulty: 8,
              questionCount: 5,
              subtopics: ['suma de exponentes', 'justificacion algebraica'],
              skills: ['ley-producto-potencias', 'exponentes'],
            },
            {
              title: 'Cociente de potencias de igual base',
              difficulty: 8,
              questionCount: 5,
              subtopics: ['resta de exponentes', 'interpretacion estructural'],
              skills: ['ley-cociente-potencias', 'exponentes'],
            },
            {
              title: 'Potencia de una potencia',
              difficulty: 9,
              questionCount: 5,
              subtopics: ['multiplicacion de exponentes', 'analisis estructural'],
              skills: ['potencia-de-potencia', 'simplificacion'],
            },
            {
              title: 'Potencia de un producto',
              difficulty: 9,
              questionCount: 5,
              subtopics: ['distribucion del exponente', 'factorizacion estructural'],
              skills: ['potencia-de-producto', 'distributividad'],
            },
            {
              title: 'Potencia de un cociente',
              difficulty: 9,
              questionCount: 5,
              subtopics: ['distribucion en fracciones', 'simplificacion estructural'],
              skills: ['potencia-de-cociente', 'fracciones-algebraicas'],
            },
            {
              title: 'Exponente cero',
              difficulty: 9,
              questionCount: 5,
              subtopics: ['justificacion algebraica', 'base distinta de cero'],
              skills: ['exponente-cero', 'propiedades-exponentes'],
            },
            {
              title: 'Exponentes negativos',
              difficulty: 9,
              questionCount: 5,
              subtopics: ['inverso multiplicativo', 'relacion con fracciones'],
              skills: ['exponentes-negativos', 'inverso'],
            },
            {
              title: 'Simplificacion algebraica avanzada',
              difficulty: 10,
              questionCount: 6,
              subtopics: ['combinacion de leyes', 'orden estructural', 'reduccion completa'],
              skills: ['simplificacion-exponentes', 'integracion-leyes'],
            },
            {
              title: 'Notacion cientifica',
              difficulty: 10,
              questionCount: 6,
              subtopics: ['potencias de 10', 'conversion bidireccional'],
              skills: ['notacion-cientifica', 'conversion'],
            },
            {
              title: 'Operaciones con notacion cientifica',
              difficulty: 10,
              questionCount: 6,
              subtopics: ['multiplicacion', 'division', 'ajuste de coeficientes'],
              skills: ['operaciones-notacion-cientifica', 'potencias-10'],
            },
            {
              title: 'Integracion estructural de exponentes',
              difficulty: 10,
              questionCount: 6,
              subtopics: ['leyes combinadas', 'fracciones algebraicas', 'notacion cientifica'],
              skills: ['integracion-exponentes', 'razonamiento-formal', 'nivel-elite'],
            },
          ],
        }),
        buildTopic({
          id: 'radicales-y-racionalizacion',
          name: 'Unidad 2 - Radicales y Racionalizacion',
          subtopics: [
            'Raices cuadradas y cubicas',
            'Propiedades de radicales',
            'Simplificacion avanzada',
            'Racionalizacion del denominador',
            'Exponentes racionales',
          ],
          difficultyRange: [9, 10],
          problemMix: 'mixed',
          questionCountRange: [5, 6],
          lessons: [
            {
              title: 'Raiz cuadrada como operacion inversa',
              difficulty: 9,
              questionCount: 5,
              subtopics: ['relacion potencia-raiz', 'condiciones de existencia'],
              skills: ['raiz-cuadrada', 'operacion-inversa'],
            },
            {
              title: 'Raiz cubica y raices de indice mayor',
              difficulty: 9,
              questionCount: 5,
              subtopics: ['indice del radical', 'comparacion de raices'],
              skills: ['raices', 'indice-radical'],
            },
            {
              title: 'Simplificacion basica de radicales',
              difficulty: 9,
              questionCount: 5,
              subtopics: ['extraccion de factores perfectos', 'factores primos'],
              skills: ['simplificacion-radicales', 'factorizacion'],
            },
            {
              title: 'Producto de radicales',
              difficulty: 9,
              questionCount: 5,
              subtopics: ['propiedad del producto', 'simplificacion posterior'],
              skills: ['producto-radicales', 'propiedades-radicales'],
            },
            {
              title: 'Cociente de radicales',
              difficulty: 9,
              questionCount: 5,
              subtopics: ['propiedad del cociente', 'simplificacion estructural'],
              skills: ['cociente-radicales', 'propiedades-radicales'],
            },
            {
              title: 'Suma y resta de radicales semejantes',
              difficulty: 9,
              questionCount: 5,
              subtopics: ['identificacion de radicales equivalentes', 'reduccion'],
              skills: ['suma-resta-radicales', 'radicales-semejantes'],
            },
            {
              title: 'Radicales no semejantes',
              difficulty: 10,
              questionCount: 6,
              subtopics: ['analisis estructural', 'simplificacion previa'],
              skills: ['radicales-no-semejantes', 'analisis'],
            },
            {
              title: 'Racionalizacion con denominador monomial',
              difficulty: 10,
              questionCount: 6,
              subtopics: ['eliminacion de radical simple', 'factor racionalizante'],
              skills: ['racionalizacion-monomial', 'denominadores'],
            },
            {
              title: 'Racionalizacion con binomio conjugado',
              difficulty: 10,
              questionCount: 6,
              subtopics: ['uso del conjugado', 'producto notable'],
              skills: ['racionalizacion-conjugado', 'diferencia-cuadrados'],
            },
            {
              title: 'Exponentes racionales',
              difficulty: 10,
              questionCount: 6,
              subtopics: ['relacion radical-exponente fraccionario', 'conversion bidireccional'],
              skills: ['exponentes-racionales', 'conversion'],
            },
            {
              title: 'Expresiones mixtas con potencias y radicales',
              difficulty: 10,
              questionCount: 6,
              subtopics: ['combinacion de leyes', 'racionalizacion', 'simplificacion profunda'],
              skills: ['potencias-radicales-mixtas', 'integracion'],
            },
            {
              title: 'Integracion estructural avanzada',
              difficulty: 10,
              questionCount: 6,
              subtopics: ['simplificacion completa', 'racionalizacion avanzada', 'justificacion formal'],
              skills: ['integracion-radicales', 'nivel-elite'],
            },
          ],
        }),
        buildTopic({
          id: 'polinomios-y-factorizacion-avanzada',
          name: 'Unidad 3 - Polinomios y Factorizacion Avanzada',
          subtopics: [
            'Operaciones con polinomios',
            'Productos notables',
            'Factorizacion estrategica',
            'Identidades algebraicas',
            'Analisis estructural',
          ],
          difficultyRange: [9, 10],
          problemMix: 'mixed',
          questionCountRange: [5, 6],
          lessons: [
            {
              title: 'Clasificacion y grado de polinomios',
              difficulty: 9,
              questionCount: 5,
              subtopics: ['monomio, binomio, trinomio', 'grado absoluto y relativo'],
              skills: ['clasificacion-polinomios', 'grado'],
            },
            {
              title: 'Suma y resta de polinomios',
              difficulty: 9,
              questionCount: 5,
              subtopics: ['terminos semejantes', 'orden estructural'],
              skills: ['suma-resta-polinomios', 'terminos-semejantes'],
            },
            {
              title: 'Multiplicacion de monomio por polinomio',
              difficulty: 9,
              questionCount: 5,
              subtopics: ['distributividad', 'organizacion estructural'],
              skills: ['distributividad', 'producto-monomio-polinomio'],
            },
            {
              title: 'Multiplicacion de polinomios',
              difficulty: 9,
              questionCount: 5,
              subtopics: ['binomio por binomio', 'reduccion final'],
              skills: ['multiplicacion-polinomios', 'tecnica-estructurada'],
            },
            {
              title: 'Productos notables I',
              difficulty: 10,
              questionCount: 6,
              subtopics: ['cuadrado de binomio', 'identificacion estructural'],
              skills: ['productos-notables', 'cuadrado-binomio'],
            },
            {
              title: 'Productos notables II',
              difficulty: 10,
              questionCount: 6,
              subtopics: ['diferencia de cuadrados', 'trinomio cuadrado perfecto'],
              skills: ['productos-notables', 'patrones-algebraicos'],
            },
            {
              title: 'Factor comun',
              difficulty: 10,
              questionCount: 6,
              subtopics: ['extraccion estrategica', 'simplificacion estructural'],
              skills: ['factor-comun', 'factorizacion'],
            },
            {
              title: 'Factorizacion por agrupacion',
              difficulty: 10,
              questionCount: 6,
              subtopics: ['reorganizacion de terminos', 'factor comun doble'],
              skills: ['agrupacion', 'factorizacion'],
            },
            {
              title: 'Trinomio cuadratico simple',
              difficulty: 10,
              questionCount: 6,
              subtopics: ['x^2 + bx + c', 'descomposicion numerica'],
              skills: ['trinomio-simple', 'factorizacion'],
            },
            {
              title: 'Trinomio general ax^2 + bx + c',
              difficulty: 10,
              questionCount: 6,
              subtopics: ['metodo estructurado', 'descomposicion estrategica'],
              skills: ['trinomio-general', 'factorizacion-avanzada'],
            },
            {
              title: 'Identidades y verificacion estructural',
              difficulty: 10,
              questionCount: 6,
              subtopics: ['comprobacion por multiplicacion', 'patrones ocultos'],
              skills: ['verificacion-factorizacion', 'identidades'],
            },
            {
              title: 'Integracion algebraica avanzada',
              difficulty: 10,
              questionCount: 6,
              subtopics: ['operaciones', 'productos notables', 'factorizacion multiple'],
              skills: ['integracion-polinomios', 'nivel-elite'],
            },
          ],
        }),
        buildTopic({
          id: 'expresiones-algebraicas-racionales',
          name: 'Unidad 4 - Expresiones Algebraicas Racionales',
          subtopics: [
            'Factorizacion avanzada',
            'Restricciones del dominio',
            'Operaciones con fracciones algebraicas',
            'Ecuaciones racionales',
            'Analisis estructural',
          ],
          difficultyRange: [9, 10],
          problemMix: 'mixed',
          questionCountRange: [5, 6],
          lessons: [
            {
              title: 'Concepto de expresion racional',
              difficulty: 9,
              questionCount: 5,
              subtopics: ['fraccion algebraica', 'condiciones de existencia'],
              skills: ['expresion-racional', 'dominio'],
            },
            {
              title: 'Restricciones del dominio',
              difficulty: 9,
              questionCount: 5,
              subtopics: ['denominador distinto de cero', 'analisis previo'],
              skills: ['restricciones-dominio', 'analisis'],
            },
            {
              title: 'Simplificacion por factor comun',
              difficulty: 9,
              questionCount: 5,
              subtopics: ['factorizacion del numerador', 'cancelacion estructural'],
              skills: ['simplificacion-racional', 'factor-comun'],
            },
            {
              title: 'Simplificacion con productos notables',
              difficulty: 9,
              questionCount: 5,
              subtopics: ['diferencia de cuadrados', 'trinomio factorizable'],
              skills: ['simplificacion-notables', 'expresiones-racionales'],
            },
            {
              title: 'Multiplicacion de expresiones racionales',
              difficulty: 10,
              questionCount: 6,
              subtopics: ['factorizacion previa', 'simplificacion cruzada'],
              skills: ['multiplicacion-racional', 'reduccion'],
            },
            {
              title: 'Division de expresiones racionales',
              difficulty: 10,
              questionCount: 6,
              subtopics: ['inverso multiplicativo', 'simplificacion completa'],
              skills: ['division-racional', 'inverso'],
            },
            {
              title: 'Suma y resta con igual denominador',
              difficulty: 10,
              questionCount: 6,
              subtopics: ['reduccion directa', 'factorizacion posterior'],
              skills: ['suma-resta-racional', 'denominador-comun'],
            },
            {
              title: 'Suma y resta con distinto denominador',
              difficulty: 10,
              questionCount: 6,
              subtopics: ['mcm algebraico', 'factorizacion estrategica'],
              skills: ['mcm-racional', 'suma-resta-racional'],
            },
            {
              title: 'Expresiones complejas (fracciones compuestas)',
              difficulty: 10,
              questionCount: 6,
              subtopics: ['multiplicacion por mcm', 'reduccion integral'],
              skills: ['fracciones-compuestas', 'simplificacion'],
            },
            {
              title: 'Ecuaciones racionales basicas',
              difficulty: 10,
              questionCount: 6,
              subtopics: ['eliminacion de denominadores', 'verificacion de soluciones'],
              skills: ['ecuaciones-racionales', 'verificacion'],
            },
            {
              title: 'Ecuaciones racionales avanzadas',
              difficulty: 10,
              questionCount: 6,
              subtopics: ['factorizacion multiple', 'soluciones extranas'],
              skills: ['ecuaciones-racionales-avanzadas', 'analisis-formal'],
            },
            {
              title: 'Integracion algebraica estructural',
              difficulty: 10,
              questionCount: 6,
              subtopics: ['factorizacion', 'radicales', 'exponentes', 'operaciones racionales'],
              skills: ['integracion-racional', 'dominio-iii-bimestre', 'nivel-elite'],
            },
          ],
        }),
      ],
    },
    {
      id: 'ecuaciones-inecuaciones-modelacion-algebraica-iv-bimestre',
      name: 'IV Bimestre - Ecuaciones, Inecuaciones y Modelacion Algebraica',
      topics: [
        buildTopic({
          id: 'ecuaciones-cuadraticas-metodos-resolucion',
          name: 'Unidad 1 - Ecuaciones Cuadraticas y Metodos de Resolucion',
          subtopics: [
            'Resolucion completa de ecuaciones cuadraticas',
            'Comparacion de metodos',
            'Analisis del discriminante',
            'Interpretacion grafica',
            'Validacion de soluciones',
          ],
          difficultyRange: [9, 10],
          problemMix: 'mixed',
          questionCountRange: [5, 6],
          lessons: [
            {
              title: 'Ecuacion cuadratica estandar',
              difficulty: 9,
              questionCount: 5,
              subtopics: ['forma general ax^2 + bx + c = 0', 'identificacion de coeficientes'],
              skills: ['ecuacion-cuadratica', 'forma-estandar', 'coeficientes'],
            },
            {
              title: 'Resolucion por factorizacion simple',
              difficulty: 9,
              questionCount: 5,
              problemMix: 'mechanical',
              subtopics: ['factorizacion directa', 'producto cero', 'verificacion'],
              skills: ['factorizacion-cuadratica', 'producto-cero', 'verificacion'],
            },
            {
              title: 'Trinomio general en ecuaciones',
              difficulty: 9,
              questionCount: 5,
              problemMix: 'mechanical',
              subtopics: ['factorizacion de ax^2 + bx + c', 'metodo estructurado'],
              skills: ['trinomio-general', 'factorizacion', 'ecuaciones-cuadraticas'],
            },
            {
              title: 'Metodo de completar el cuadrado',
              difficulty: 10,
              questionCount: 6,
              subtopics: ['transformacion a forma canonica', 'desarrollo estructurado'],
              skills: ['completar-cuadrado', 'forma-canonica', 'ecuaciones-cuadraticas'],
            },
            {
              title: 'Formula general',
              difficulty: 10,
              questionCount: 6,
              problemMix: 'mechanical',
              subtopics: ['uso de formula cuadratica', 'organizacion algebraica', 'simplificacion final'],
              skills: ['formula-general', 'resolucion-cuadratica', 'precision-tecnica'],
            },
            {
              title: 'El discriminante',
              difficulty: 10,
              questionCount: 6,
              subtopics: ['b^2 - 4ac', 'numero de soluciones', 'naturaleza de raices'],
              skills: ['discriminante', 'analisis-soluciones', 'criterio-algebraico'],
            },
            {
              title: 'Comparacion de metodos',
              difficulty: 10,
              questionCount: 6,
              subtopics: ['ventajas de metodos', 'eficiencia estrategica'],
              skills: ['seleccion-metodo', 'estrategia', 'ecuaciones-cuadraticas'],
            },
            {
              title: 'Interpretacion grafica de soluciones',
              difficulty: 10,
              questionCount: 6,
              subtopics: ['interseccion con eje x', 'relacion con discriminante'],
              skills: ['interpretacion-grafica', 'raices', 'parabolas'],
            },
            {
              title: 'Ecuaciones cuadraticas con parametro',
              difficulty: 10,
              questionCount: 6,
              subtopics: ['analisis segun parametro', 'condiciones de soluciones'],
              skills: ['parametros', 'analisis-condicional', 'ecuaciones-cuadraticas'],
            },
            {
              title: 'Problemas contextualizados',
              difficulty: 10,
              questionCount: 6,
              problemMix: 'contextualized',
              subtopics: ['modelacion algebraica', 'traduccion de contexto'],
              skills: ['modelacion-cuadratica', 'traduccion-matematica', 'contexto-real'],
            },
            {
              title: 'Ecuaciones cuadraticas factorizables no evidentes',
              difficulty: 10,
              questionCount: 6,
              subtopics: ['reorganizacion estructural', 'factorizacion estrategica'],
              skills: ['factorizacion-avanzada', 'analisis-estructural', 'ecuaciones'],
            },
            {
              title: 'Integracion avanzada de metodos',
              difficulty: 10,
              questionCount: 6,
              subtopics: ['comparacion de metodos', 'discriminante', 'grafica', 'modelacion'],
              skills: ['integracion-cuadratica', 'estrategia', 'nivel-elite'],
            },
          ],
        }),
        buildTopic({
          id: 'inecuaciones-lineales-cuadraticas',
          name: 'Unidad 2 - Inecuaciones Lineales y Cuadraticas',
          subtopics: [
            'Inecuaciones lineales',
            'Inecuaciones cuadraticas',
            'Analisis del signo',
            'Representacion en intervalos',
            'Modelacion con desigualdades',
          ],
          difficultyRange: [9, 10],
          problemMix: 'mixed',
          questionCountRange: [5, 6],
          lessons: [
            {
              title: 'Concepto de desigualdad algebraica',
              difficulty: 9,
              questionCount: 5,
              subtopics: ['simbolos >, <, >=, <=', 'interpretacion estructural'],
              skills: ['desigualdades', 'interpretacion', 'comparacion'],
            },
            {
              title: 'Inecuaciones lineales basicas',
              difficulty: 9,
              questionCount: 5,
              problemMix: 'mechanical',
              subtopics: ['despeje estructurado', 'cambio de sentido con negativo'],
              skills: ['inecuaciones-lineales', 'despeje', 'reglas-signo'],
            },
            {
              title: 'Representacion en la recta numerica',
              difficulty: 9,
              questionCount: 5,
              subtopics: ['intervalos abiertos y cerrados', 'conjunto solucion'],
              skills: ['recta-numerica', 'intervalos', 'representacion'],
            },
            {
              title: 'Inecuaciones lineales compuestas',
              difficulty: 9,
              questionCount: 5,
              subtopics: ['desigualdades dobles', 'interseccion de intervalos'],
              skills: ['inecuaciones-compuestas', 'interseccion', 'intervalos'],
            },
            {
              title: 'Introduccion a inecuaciones cuadraticas',
              difficulty: 10,
              questionCount: 6,
              subtopics: ['forma estandar', 'relacion con ecuacion asociada'],
              skills: ['inecuaciones-cuadraticas', 'estructura', 'analisis'],
            },
            {
              title: 'Resolucion por factorizacion',
              difficulty: 10,
              questionCount: 6,
              problemMix: 'mechanical',
              subtopics: ['puntos criticos', 'analisis de signos'],
              skills: ['factorizacion', 'recta-signos', 'inecuaciones-cuadraticas'],
            },
            {
              title: 'Metodo de la recta de signos',
              difficulty: 10,
              questionCount: 6,
              subtopics: ['tabla de signos', 'analisis por intervalos'],
              skills: ['recta-signos', 'tabla-signos', 'intervalos'],
            },
            {
              title: 'Inecuaciones cuadraticas no factorizables',
              difficulty: 10,
              questionCount: 6,
              subtopics: ['formula general', 'analisis del discriminante'],
              skills: ['formula-general', 'discriminante', 'inecuaciones-cuadraticas'],
            },
            {
              title: 'Interpretacion grafica',
              difficulty: 10,
              questionCount: 6,
              subtopics: ['parabola y regiones solucion', 'concavidad'],
              skills: ['interpretacion-grafica', 'parabola', 'regiones-solucion'],
            },
            {
              title: 'Inecuaciones racionales basicas',
              difficulty: 10,
              questionCount: 6,
              subtopics: ['restricciones del dominio', 'analisis de signos en fracciones'],
              skills: ['inecuaciones-racionales', 'dominio', 'analisis-signos'],
            },
            {
              title: 'Modelacion con desigualdades',
              difficulty: 10,
              questionCount: 6,
              problemMix: 'contextualized',
              subtopics: ['traduccion de situaciones reales', 'interpretacion de limites'],
              skills: ['modelacion-inecuaciones', 'traduccion-matematica', 'contexto-real'],
            },
            {
              title: 'Integracion estrategica de inecuaciones',
              difficulty: 10,
              questionCount: 6,
              subtopics: ['lineales', 'cuadraticas', 'racionales', 'analisis estructural'],
              skills: ['integracion-inecuaciones', 'dominio-completo', 'nivel-elite'],
            },
          ],
        }),
        buildTopic({
          id: 'sistemas-ecuaciones-modelacion-avanzada',
          name: 'Unidad 3 - Sistemas de Ecuaciones y Modelacion Avanzada',
          subtopics: [
            'Sistemas lineales y no lineales',
            'Metodos algebraicos avanzados',
            'Interpretacion grafica',
            'Modelacion con multiples variables',
            'Analisis estrategico de soluciones',
          ],
          difficultyRange: [9, 10],
          problemMix: 'mixed',
          questionCountRange: [5, 6],
          lessons: [
            {
              title: 'Repaso de sistemas lineales',
              difficulty: 9,
              questionCount: 5,
              subtopics: ['sustitucion', 'igualacion', 'interpretacion geometrica'],
              skills: ['sistemas-lineales', 'sustitucion', 'igualacion'],
            },
            {
              title: 'Metodo de eliminacion',
              difficulty: 9,
              questionCount: 5,
              problemMix: 'mechanical',
              subtopics: ['reduccion estrategica', 'combinacion lineal'],
              skills: ['eliminacion', 'reduccion', 'sistemas-lineales'],
            },
            {
              title: 'Sistemas con parametros',
              difficulty: 9,
              questionCount: 5,
              subtopics: ['solucion unica', 'infinitas soluciones', 'sin solucion'],
              skills: ['parametros', 'clasificacion-sistemas', 'analisis-condicional'],
            },
            {
              title: 'Sistemas lineal-cuadratico',
              difficulty: 10,
              questionCount: 6,
              subtopics: ['sustitucion estrategica', 'reduccion a cuadratica'],
              skills: ['sistema-lineal-cuadratico', 'sustitucion', 'ecuacion-cuadratica'],
            },
            {
              title: 'Sistemas cuadratico-cuadratico',
              difficulty: 10,
              questionCount: 6,
              subtopics: ['reduccion estructural', 'analisis de intersecciones'],
              skills: ['sistema-cuadratico', 'intersecciones', 'analisis-avanzado'],
            },
            {
              title: 'Interpretacion grafica profunda',
              difficulty: 10,
              questionCount: 6,
              subtopics: ['intersecciones multiples', 'regiones relevantes'],
              skills: ['interpretacion-grafica', 'intersecciones', 'analisis-geometrico'],
            },
            {
              title: 'Modelacion con dos variables',
              difficulty: 10,
              questionCount: 6,
              problemMix: 'contextualized',
              subtopics: ['traduccion de contexto a sistema', 'definicion de variables'],
              skills: ['modelacion-sistemas', 'variables', 'contexto-real'],
            },
            {
              title: 'Problemas con restricciones multiples',
              difficulty: 10,
              questionCount: 6,
              problemMix: 'contextualized',
              subtopics: ['condiciones adicionales', 'verificacion estructural'],
              skills: ['restricciones', 'verificacion', 'modelacion-avanzada'],
            },
            {
              title: 'Analisis estrategico de soluciones',
              difficulty: 10,
              questionCount: 6,
              subtopics: ['evaluacion de coherencia', 'descartar soluciones invalidas'],
              skills: ['analisis-coherencia', 'validacion', 'sistemas'],
            },
            {
              title: 'Sistemas con expresiones racionales',
              difficulty: 10,
              questionCount: 6,
              subtopics: ['eliminacion de denominadores', 'restricciones del dominio'],
              skills: ['sistemas-racionales', 'dominio', 'simplificacion'],
            },
            {
              title: 'Sistemas aplicados complejos',
              difficulty: 10,
              questionCount: 6,
              problemMix: 'contextualized',
              subtopics: ['modelacion multietapa', 'interpretacion profunda'],
              skills: ['modelacion-compleja', 'sistemas', 'analisis'],
            },
            {
              title: 'Integracion estrategica total',
              difficulty: 10,
              questionCount: 6,
              subtopics: ['sistemas lineales', 'no lineales', 'racionales', 'analisis grafico'],
              skills: ['integracion-sistemas', 'dominio-total', 'nivel-elite'],
            },
          ],
        }),
        buildTopic({
          id: 'integracion-algebraica-pensamiento-estrategico',
          name: 'Unidad 4 - Integracion Algebraica y Pensamiento Estrategico',
          subtopics: [
            'Integracion de ecuaciones e inecuaciones',
            'Sistemas combinados',
            'Expresiones racionales',
            'Modelacion algebraica multietapa',
            'Argumentacion formal',
          ],
          difficultyRange: [10, 10],
          problemMix: 'mixed',
          questionCountRange: [6, 6],
          lessons: [
            {
              title: 'Integracion ecuacion-inecuacion',
              difficulty: 10,
              questionCount: 6,
              subtopics: ['combinacion de igualdad y desigualdad', 'analisis conjunto'],
              skills: ['integracion-ecuacion-inecuacion', 'analisis-estructural'],
            },
            {
              title: 'Sistemas con restricciones de dominio',
              difficulty: 10,
              questionCount: 6,
              subtopics: ['expresiones racionales', 'condiciones de existencia', 'verificacion formal'],
              skills: ['sistemas-dominio', 'restricciones', 'verificacion'],
            },
            {
              title: 'Modelacion multietapa avanzada',
              difficulty: 10,
              questionCount: 6,
              problemMix: 'contextualized',
              subtopics: ['descomposicion estrategica', 'modelo progresivo'],
              skills: ['modelacion-multietapa', 'estrategia', 'resolucion'],
            },
            {
              title: 'Integracion de funciones y ecuaciones',
              difficulty: 10,
              questionCount: 6,
              subtopics: ['relacion funcion-raiz', 'intersecciones', 'interpretacion grafica'],
              skills: ['integracion-funciones-ecuaciones', 'intersecciones', 'analisis-grafico'],
            },
            {
              title: 'Analisis comparativo de modelos',
              difficulty: 10,
              questionCount: 6,
              problemMix: 'contextualized',
              subtopics: ['evaluacion de escenarios', 'criterio matematico', 'justificacion formal'],
              skills: ['comparacion-modelos', 'criterio', 'justificacion'],
            },
            {
              title: 'Optimizacion algebraica integrada',
              difficulty: 10,
              questionCount: 6,
              problemMix: 'contextualized',
              subtopics: ['maximos y minimos', 'restricciones multiples', 'interpretacion contextual'],
              skills: ['optimizacion', 'restricciones', 'integracion'],
            },
            {
              title: 'Problemas abiertos estructurados',
              difficulty: 10,
              questionCount: 6,
              problemMix: 'contextualized',
              subtopics: ['planteamiento libre', 'seleccion de metodo', 'argumentacion formal'],
              skills: ['problemas-abiertos', 'seleccion-metodo', 'argumentacion'],
            },
            {
              title: 'Analisis de errores y validacion',
              difficulty: 10,
              questionCount: 6,
              subtopics: ['identificacion de fallos algebraicos', 'correccion estructural'],
              skills: ['analisis-errores', 'validacion', 'correccion'],
            },
            {
              title: 'Integracion racional-cuadratica',
              difficulty: 10,
              questionCount: 6,
              subtopics: ['ecuaciones racionales', 'cuadraticas', 'analisis conjunto'],
              skills: ['integracion-racional-cuadratica', 'analisis-estructural'],
            },
            {
              title: 'Sistemas mixtos avanzados',
              difficulty: 10,
              questionCount: 6,
              subtopics: ['lineales', 'cuadraticos', 'racionales', 'restricciones'],
              skills: ['sistemas-mixtos', 'integracion', 'nivel-avanzado'],
            },
            {
              title: 'Argumentacion matematica formal',
              difficulty: 10,
              questionCount: 6,
              subtopics: ['justificacion paso a paso', 'coherencia logica', 'validez algebraica'],
              skills: ['argumentacion-formal', 'coherencia-logica', 'justificacion'],
            },
            {
              title: 'Integracion anual elite',
              difficulty: 10,
              questionCount: 6,
              problemMix: 'contextualized',
              subtopics: ['ecuaciones', 'inecuaciones', 'sistemas', 'modelacion', 'optimizacion'],
              skills: ['integracion-anual', 'dominio-total', 'nivel-elite'],
            },
          ],
        }),
      ],
    },
  ],
  finalExam: {
    id: 'grade-2-final-exam-elite-anual',
    name: 'Examen Final Anual 2do Secundaria (Nivel Elite)',
    questionRange: [30, 40],
    passingScore: 0.8,
    xpMultiplier: 3,
    aiHelpAllowed: false,
    examModes: {
      standard: {
        questionCount: 30,
        mixDistribution: [
          { mix: 'contextualized', count: 12 },
          { mix: 'mechanical', count: 10 },
          { mix: 'advanced-modeling', count: 8 },
        ],
      },
      elite: {
        questionCount: 36,
        mixDistribution: [
          { mix: 'contextualized', count: 15 },
          { mix: 'mechanical', count: 8 },
          { mix: 'advanced-modeling', count: 13 },
        ],
      },
      extreme: {
        questionCount: 40,
        minDifficulty: 10,
        mixDistribution: [
          { mix: 'contextualized', count: 16 },
          { mix: 'mechanical', count: 6 },
          { mix: 'advanced-modeling', count: 18 },
        ],
      },
    },
    sections: [
      {
        id: 'integracion-algebraica',
        name: 'Seccion A - Integracion Algebraica',
        count: 10,
        topicIds: [
          'ecuaciones-cuadraticas-metodos-resolucion',
          'potencias-y-leyes-de-los-exponentes',
          'radicales-y-racionalizacion',
          'polinomios-y-factorizacion-avanzada',
          'expresiones-algebraicas-racionales',
        ],
      },
      {
        id: 'funciones-sistemas',
        name: 'Seccion B - Funciones y Sistemas',
        count: 12,
        topicIds: [
          'funcion-cuadratica-analisis-estructural-completo',
          'transformaciones-y-composicion-de-funciones',
          'sistemas-no-lineales-y-analisis-grafico-avanzado',
          'sistemas-ecuaciones-modelacion-avanzada',
        ],
      },
      {
        id: 'inecuaciones-dominio',
        name: 'Seccion C - Inecuaciones y Dominio',
        count: 8,
        topicIds: ['inecuaciones-lineales-cuadraticas', 'expresiones-algebraicas-racionales'],
      },
      {
        id: 'modelacion-avanzada',
        name: 'Seccion D - Modelacion Avanzada',
        count: 10,
        topicIds: [
          'integracion-algebraica-pensamiento-estrategico',
          'modelacion-cuadratica-aplicada-pensamiento-estrategico',
          'sistemas-ecuaciones-modelacion-avanzada',
        ],
      },
    ],
    distribution: [
      { topicId: 'ecuaciones-cuadraticas-metodos-resolucion', count: 5, difficultyRange: [9, 10] },
      { topicId: 'potencias-y-leyes-de-los-exponentes', count: 3, difficultyRange: [9, 10] },
      { topicId: 'radicales-y-racionalizacion', count: 3, difficultyRange: [9, 10] },
      { topicId: 'polinomios-y-factorizacion-avanzada', count: 3, difficultyRange: [9, 10] },
      { topicId: 'expresiones-algebraicas-racionales', count: 3, difficultyRange: [9, 10] },
      { topicId: 'funcion-cuadratica-analisis-estructural-completo', count: 4, difficultyRange: [9, 10] },
      { topicId: 'transformaciones-y-composicion-de-funciones', count: 3, difficultyRange: [9, 10] },
      { topicId: 'sistemas-no-lineales-y-analisis-grafico-avanzado', count: 3, difficultyRange: [9, 10] },
      { topicId: 'sistemas-ecuaciones-modelacion-avanzada', count: 4, difficultyRange: [9, 10] },
      { topicId: 'inecuaciones-lineales-cuadraticas', count: 3, difficultyRange: [9, 10] },
      { topicId: 'modelacion-cuadratica-aplicada-pensamiento-estrategico', count: 3, difficultyRange: [9, 10] },
      { topicId: 'integracion-algebraica-pensamiento-estrategico', count: 3, difficultyRange: [10, 10] },
    ],
    mixDistribution: [
      { mix: 'contextualized', count: 18 },
      { mix: 'mechanical', count: 8 },
      { mix: 'advanced-modeling', count: 14 },
    ],
  },
}

export default grade2
