import { createLesson } from '../core/shared.js'

const buildTopic = ({
  id,
  name,
  subtopics = [],
  difficultyRange = [1, 3],
  problemMix = 'mixed',
  questionCountRange = [4, 4],
  lessons = [],
}) => ({
  id,
  name,
  subtopics,
  difficultyRange,
  problemMix,
  questionCountRange,
  lessons: lessons.map((lesson, index) =>
    createLesson({
      topicId: id,
      index: index + 1,
      ...lesson,
      problemMix: lesson.problemMix || problemMix,
      subtopics: lesson.subtopics || [],
    }),
  ),
})

const grade1 = {
  id: 'grade-1',
  gradeNumber: 1,
  name: '1ro Secundaria - Matematicas (Alto Rendimiento)',
  objective:
    'Desarrollar comprension solida de numeros, operaciones, proporciones, relaciones algebraicas simples, geometria plana y sentido de datos/probabilidad con aplicacion real.',
  areas: [
    {
      id: 'numeros-naturales',
      name: '1. Numeros Naturales',
      topics: [
        buildTopic({
          id: 'operaciones-basicas',
          name: 'Operaciones Basicas',
          subtopics: [
            'Suma con dinero (compras)',
            'Multiplicacion para agrupar objetos',
            'Division para repartir entre amigos',
          ],
          difficultyRange: [1, 3],
          problemMix: 'contextualized',
          questionCountRange: [3, 3],
          lessons: [
            {
              title: 'Suma contextualizada con dinero',
              difficulty: 1,
              questionCount: 3,
              problemMix: 'contextualized',
              subtopics: ['suma con dinero'],
              skills: ['suma', 'compras', 'contexto'],
            },
            {
              title: 'Multiplicacion contextualizada para agrupar',
              difficulty: 2,
              questionCount: 3,
              problemMix: 'contextualized',
              subtopics: ['multiplicacion para agrupar objetos'],
              skills: ['multiplicacion', 'grupos', 'contexto'],
            },
            {
              title: 'Division contextualizada para repartir',
              difficulty: 3,
              questionCount: 3,
              problemMix: 'contextualized',
              subtopics: ['division para repartir entre amigos'],
              skills: ['division', 'reparto', 'contexto'],
            },
          ],
        }),
      ],
    },
    {
      id: 'aritmetica-fundamental',
      name: '2. Aritmetica Fundamental',
      topics: [
        buildTopic({
          id: 'jerarquia-operaciones',
          name: 'Jerarquia de Operaciones',
          subtopics: ['Operaciones combinadas', 'Prioridad operatoria', 'Aplicacion en contexto'],
          difficultyRange: [4, 6],
          problemMix: 'mixed',
          questionCountRange: [4, 4],
          lessons: [
            {
              title: 'Jerarquia de operaciones mecanica',
              difficulty: 4,
              questionCount: 4,
              problemMix: 'mixed',
              subtopics: ['operaciones combinadas'],
              skills: ['jerarquia', 'calculo', 'prioridad'],
            },
            {
              title: 'Jerarquia de operaciones contextualizada',
              difficulty: 5,
              questionCount: 4,
              problemMix: 'mixed',
              subtopics: ['aplicacion con contexto'],
              skills: ['jerarquia', 'modelado', 'contexto'],
            },
          ],
        }),
        buildTopic({
          id: 'divisibilidad',
          name: 'Divisibilidad',
          subtopics: ['Multiplos', 'Divisores', 'Criterios 2,3,5,10', 'Numeros primos y compuestos'],
          difficultyRange: [4, 6],
          problemMix: 'mixed',
          questionCountRange: [4, 4],
          lessons: [
            {
              title: 'Multiplos y divisores',
              difficulty: 4,
              questionCount: 4,
              problemMix: 'mixed',
              subtopics: ['multiplos', 'divisores'],
              skills: ['multiplos', 'divisores'],
            },
            {
              title: 'Criterios de divisibilidad (2,3,5,10)',
              difficulty: 5,
              questionCount: 4,
              problemMix: 'mixed',
              subtopics: ['criterios de divisibilidad'],
              skills: ['criterios', 'divisibilidad'],
            },
            {
              title: 'Primos y compuestos aplicados',
              difficulty: 6,
              questionCount: 4,
              problemMix: 'mixed',
              subtopics: ['primos', 'compuestos', 'contexto'],
              skills: ['primos', 'compuestos', 'analisis'],
            },
          ],
        }),
        buildTopic({
          id: 'fracciones',
          name: 'Fracciones',
          subtopics: ['Representacion', 'Equivalentes', 'Comparacion', 'Suma, resta y multiplicacion'],
          difficultyRange: [4, 6],
          problemMix: 'mixed',
          questionCountRange: [4, 5],
          lessons: [
            {
              title: 'Representacion y fracciones equivalentes',
              difficulty: 4,
              questionCount: 4,
              problemMix: 'mixed',
              subtopics: ['representacion', 'equivalentes'],
              skills: ['representacion', 'equivalencia'],
            },
            {
              title: 'Comparacion de fracciones',
              difficulty: 5,
              questionCount: 4,
              problemMix: 'mixed',
              subtopics: ['comparacion'],
              skills: ['comparacion', 'orden'],
            },
            {
              title: 'Suma, resta y multiplicacion de fracciones',
              difficulty: 6,
              questionCount: 5,
              problemMix: 'mixed',
              subtopics: ['suma', 'resta', 'multiplicacion'],
              skills: ['operaciones-fracciones', 'contexto'],
            },
          ],
        }),
      ],
    },
    {
      id: 'geometria',
      name: '3. Geometria',
      topics: [
        buildTopic({
          id: 'figuras-planas',
          name: 'Figuras Planas',
          subtopics: ['Triangulos', 'Cuadrilateros', 'Perimetro', 'Area de cuadrado, rectangulo y triangulo'],
          difficultyRange: [4, 5],
          problemMix: 'mixed',
          questionCountRange: [4, 5],
          lessons: [
            {
              title: 'Triangulos y cuadrilateros',
              difficulty: 4,
              questionCount: 4,
              problemMix: 'mixed',
              subtopics: ['triangulos', 'cuadrilateros'],
              skills: ['figuras', 'clasificacion'],
            },
            {
              title: 'Perimetro de figuras planas',
              difficulty: 4,
              questionCount: 4,
              problemMix: 'mixed',
              subtopics: ['perimetro'],
              skills: ['perimetro', 'longitud'],
            },
            {
              title: 'Area de cuadrado, rectangulo y triangulo',
              difficulty: 5,
              questionCount: 5,
              problemMix: 'mixed',
              subtopics: ['area cuadrado', 'area rectangulo', 'area triangulo'],
              skills: ['area', 'modelado'],
            },
          ],
        }),
        buildTopic({
          id: 'angulos',
          name: 'Angulos',
          subtopics: ['Tipos de angulos', 'Medicion con transportador', 'Complementarios y suplementarios'],
          difficultyRange: [4, 6],
          problemMix: 'mixed',
          questionCountRange: [4, 4],
          lessons: [
            {
              title: 'Tipos de angulos',
              difficulty: 4,
              questionCount: 4,
              problemMix: 'mixed',
              subtopics: ['tipos de angulos'],
              skills: ['agudo', 'recto', 'obtuso'],
            },
            {
              title: 'Medicion de angulos con transportador',
              difficulty: 5,
              questionCount: 4,
              problemMix: 'mixed',
              subtopics: ['medicion con transportador'],
              skills: ['medicion', 'grados'],
            },
            {
              title: 'Angulos complementarios y suplementarios',
              difficulty: 6,
              questionCount: 4,
              problemMix: 'mixed',
              subtopics: ['complementarios', 'suplementarios'],
              skills: ['complementarios', 'suplementarios'],
            },
          ],
        }),
      ],
    },
    {
      id: 'algebra-basica',
      name: '4. Algebra Basica',
      topics: [
        buildTopic({
          id: 'expresiones-algebraicas',
          name: 'Expresiones Algebraicas',
          subtopics: ['Variables', 'Traduccion verbal a algebraico', 'Evaluacion', 'Simplificacion'],
          difficultyRange: [4, 5],
          problemMix: 'mixed',
          questionCountRange: [4, 4],
          lessons: [
            {
              title: 'Variables y traduccion verbal a algebraico',
              difficulty: 4,
              questionCount: 4,
              problemMix: 'mixed',
              subtopics: ['variables', 'traduccion verbal'],
              skills: ['variables', 'traduccion'],
            },
            {
              title: 'Evaluacion de expresiones algebraicas',
              difficulty: 5,
              questionCount: 4,
              problemMix: 'mixed',
              subtopics: ['evaluacion'],
              skills: ['evaluacion', 'sustitucion'],
            },
            {
              title: 'Simplificacion de expresiones',
              difficulty: 5,
              questionCount: 4,
              problemMix: 'mixed',
              subtopics: ['simplificacion'],
              skills: ['terminos semejantes', 'simplificacion'],
            },
          ],
        }),
        buildTopic({
          id: 'ecuaciones-basicas',
          name: 'Ecuaciones Basicas',
          subtopics: ['x + a = b', 'ax = b', 'Dos operaciones', 'Traduccion de contexto'],
          difficultyRange: [4, 6],
          problemMix: 'mixed',
          questionCountRange: [4, 5],
          lessons: [
            {
              title: 'Resolucion de x + a = b',
              difficulty: 4,
              questionCount: 4,
              problemMix: 'mixed',
              subtopics: ['x + a = b'],
              skills: ['ecuacion-lineal', 'despeje'],
            },
            {
              title: 'Resolucion de ax = b',
              difficulty: 5,
              questionCount: 4,
              problemMix: 'mixed',
              subtopics: ['ax = b'],
              skills: ['ecuacion-lineal', 'division'],
            },
            {
              title: 'Ecuaciones de dos operaciones y contexto',
              difficulty: 6,
              questionCount: 5,
              problemMix: 'mixed',
              subtopics: ['dos operaciones', 'traduccion de contexto'],
              skills: ['ecuacion-dos-pasos', 'modelado'],
            },
          ],
        }),
      ],
    },
    {
      id: 'estadistica-probabilidad',
      name: '5. Estadistica y Probabilidad',
      topics: [
        buildTopic({
          id: 'estadistica',
          name: 'Estadistica',
          subtopics: ['Recoleccion de datos', 'Tabla de frecuencia', 'Grafico de barras', 'Media aritmetica'],
          difficultyRange: [2, 3],
          problemMix: 'contextualized',
          questionCountRange: [3, 4],
          lessons: [
            {
              title: 'Recoleccion de datos y tabla de frecuencia',
              difficulty: 2,
              questionCount: 3,
              problemMix: 'contextualized',
              subtopics: ['recoleccion', 'frecuencia'],
              skills: ['datos', 'frecuencia'],
            },
            {
              title: 'Interpretacion de grafico de barras',
              difficulty: 3,
              questionCount: 4,
              problemMix: 'contextualized',
              subtopics: ['grafico de barras'],
              skills: ['grafico', 'interpretacion'],
            },
            {
              title: 'Media aritmetica aplicada',
              difficulty: 3,
              questionCount: 4,
              problemMix: 'contextualized',
              subtopics: ['media aritmetica'],
              skills: ['media', 'analisis'],
            },
          ],
        }),
        buildTopic({
          id: 'probabilidad-simple',
          name: 'Probabilidad Simple',
          subtopics: ['Espacio muestral', 'Experimentos simples', 'Concepto basico de probabilidad'],
          difficultyRange: [4, 6],
          problemMix: 'mixed',
          questionCountRange: [3, 4],
          lessons: [
            {
              title: 'Espacio muestral en experimentos simples',
              difficulty: 4,
              questionCount: 3,
              problemMix: 'mixed',
              subtopics: ['espacio muestral'],
              skills: ['espacio-muestral'],
            },
            {
              title: 'Probabilidad simple en contexto',
              difficulty: 5,
              questionCount: 4,
              problemMix: 'mixed',
              subtopics: ['experimentos simples', 'probabilidad basica'],
              skills: ['probabilidad', 'contexto'],
            },
          ],
        }),
      ],
    },
    {
      id: 'medicion',
      name: '6. Medicion',
      topics: [
        buildTopic({
          id: 'unidades-de-medida',
          name: 'Unidades de Medida',
          subtopics: ['Longitud', 'Masa', 'Capacidad', 'Conversion de unidades'],
          difficultyRange: [2, 3],
          problemMix: 'contextualized',
          questionCountRange: [3, 4],
          lessons: [
            {
              title: 'Longitud, masa y capacidad en contexto',
              difficulty: 2,
              questionCount: 3,
              problemMix: 'contextualized',
              subtopics: ['longitud', 'masa', 'capacidad'],
              skills: ['medicion', 'unidades'],
            },
            {
              title: 'Conversion de unidades basicas',
              difficulty: 3,
              questionCount: 4,
              problemMix: 'contextualized',
              subtopics: ['conversion de unidades'],
              skills: ['conversion', 'equivalencias'],
            },
            {
              title: 'Conversion de unidades aplicadas',
              difficulty: 3,
              questionCount: 4,
              problemMix: 'contextualized',
              subtopics: ['conversion en problemas reales'],
              skills: ['conversion', 'aplicacion'],
            },
          ],
        }),
      ],
    },
  ],
  finalExam: {
    id: 'grade-1-final-exam',
    name: 'Examen Final 1ro Secundaria (Alto Rendimiento)',
    questionRange: [60, 60],
    passingScore: 0.75,
    xpMultiplier: 2,
    aiHelpAllowed: false,
    sections: [
      { id: 'aritmetica', name: 'Aritmetica', count: 15, topicIds: ['jerarquia-operaciones', 'divisibilidad', 'fracciones'] },
      { id: 'geometria', name: 'Geometria', count: 12, topicIds: ['figuras-planas', 'angulos'] },
      { id: 'algebra', name: 'Algebra', count: 12, topicIds: ['ecuaciones-basicas', 'expresiones-algebraicas'] },
      { id: 'estadistica-probabilidad', name: 'Estadistica y Probabilidad', count: 11, topicIds: ['estadistica', 'probabilidad-simple'] },
      { id: 'medicion', name: 'Medicion', count: 10, topicIds: ['unidades-de-medida'] },
    ],
    distribution: [
      { topicId: 'jerarquia-operaciones', count: 5, difficultyRange: [4, 6] },
      { topicId: 'divisibilidad', count: 5, difficultyRange: [4, 6] },
      { topicId: 'fracciones', count: 5, difficultyRange: [4, 6] },
      { topicId: 'figuras-planas', count: 7, difficultyRange: [4, 6] },
      { topicId: 'angulos', count: 5, difficultyRange: [4, 6] },
      { topicId: 'ecuaciones-basicas', count: 6, difficultyRange: [4, 6] },
      { topicId: 'expresiones-algebraicas', count: 6, difficultyRange: [4, 6] },
      { topicId: 'estadistica', count: 6, difficultyRange: [2, 5] },
      { topicId: 'probabilidad-simple', count: 5, difficultyRange: [4, 6] },
      { topicId: 'unidades-de-medida', count: 10, difficultyRange: [2, 4] },
    ],
  },
}

export default grade1
