import { createLesson } from '../core/shared.js'

const buildTopic = ({
  id,
  name,
  subtopics = [],
  difficultyRange = [1, 4],
  problemMix = 'mixed',
  questionCountRange = [3, 5],
  lessons = [],
}) => ({
  id,
  name,
  subtopics,
  difficultyRange,
  problemMix,
  questionCountRange,
  lessons: lessons.map((lesson, index) =>
    createLesson({
      topicId: id,
      index: index + 1,
      ...lesson,
      problemMix: lesson.problemMix || problemMix,
      subtopics: lesson.subtopics || [],
    }),
  ),
})

const grade1 = {
  id: 'grade-1',
  gradeNumber: 1,
  name: '1ro Secundaria - Matematica (Alto Rendimiento)',
  objective:
    'Consolidar fundamentos numericos, transitar al pensamiento algebraico y desarrollar razonamiento proporcional y geometrico con modelacion formal.',
  areas: [
    {
      id: 'numeros-naturales',
      name: '1er Bimestre - Unidad 1: Fundamentos Numericos (Sistema Decimal)',
      topics: [
        buildTopic({
          id: 'sistema-numeros-naturales-decimal',
          name: 'Sistema de Numeros Naturales (Estructura Decimal)',
          subtopics: [
            'Lectura y escritura de numeros naturales',
            'Valor posicional y estructura decimal',
            'Comparacion y orden de numeros naturales',
            'Propiedades de la suma',
            'Propiedades de la multiplicacion y distributividad',
          ],
          difficultyRange: [1, 4],
          problemMix: 'mixed',
          questionCountRange: [3, 4],
          lessons: [
            {
              title: 'Lectura y escritura de numeros naturales',
              difficulty: 1,
              questionCount: 3,
              problemMix: 'contextualized',
              subtopics: ['lectura de cantidades', 'forma verbal y numerica'],
              skills: ['numeracion-decimal', 'representacion', 'conversion'],
            },
            {
              title: 'Valor posicional y estructura del sistema decimal',
              difficulty: 2,
              questionCount: 3,
              problemMix: 'contextualized',
              subtopics: ['valor posicional', 'descomposicion aditiva', 'potencias de 10'],
              skills: ['valor-posicional', 'descomposicion', 'base-10'],
            },
            {
              title: 'Comparacion y orden de numeros naturales',
              difficulty: 2,
              questionCount: 3,
              problemMix: 'contextualized',
              subtopics: ['relaciones de orden', 'desigualdad', 'magnitud'],
              skills: ['orden', 'comparacion', 'magnitud'],
            },
            {
              title: 'Propiedades de la suma y estructura aditiva',
              difficulty: 3,
              questionCount: 3,
              problemMix: 'contextualized',
              subtopics: ['conmutativa', 'asociativa', 'elemento neutro'],
              skills: ['propiedades-suma', 'estructura-aditiva'],
            },
            {
              title: 'Propiedades de la multiplicacion y distributividad',
              difficulty: 4,
              questionCount: 4,
              problemMix: 'mixed',
              subtopics: ['conmutativa', 'asociativa', 'distributiva'],
              skills: ['propiedades-multiplicacion', 'distributividad', 'base-algebraica'],
            },
          ],
        }),
      ],
    },
    {
      id: 'aritmetica-fundamental',
      name: '1er Bimestre - Unidad 2: Operaciones Fundamentales y Modelacion Numerica',
      topics: [
        buildTopic({
          id: 'operaciones-fundamentales-modelacion-numerica',
          name: 'Operaciones Fundamentales y Modelacion Numerica',
          subtopics: [
            'Suma y resta combinada',
            'Multiplicacion y division combinada',
            'Jerarquia de operaciones formal',
            'Modelacion de problemas multietapa',
            'Desafio integrador de operaciones estructuradas',
          ],
          difficultyRange: [4, 7],
          problemMix: 'mixed',
          questionCountRange: [4, 5],
          lessons: [
            {
              title: 'Suma y resta combinada en expresiones numericas',
              difficulty: 4,
              questionCount: 4,
              problemMix: 'mixed',
              subtopics: ['secuencia aditiva', 'control de procedimiento'],
              skills: ['suma-resta-combinada', 'coherencia-operativa'],
            },
            {
              title: 'Multiplicacion y division combinada',
              difficulty: 5,
              questionCount: 4,
              problemMix: 'mixed',
              subtopics: ['relacion inversa', 'calculo compuesto'],
              skills: ['multiplicacion-division-combinada', 'relacion-inversa'],
            },
            {
              title: 'Jerarquia de operaciones (orden operativo formal)',
              difficulty: 6,
              questionCount: 5,
              problemMix: 'mixed',
              subtopics: ['parentesis', 'prioridad', 'orden operativo'],
              skills: ['jerarquia-operativa', 'evaluacion-expresiones'],
            },
            {
              title: 'Modelacion de problemas multietapa',
              difficulty: 6,
              questionCount: 5,
              problemMix: 'mixed',
              subtopics: ['traduccion verbal', 'estructura de pasos'],
              skills: ['modelacion-numerica', 'multietapa'],
            },
            {
              title: 'Desafio integrador de operaciones estructuradas',
              difficulty: 7,
              questionCount: 5,
              problemMix: 'mixed',
              subtopics: ['integracion operativa', 'contextos no rutinarios'],
              skills: ['integracion-operaciones', 'alto-rendimiento'],
            },
          ],
        }),
      ],
    },
    {
      id: 'numeros-enteros',
      name: '1er Bimestre - Unidad 3: Introduccion al Sistema de Numeros Enteros',
      topics: [
        buildTopic({
          id: 'introduccion-sistema-numeros-enteros',
          name: 'Introduccion al Sistema de Numeros Enteros',
          subtopics: [
            'Concepto y representacion de enteros',
            'Recta numerica y orden',
            'Suma de enteros',
            'Resta de enteros y equivalencia aditiva',
            'Problemas contextualizados con enteros',
          ],
          difficultyRange: [3, 7],
          problemMix: 'mixed',
          questionCountRange: [3, 5],
          lessons: [
            {
              title: 'Concepto y representacion de numeros enteros',
              difficulty: 3,
              questionCount: 3,
              problemMix: 'contextualized',
              subtopics: ['positivos y negativos', 'interpretacion con direccion'],
              skills: ['enteros-concepto', 'representacion'],
            },
            {
              title: 'Recta numerica y orden en los enteros',
              difficulty: 4,
              questionCount: 4,
              problemMix: 'mixed',
              subtopics: ['ubicacion en recta', 'comparacion de enteros'],
              skills: ['recta-numerica', 'orden-enteros'],
            },
            {
              title: 'Suma de numeros enteros',
              difficulty: 5,
              questionCount: 4,
              problemMix: 'mixed',
              subtopics: ['reglas de signo', 'desplazamiento en recta'],
              skills: ['suma-enteros', 'simetria-aditiva'],
            },
            {
              title: 'Resta de enteros y equivalencia aditiva',
              difficulty: 6,
              questionCount: 5,
              problemMix: 'mixed',
              subtopics: ['suma del opuesto', 'inverso aditivo'],
              skills: ['resta-enteros', 'equivalencia-aditiva'],
            },
            {
              title: 'Problemas contextualizados con numeros enteros',
              difficulty: 7,
              questionCount: 5,
              problemMix: 'mixed',
              subtopics: ['contexto financiero', 'variacion termica', 'cambios netos'],
              skills: ['modelacion-enteros', 'interpretacion-contextual'],
            },
          ],
        }),
      ],
    },
    {
      id: 'geometria',
      name: '1er Bimestre - Unidad 4: Fundamentos de Geometria Plana Inicial',
      topics: [
        buildTopic({
          id: 'fundamentos-geometria-plana-inicial',
          name: 'Fundamentos de Geometria Plana Inicial',
          subtopics: [
            'Punto, recta y plano',
            'Segmentos y angulos',
            'Triangulos por lados y angulos',
            'Perimetro de figuras planas',
            'Problemas integradores geometrico-numericos',
          ],
          difficultyRange: [3, 7],
          problemMix: 'mixed',
          questionCountRange: [3, 5],
          lessons: [
            {
              title: 'Conceptos basicos: punto, recta y plano',
              difficulty: 3,
              questionCount: 3,
              problemMix: 'contextualized',
              subtopics: ['elementos primitivos', 'lenguaje geometrico'],
              skills: ['punto-recta-plano', 'geometria-euclidiana'],
            },
            {
              title: 'Segmentos y angulos: clasificacion y medicion basica',
              difficulty: 4,
              questionCount: 4,
              problemMix: 'mixed',
              subtopics: ['segmento', 'angulo', 'medicion'],
              skills: ['segmentos', 'angulos', 'clasificacion'],
            },
            {
              title: 'Triangulos: clasificacion por lados y angulos',
              difficulty: 5,
              questionCount: 4,
              problemMix: 'mixed',
              subtopics: ['equilatero', 'isosceles', 'escaleno', 'acutangulo', 'rectangulo', 'obtusangulo'],
              skills: ['triangulos', 'clasificacion-formal'],
            },
            {
              title: 'Perimetro de figuras planas',
              difficulty: 6,
              questionCount: 5,
              problemMix: 'mixed',
              subtopics: ['contorno', 'suma de longitudes', 'figuras compuestas'],
              skills: ['perimetro', 'modelacion-geometrica'],
            },
            {
              title: 'Problemas integradores geometrico-numericos',
              difficulty: 7,
              questionCount: 5,
              problemMix: 'mixed',
              subtopics: ['integracion aritmetica-geometria', 'problemas no rutinarios'],
              skills: ['integracion-geometrica', 'razonamiento-espacial'],
            },
          ],
        }),
      ],
    },
    {
      id: 'algebra-basica-bimestre-2',
      name: '2do Bimestre - Unidad 1: Lenguaje Algebraico y Expresiones',
      topics: [
        buildTopic({
          id: 'lenguaje-algebraico-expresiones',
          name: 'Lenguaje Algebraico y Expresiones',
          subtopics: [
            'Variables y representacion de cantidades',
            'Traduccion verbal a expresion algebraica',
            'Terminos algebraicos y clasificacion',
            'Reduccion de terminos semejantes',
            'Evaluacion de expresiones',
            'Propiedades operativas algebraicas',
            'Modelacion algebraica basica',
            'Integracion estructural algebraica',
          ],
          difficultyRange: [4, 8],
          problemMix: 'mixed',
          questionCountRange: [4, 6],
          lessons: [
            {
              title: 'Uso de letras para representar cantidades',
              difficulty: 4,
              questionCount: 4,
              problemMix: 'mixed',
              subtopics: ['variable', 'cantidad desconocida', 'cantidad general'],
              skills: ['variables', 'representacion-simbolica'],
            },
            {
              title: 'Traduccion de enunciados a expresiones algebraicas',
              difficulty: 5,
              questionCount: 5,
              problemMix: 'contextualized',
              subtopics: ['traduccion verbal', 'expresion algebraica'],
              skills: ['traduccion-algebraica', 'modelacion-verbal'],
            },
            {
              title: 'Terminos algebraicos y clasificacion',
              difficulty: 5,
              questionCount: 5,
              problemMix: 'mechanical',
              subtopics: ['termino', 'coeficiente', 'parte literal', 'grado'],
              skills: ['clasificacion-terminos', 'estructura-algebraica'],
            },
            {
              title: 'Reduccion de terminos semejantes',
              difficulty: 6,
              questionCount: 6,
              problemMix: 'mixed',
              subtopics: ['terminos semejantes', 'simplificacion'],
              skills: ['reduccion', 'simplificacion-algebraica'],
            },
            {
              title: 'Evaluacion de expresiones algebraicas',
              difficulty: 6,
              questionCount: 6,
              problemMix: 'mechanical',
              subtopics: ['sustitucion', 'jerarquia operativa'],
              skills: ['evaluacion-expresiones', 'sustitucion'],
            },
            {
              title: 'Propiedades operativas en expresiones algebraicas',
              difficulty: 7,
              questionCount: 6,
              problemMix: 'mixed',
              subtopics: ['conmutativa', 'asociativa', 'distributiva'],
              skills: ['propiedades-algebraicas', 'reestructuracion'],
            },
            {
              title: 'Problemas algebraicos de modelacion basica',
              difficulty: 7,
              questionCount: 6,
              problemMix: 'contextualized',
              subtopics: ['modelacion', 'una o dos variables'],
              skills: ['modelacion-algebraica', 'contexto'],
            },
            {
              title: 'Integracion estructural algebraica',
              difficulty: 8,
              questionCount: 6,
              problemMix: 'contextualized',
              subtopics: ['traduccion', 'simplificacion', 'evaluacion'],
              skills: ['integracion-algebraica', 'alto-rendimiento'],
            },
          ],
        }),
      ],
    },
    {
      id: 'algebra-ecuaciones-lineales',
      name: '2do Bimestre - Unidad 2: Ecuaciones Lineales de Primer Grado',
      topics: [
        buildTopic({
          id: 'ecuaciones-lineales-primer-grado',
          name: 'Ecuaciones Lineales de Primer Grado',
          subtopics: [
            'Concepto de ecuacion y principio de igualdad',
            'Ecuaciones simples x + a = b',
            'Ecuaciones con multiplicacion y division',
            'Terminos en ambos miembros',
            'Parentesis y distributiva',
            'Problemas verbales de una incognita',
            'Enteros y fracciones simples',
            'Integracion avanzada de ecuaciones',
          ],
          difficultyRange: [5, 9],
          problemMix: 'mixed',
          questionCountRange: [5, 6],
          lessons: [
            {
              title: 'Concepto de ecuacion y principio de igualdad',
              difficulty: 5,
              questionCount: 5,
              problemMix: 'mechanical',
              subtopics: ['ecuacion', 'igualdad', 'equilibrio'],
              skills: ['principio-igualdad', 'reconocimiento-ecuaciones'],
            },
            {
              title: 'Resolucion de ecuaciones simples (x + a = b)',
              difficulty: 6,
              questionCount: 6,
              problemMix: 'mechanical',
              subtopics: ['operacion inversa', 'despeje simple'],
              skills: ['ecuacion-simple', 'operaciones-inversas'],
            },
            {
              title: 'Ecuaciones con multiplicacion y division',
              difficulty: 6,
              questionCount: 6,
              problemMix: 'mixed',
              subtopics: ['ax = b', 'x/a = b'],
              skills: ['ecuacion-mul-div', 'coeficiente'],
            },
            {
              title: 'Ecuaciones con terminos en ambos miembros',
              difficulty: 7,
              questionCount: 6,
              problemMix: 'mixed',
              subtopics: ['transposicion', 'reduccion'],
              skills: ['ambos-miembros', 'aislamiento-variable'],
            },
            {
              title: 'Ecuaciones con parentesis y distributiva',
              difficulty: 7,
              questionCount: 6,
              problemMix: 'mechanical',
              subtopics: ['distributiva', 'simplificacion previa'],
              skills: ['distributiva-ecuaciones', 'orden-procedimental'],
            },
            {
              title: 'Problemas verbales de una incognita',
              difficulty: 8,
              questionCount: 6,
              problemMix: 'contextualized',
              subtopics: ['modelacion verbal', 'planteamiento de ecuacion'],
              skills: ['modelacion-ecuaciones', 'contexto'],
            },
            {
              title: 'Ecuaciones con numeros enteros y fracciones simples',
              difficulty: 8,
              questionCount: 6,
              problemMix: 'mixed',
              subtopics: ['enteros', 'fracciones simples'],
              skills: ['ecuaciones-enteros-fracciones', 'precision-operativa'],
            },
            {
              title: 'Integracion avanzada de ecuaciones lineales',
              difficulty: 9,
              questionCount: 6,
              problemMix: 'contextualized',
              subtopics: ['multietapa', 'simplificacion + modelacion'],
              skills: ['integracion-ecuaciones', 'argumentacion-formal'],
            },
          ],
        }),
      ],
    },
    {
      id: 'aritmetica-fundamental-proporcionalidad',
      name: '2do Bimestre - Unidad 3: Razones, Proporciones y Proporcionalidad',
      topics: [
        buildTopic({
          id: 'razones-proporciones-proporcionalidad',
          name: 'Razones, Proporciones y Proporcionalidad',
          subtopics: [
            'Concepto de razon',
            'Proporciones y propiedad fundamental',
            'Magnitudes directamente proporcionales',
            'Magnitudes inversamente proporcionales',
            'Regla de tres simple directa',
            'Regla de tres simple inversa',
            'Porcentajes como proporcionalidad',
            'Integracion avanzada de proporcionalidad',
          ],
          difficultyRange: [5, 9],
          problemMix: 'mixed',
          questionCountRange: [5, 6],
          lessons: [
            {
              title: 'Concepto de razon',
              difficulty: 5,
              questionCount: 5,
              problemMix: 'mechanical',
              subtopics: ['comparacion multiplicativa', 'a:b', 'fraccion', 'decimal'],
              skills: ['razon', 'representaciones'],
            },
            {
              title: 'Proporciones y propiedad fundamental',
              difficulty: 6,
              questionCount: 6,
              problemMix: 'mechanical',
              subtopics: ['igualdad de razones', 'producto cruzado'],
              skills: ['proporcion', 'propiedad-fundamental'],
            },
            {
              title: 'Magnitudes directamente proporcionales',
              difficulty: 6,
              questionCount: 6,
              problemMix: 'contextualized',
              subtopics: ['proporcionalidad directa', 'tabla', 'ecuacion simple'],
              skills: ['directa', 'modelacion-proporcional'],
            },
            {
              title: 'Magnitudes inversamente proporcionales',
              difficulty: 7,
              questionCount: 6,
              problemMix: 'mixed',
              subtopics: ['proporcionalidad inversa', 'producto constante'],
              skills: ['inversa', 'razonamiento-estructurado'],
            },
            {
              title: 'Regla de tres simple directa',
              difficulty: 7,
              questionCount: 6,
              problemMix: 'contextualized',
              subtopics: ['procedimiento directo', 'valor desconocido'],
              skills: ['regla-de-tres-directa', 'procedimiento-claro'],
            },
            {
              title: 'Regla de tres simple inversa',
              difficulty: 8,
              questionCount: 6,
              problemMix: 'contextualized',
              subtopics: ['procedimiento inverso', 'naturaleza de relacion'],
              skills: ['regla-de-tres-inversa', 'analisis-relacional'],
            },
            {
              title: 'Porcentajes como caso particular de proporcionalidad',
              difficulty: 8,
              questionCount: 6,
              problemMix: 'mixed',
              subtopics: ['porcentaje', 'aumentos', 'descuentos', 'variaciones'],
              skills: ['porcentajes', 'contexto-financiero'],
            },
            {
              title: 'Integracion avanzada de proporcionalidad',
              difficulty: 9,
              questionCount: 6,
              problemMix: 'contextualized',
              subtopics: ['directa + inversa + porcentaje', 'multietapa'],
              skills: ['integracion-proporcional', 'modelacion-avanzada'],
            },
          ],
        }),
      ],
    },
    {
      id: 'geometria-proporcionalidad',
      name: '2do Bimestre - Unidad 4: Proporcionalidad en Geometria (Escalas y Semejanza)',
      topics: [
        buildTopic({
          id: 'proporcionalidad-geometrica-escalas-semejanza',
          name: 'Proporcionalidad Geometrica: Escalas y Semejanza',
          subtopics: [
            'Escalas y ampliacion/reduccion',
            'Figuras semejantes y razon de semejanza',
            'Lados faltantes en figuras semejantes',
            'Perimetros y semejanza',
            'Areas y razon de semejanza',
            'Escalas en contextos reales',
            'Integracion algebra + semejanza',
            'Integracion avanzada proporcional-geometrica',
          ],
          difficultyRange: [6, 10],
          problemMix: 'mixed',
          questionCountRange: [6, 6],
          lessons: [
            {
              title: 'Escalas y reduccion/ampliacion de figuras',
              difficulty: 6,
              questionCount: 6,
              problemMix: 'mixed',
              subtopics: ['factor de escala', 'planos', 'mapas', 'maquetas'],
              skills: ['escalas', 'ampliacion-reduccion'],
            },
            {
              title: 'Figuras semejantes y razon de semejanza',
              difficulty: 7,
              questionCount: 6,
              problemMix: 'mixed',
              subtopics: ['semejanza', 'lados correspondientes', 'razon'],
              skills: ['figuras-semejantes', 'razon-semejanza'],
            },
            {
              title: 'Calculo de lados faltantes en figuras semejantes',
              difficulty: 7,
              questionCount: 6,
              problemMix: 'mixed',
              subtopics: ['proporciones geometricas', 'medidas desconocidas'],
              skills: ['lados-faltantes', 'proporcionalidad-estructural'],
            },
            {
              title: 'Perimetros y semejanza',
              difficulty: 8,
              questionCount: 6,
              problemMix: 'mixed',
              subtopics: ['perimetro', 'factor de escala'],
              skills: ['perimetro-semejanza', 'variacion-lineal'],
            },
            {
              title: 'Areas y razon de semejanza',
              difficulty: 8,
              questionCount: 6,
              problemMix: 'mixed',
              subtopics: ['area', 'razon cuadratica'],
              skills: ['area-semejanza', 'factor-cuadratico'],
            },
            {
              title: 'Problemas de escala en contextos reales',
              difficulty: 9,
              questionCount: 6,
              problemMix: 'contextualized',
              subtopics: ['planos tecnicos', 'mapas', 'arquitectura'],
              skills: ['escala-contextual', 'modelacion-geometrica'],
            },
            {
              title: 'Integracion algebra + semejanza',
              difficulty: 9,
              questionCount: 6,
              problemMix: 'contextualized',
              subtopics: ['ecuaciones en semejanza', 'medidas desconocidas'],
              skills: ['ecuaciones-semejanza', 'integracion-algebra-geometria'],
            },
            {
              title: 'Integracion avanzada proporcional-geometrica',
              difficulty: 10,
              questionCount: 6,
              problemMix: 'contextualized',
              subtopics: ['escalas', 'semejanza', 'perimetro', 'area', 'ecuaciones', 'multietapa'],
              skills: ['integracion-proporcional-geometrica', 'abstraccion-elite'],
            },
          ],
        }),
      ],
    },
    {
      id: 'funciones-lineales-iniciales',
      name: '3er Bimestre - Unidad 1: Relaciones y Funciones Lineales Iniciales',
      topics: [
        buildTopic({
          id: 'relaciones-funciones-lineales-iniciales',
          name: 'Relaciones y Funciones Lineales Iniciales',
          subtopics: [
            'Relaciones entre magnitudes',
            'Tablas de valores y patrones',
            'Plano cartesiano y pares ordenados',
            'Representacion grafica de relaciones',
            'Concepto formal de funcion',
            'Funciones lineales y = mx',
            'Pendiente como tasa de cambio',
            'Integracion funcional avanzada',
          ],
          difficultyRange: [6, 10],
          problemMix: 'mixed',
          questionCountRange: [5, 6],
          lessons: [
            {
              title: 'Relaciones entre magnitudes',
              difficulty: 6,
              questionCount: 5,
              problemMix: 'contextualized',
              subtopics: ['variable dependiente', 'variable independiente'],
              skills: ['relaciones', 'dependencia-variables'],
            },
            {
              title: 'Tablas de valores y patrones',
              difficulty: 6,
              questionCount: 6,
              problemMix: 'mixed',
              subtopics: ['tabla de valores', 'regularidades'],
              skills: ['tablas', 'patrones'],
            },
            {
              title: 'Plano cartesiano y pares ordenados',
              difficulty: 7,
              questionCount: 6,
              problemMix: 'mixed',
              subtopics: ['ejes coordenados', 'pares ordenados'],
              skills: ['plano-cartesiano', 'coordenadas'],
            },
            {
              title: 'Representacion grafica de relaciones',
              difficulty: 7,
              questionCount: 6,
              problemMix: 'mixed',
              subtopics: ['tabla a grafica', 'crecimiento', 'decrecimiento'],
              skills: ['representacion-grafica', 'interpretacion'],
            },
            {
              title: 'Concepto formal de funcion',
              difficulty: 8,
              questionCount: 6,
              problemMix: 'mechanical',
              subtopics: ['definicion de funcion', 'unicidad de correspondencia'],
              skills: ['concepto-funcion', 'justificacion'],
            },
            {
              title: 'Funciones lineales de la forma y = mx',
              difficulty: 8,
              questionCount: 6,
              problemMix: 'mixed',
              subtopics: ['proporcionalidad directa', 'tabla y grafica'],
              skills: ['funcion-lineal-basica', 'y-equals-mx'],
            },
            {
              title: 'Interpretacion de pendiente como tasa de cambio',
              difficulty: 9,
              questionCount: 6,
              problemMix: 'contextualized',
              subtopics: ['pendiente', 'razon de cambio'],
              skills: ['pendiente', 'tasa-cambio'],
            },
            {
              title: 'Integracion funcional avanzada',
              difficulty: 10,
              questionCount: 6,
              problemMix: 'contextualized',
              subtopics: ['tabla', 'grafica', 'expresion algebraica', 'interpretacion'],
              skills: ['integracion-funcional', 'modelacion-lineal'],
            },
          ],
        }),
      ],
    },
    {
      id: 'algebra-sistemas-ecuaciones-intro',
      name: '3er Bimestre - Unidad 2: Sistemas de Ecuaciones Lineales (Introduccion)',
      topics: [
        buildTopic({
          id: 'sistemas-ecuaciones-lineales-introduccion',
          name: 'Sistemas de Ecuaciones Lineales (Introduccion)',
          subtopics: [
            'Ecuaciones lineales con dos variables',
            'Representacion grafica de ecuaciones lineales',
            'Concepto de sistema de ecuaciones',
            'Metodo grafico',
            'Metodo de sustitucion',
            'Metodo de igualacion',
            'Problemas verbales con sistemas',
            'Integracion grafica y algebraica',
          ],
          difficultyRange: [7, 10],
          problemMix: 'mixed',
          questionCountRange: [5, 6],
          lessons: [
            {
              title: 'Ecuaciones lineales con dos variables',
              difficulty: 7,
              questionCount: 5,
              problemMix: 'mechanical',
              subtopics: ['ax + by = c', 'pares ordenados solucion'],
              skills: ['dos-variables', 'soluciones-validas'],
            },
            {
              title: 'Representacion grafica de ecuaciones lineales',
              difficulty: 7,
              questionCount: 6,
              problemMix: 'mixed',
              subtopics: ['tabla de valores', 'grafica de recta'],
              skills: ['grafica-ecuacion', 'plano-cartesiano'],
            },
            {
              title: 'Concepto de sistema de ecuaciones',
              difficulty: 8,
              questionCount: 6,
              problemMix: 'mixed',
              subtopics: ['dos ecuaciones simultaneas', 'punto comun'],
              skills: ['concepto-sistema', 'interseccion'],
            },
            {
              title: 'Metodo grafico',
              difficulty: 8,
              questionCount: 6,
              problemMix: 'mixed',
              subtopics: ['interseccion de rectas', 'solucion aproximada'],
              skills: ['metodo-grafico', 'interpretacion'],
            },
            {
              title: 'Metodo de sustitucion (introduccion)',
              difficulty: 9,
              questionCount: 6,
              problemMix: 'mechanical',
              subtopics: ['sustitucion algebraica', 'orden logico'],
              skills: ['sustitucion', 'resolucion-sistemas'],
            },
            {
              title: 'Metodo de igualacion (introductorio)',
              difficulty: 9,
              questionCount: 6,
              problemMix: 'mechanical',
              subtopics: ['igualacion de expresiones', 'solucion exacta'],
              skills: ['igualacion', 'resolucion-sistemas'],
            },
            {
              title: 'Problemas verbales con sistemas',
              difficulty: 10,
              questionCount: 6,
              problemMix: 'contextualized',
              subtopics: ['mezclas', 'edades', 'precios', 'costos'],
              skills: ['modelacion-sistemas', 'contexto'],
            },
            {
              title: 'Integracion grafica y algebraica',
              difficulty: 10,
              questionCount: 6,
              problemMix: 'mixed',
              subtopics: ['grafico + algebraico', 'rectas paralelas y coincidentes'],
              skills: ['integracion-sistemas', 'analisis-soluciones'],
            },
          ],
        }),
      ],
    },
    {
      id: 'funciones-cuadraticas-introduccion',
      name: '3er Bimestre - Unidad 3: Introduccion a Funciones Cuadraticas',
      topics: [
        buildTopic({
          id: 'introduccion-funciones-cuadraticas',
          name: 'Introduccion a Funciones Cuadraticas',
          subtopics: [
            'Patrones cuadraticos',
            'Expresiones cuadraticas basicas (x^2)',
            'Funcion y = x^2',
            'Transformaciones y = ax^2',
            'Comparacion lineal vs cuadratica',
            'Area variable y modelacion geometrica',
            'Interpretacion grafica avanzada',
            'Integracion funcional avanzada',
          ],
          difficultyRange: [8, 10],
          problemMix: 'mixed',
          questionCountRange: [5, 6],
          lessons: [
            {
              title: 'Patrones cuadraticos',
              difficulty: 8,
              questionCount: 5,
              problemMix: 'mixed',
              subtopics: ['diferencias de segundo orden', 'crecimiento cuadratico'],
              skills: ['patrones-cuadraticos', 'no-linealidad'],
            },
            {
              title: 'Expresiones cuadraticas basicas (x^2)',
              difficulty: 8,
              questionCount: 6,
              problemMix: 'mechanical',
              subtopics: ['termino cuadratico', 'comparacion x vs x^2'],
              skills: ['x-cuadrado', 'evaluacion-cuadratica'],
            },
            {
              title: 'Funcion cuadratica de la forma y = x^2',
              difficulty: 9,
              questionCount: 6,
              problemMix: 'mixed',
              subtopics: ['tabla de valores', 'parabola basica', 'simetria'],
              skills: ['y-equals-x2', 'grafica-parabolica'],
            },
            {
              title: 'Transformaciones simples: y = ax^2',
              difficulty: 9,
              questionCount: 6,
              problemMix: 'mixed',
              subtopics: ['coeficiente a', 'apertura', 'orientacion'],
              skills: ['transformaciones-cuadraticas', 'coeficiente-a'],
            },
            {
              title: 'Comparacion entre funcion lineal y cuadratica',
              difficulty: 9,
              questionCount: 6,
              problemMix: 'contextualized',
              subtopics: ['crecimiento constante', 'crecimiento acelerado'],
              skills: ['lineal-vs-cuadratica', 'analisis-funcional'],
            },
            {
              title: 'Problemas geometricos con area variable',
              difficulty: 10,
              questionCount: 6,
              problemMix: 'contextualized',
              subtopics: ['area de cuadrado', 'modelacion geometrica'],
              skills: ['modelacion-area-cuadratica', 'contexto-geometrico'],
            },
            {
              title: 'Interpretacion grafica avanzada',
              difficulty: 10,
              questionCount: 6,
              problemMix: 'mixed',
              subtopics: ['vertice', 'simetria', 'creciente/decreciente'],
              skills: ['interpretacion-parabola', 'analisis-grafico'],
            },
            {
              title: 'Integracion funcional avanzada',
              difficulty: 10,
              questionCount: 6,
              problemMix: 'contextualized',
              subtopics: ['tabla', 'grafica', 'expresion', 'comparacion', 'modelacion'],
              skills: ['integracion-cuadratica', 'abstraccion-funcional'],
            },
          ],
        }),
      ],
    },
    {
      id: 'estadistica-probabilidad-analisis-datos',
      name: '3er Bimestre - Unidad 4: Estadistica y Analisis de Datos',
      topics: [
        buildTopic({
          id: 'estadistica-analisis-datos',
          name: 'Estadistica y Analisis de Datos',
          subtopics: [
            'Recoleccion y organizacion de datos',
            'Tablas de frecuencia',
            'Graficos estadisticos',
            'Media aritmetica',
            'Mediana y moda',
            'Rango y variabilidad',
            'Interpretacion critica de graficos',
            'Proyecto integrador estadistico',
          ],
          difficultyRange: [6, 10],
          problemMix: 'mixed',
          questionCountRange: [5, 6],
          lessons: [
            {
              title: 'Recoleccion y organizacion de datos',
              difficulty: 6,
              questionCount: 5,
              problemMix: 'contextualized',
              subtopics: ['variables', 'datos cuantitativos y cualitativos', 'tablas simples'],
              skills: ['organizacion-datos', 'clasificacion'],
            },
            {
              title: 'Tablas de frecuencia',
              difficulty: 7,
              questionCount: 6,
              problemMix: 'mixed',
              subtopics: ['frecuencia absoluta', 'frecuencia relativa'],
              skills: ['tabla-frecuencia', 'calculo-frecuencias'],
            },
            {
              title: 'Graficos estadisticos',
              difficulty: 7,
              questionCount: 6,
              problemMix: 'mixed',
              subtopics: ['barras', 'circular', 'lineal'],
              skills: ['representacion-grafica-datos', 'seleccion-grafico'],
            },
            {
              title: 'Media aritmetica',
              difficulty: 8,
              questionCount: 6,
              problemMix: 'mixed',
              subtopics: ['promedio', 'tendencia central'],
              skills: ['media', 'interpretacion-promedio'],
            },
            {
              title: 'Mediana y moda',
              difficulty: 8,
              questionCount: 6,
              problemMix: 'mixed',
              subtopics: ['mediana', 'moda', 'comparacion de medidas'],
              skills: ['mediana-moda', 'analisis-central'],
            },
            {
              title: 'Rango y variabilidad',
              difficulty: 9,
              questionCount: 6,
              problemMix: 'contextualized',
              subtopics: ['rango', 'dispersion', 'comparacion de conjuntos'],
              skills: ['rango', 'variabilidad'],
            },
            {
              title: 'Interpretacion critica de graficos',
              difficulty: 9,
              questionCount: 6,
              problemMix: 'contextualized',
              subtopics: ['escalas enganosas', 'errores de interpretacion'],
              skills: ['lectura-critica-graficos', 'validacion-estadistica'],
            },
            {
              title: 'Proyecto integrador estadistico',
              difficulty: 10,
              questionCount: 6,
              problemMix: 'contextualized',
              subtopics: ['organizacion', 'representacion', 'media/mediana/moda', 'rango', 'argumentacion'],
              skills: ['integracion-estadistica', 'toma-decisiones'],
            },
          ],
        }),
      ],
    },
    {
      id: 'algebra-inecuaciones-restricciones',
      name: '4to Bimestre - Unidad 1: Inecuaciones Lineales y Modelacion con Restricciones',
      topics: [
        buildTopic({
          id: 'inecuaciones-modelacion-restricciones',
          name: 'Inecuaciones Lineales y Modelacion con Restricciones',
          subtopics: [
            'Concepto de desigualdad algebraica',
            'Resolucion de inecuaciones simples',
            'Cambio de sentido por multiplicacion negativa',
            'Representacion en recta numerica',
            'Inecuaciones con parentesis y distributiva',
            'Problemas verbales con restricciones',
            'Sistemas simples de inecuaciones',
            'Integracion avanzada con modelacion',
          ],
          difficultyRange: [7, 10],
          problemMix: 'mixed',
          questionCountRange: [5, 6],
          lessons: [
            {
              title: 'Concepto de desigualdad algebraica',
              difficulty: 7,
              questionCount: 5,
              problemMix: 'mixed',
              subtopics: ['simbolos < > <= >=', 'conjunto solucion'],
              skills: ['desigualdades', 'formulacion-inecuaciones'],
            },
            {
              title: 'Resolucion de inecuaciones simples (x + a > b)',
              difficulty: 8,
              questionCount: 6,
              problemMix: 'mechanical',
              subtopics: ['operaciones inversas', 'aislamiento de variable'],
              skills: ['inecuacion-simple', 'operaciones-inversas'],
            },
            {
              title: 'Inecuaciones con multiplicacion y cambio de sentido',
              difficulty: 8,
              questionCount: 6,
              problemMix: 'mechanical',
              subtopics: ['numero negativo', 'cambio de desigualdad'],
              skills: ['cambio-sentido', 'regla-negativo'],
            },
            {
              title: 'Representacion en recta numerica',
              difficulty: 8,
              questionCount: 6,
              problemMix: 'mixed',
              subtopics: ['intervalos', 'punto abierto y cerrado'],
              skills: ['recta-numerica-inecuaciones', 'interpretacion-grafica'],
            },
            {
              title: 'Inecuaciones con parentesis y distributiva',
              difficulty: 9,
              questionCount: 6,
              problemMix: 'mechanical',
              subtopics: ['distributiva', 'reduccion de terminos'],
              skills: ['inecuaciones-distributiva', 'estructura-algebraica'],
            },
            {
              title: 'Problemas verbales con restricciones',
              difficulty: 9,
              questionCount: 6,
              problemMix: 'contextualized',
              subtopics: ['presupuesto maximo', 'cantidad minima', 'capacidad'],
              skills: ['modelacion-restricciones', 'contexto'],
            },
            {
              title: 'Sistemas simples de inecuaciones',
              difficulty: 10,
              questionCount: 6,
              problemMix: 'mixed',
              subtopics: ['interseccion de soluciones', 'rango comun'],
              skills: ['sistema-inecuaciones', 'interseccion-intervalos'],
            },
            {
              title: 'Integracion avanzada con modelacion',
              difficulty: 10,
              questionCount: 6,
              problemMix: 'contextualized',
              subtopics: ['inecuaciones', 'funciones lineales', 'restricciones reales', 'interpretacion grafica'],
              skills: ['integracion-inecuaciones', 'analisis-completo'],
            },
          ],
        }),
      ],
    },
    {
      id: 'geometria-analitica-inicial',
      name: '4to Bimestre - Unidad 2: Geometria Analitica Inicial',
      topics: [
        buildTopic({
          id: 'geometria-analitica-inicial',
          name: 'Geometria Analitica Inicial',
          subtopics: [
            'Distancia entre dos puntos',
            'Punto medio de un segmento',
            'Pendiente como razon geometrica',
            'Ecuacion basica de la recta y = mx + b',
            'Rectas paralelas y perpendiculares',
            'Interpretacion geometrica de sistemas',
            'Aplicaciones espaciales',
            'Integracion algebra-geometrica avanzada',
          ],
          difficultyRange: [8, 10],
          problemMix: 'mixed',
          questionCountRange: [6, 6],
          lessons: [
            {
              title: 'Distancia entre dos puntos',
              difficulty: 8,
              questionCount: 6,
              problemMix: 'mixed',
              subtopics: ['diferencia de coordenadas', 'distancia en ejes paralelos'],
              skills: ['distancia-puntos', 'plano-cartesiano'],
            },
            {
              title: 'Punto medio de un segmento',
              difficulty: 8,
              questionCount: 6,
              problemMix: 'mechanical',
              subtopics: ['promedio de coordenadas', 'interpretacion geometrica'],
              skills: ['punto-medio', 'segmentos'],
            },
            {
              title: 'Pendiente como razon geometrica',
              difficulty: 8,
              questionCount: 6,
              problemMix: 'mixed',
              subtopics: ['cambio vertical/horizontal', 'crecimiento'],
              skills: ['pendiente-geometrica', 'razon-cambio'],
            },
            {
              title: 'Ecuacion basica de la recta (y = mx + b)',
              difficulty: 9,
              questionCount: 6,
              problemMix: 'mixed',
              subtopics: ['pendiente', 'intercepto', 'construccion de recta'],
              skills: ['ecuacion-recta', 'forma-mx-b'],
            },
            {
              title: 'Rectas paralelas y perpendiculares',
              difficulty: 9,
              questionCount: 6,
              problemMix: 'mechanical',
              subtopics: ['misma pendiente', 'pendiente reciproca negativa'],
              skills: ['paralelas-perpendiculares', 'analisis-pendiente'],
            },
            {
              title: 'Interpretacion geometrica de sistemas',
              difficulty: 9,
              questionCount: 6,
              problemMix: 'mixed',
              subtopics: ['interseccion de rectas', 'solucion de sistema'],
              skills: ['sistemas-geometria', 'conexion-algebra-grafica'],
            },
            {
              title: 'Aplicaciones espaciales',
              difficulty: 10,
              questionCount: 6,
              problemMix: 'contextualized',
              subtopics: ['trayectorias', 'comparacion de pendientes', 'interseccion real'],
              skills: ['modelacion-espacial', 'rectas-en-contexto'],
            },
            {
              title: 'Integracion algebra-geometrica avanzada',
              difficulty: 10,
              questionCount: 6,
              problemMix: 'contextualized',
              subtopics: ['pendiente', 'punto medio', 'ecuacion de recta', 'sistemas', 'restricciones'],
              skills: ['integracion-analitica', 'desafio-elite'],
            },
          ],
        }),
      ],
    },
    {
      id: 'probabilidad-conteo-inicial',
      name: '4to Bimestre - Unidad 3: Probabilidad y Conteo Inicial',
      topics: [
        buildTopic({
          id: 'probabilidad-conteo-inicial',
          name: 'Probabilidad y Conteo Inicial',
          subtopics: [
            'Experimentos aleatorios',
            'Espacio muestral',
            'Probabilidad clasica',
            'Eventos simples y compuestos',
            'Regla basica de conteo',
            'Diagramas de arbol',
            'Probabilidad en contextos reales',
            'Integracion probabilistica avanzada',
          ],
          difficultyRange: [7, 10],
          problemMix: 'mixed',
          questionCountRange: [5, 6],
          lessons: [
            {
              title: 'Experimentos aleatorios',
              difficulty: 7,
              questionCount: 5,
              problemMix: 'mixed',
              subtopics: ['determinista vs aleatorio', 'resultados posibles'],
              skills: ['experimento-aleatorio', 'identificacion-eventos'],
            },
            {
              title: 'Espacio muestral',
              difficulty: 8,
              questionCount: 6,
              problemMix: 'mechanical',
              subtopics: ['conjunto de resultados', 'construccion de espacio muestral'],
              skills: ['espacio-muestral', 'enumeracion'],
            },
            {
              title: 'Probabilidad clasica',
              difficulty: 8,
              questionCount: 6,
              problemMix: 'mechanical',
              subtopics: ['casos favorables', 'casos posibles', 'equiprobabilidad'],
              skills: ['probabilidad-clasica', 'calculo-basico'],
            },
            {
              title: 'Eventos simples y compuestos',
              difficulty: 8,
              questionCount: 6,
              problemMix: 'mixed',
              subtopics: ['union', 'interseccion', 'evento simple'],
              skills: ['eventos-compuestos', 'interpretacion'],
            },
            {
              title: 'Regla basica de conteo',
              difficulty: 9,
              questionCount: 6,
              problemMix: 'mechanical',
              subtopics: ['principio multiplicativo', 'conteo estructural'],
              skills: ['conteo-multiplicativo', 'combinacion-etapas'],
            },
            {
              title: 'Diagramas de arbol',
              difficulty: 9,
              questionCount: 6,
              problemMix: 'mixed',
              subtopics: ['eventos consecutivos', 'visualizacion de posibilidades'],
              skills: ['diagrama-arbol', 'analisis-probabilistico'],
            },
            {
              title: 'Probabilidad en contextos reales',
              difficulty: 10,
              questionCount: 6,
              problemMix: 'contextualized',
              subtopics: ['juegos', 'riesgo', 'seleccion al azar', 'comparacion'],
              skills: ['probabilidad-aplicada', 'toma-decisiones'],
            },
            {
              title: 'Integracion probabilistica avanzada',
              difficulty: 10,
              questionCount: 6,
              problemMix: 'contextualized',
              subtopics: ['espacio muestral', 'conteo', 'eventos compuestos', 'interpretacion'],
              skills: ['integracion-probabilidad', 'desafio-elite'],
            },
          ],
        }),
      ],
    },
    {
      id: 'proyecto-integrador-matematico',
      name: '4to Bimestre - Unidad 4: Proyecto Integrador Matematico (Nivel Elite)',
      topics: [
        buildTopic({
          id: 'proyecto-integrador-matematico',
          name: 'Proyecto Integrador Matematico',
          subtopics: [
            'Modelacion algebraica multietapa',
            'Integracion de funciones lineales',
            'Sistemas aplicados en contexto real',
            'Restricciones con inecuaciones',
            'Integracion geometrica avanzada',
            'Analisis probabilistico aplicado',
            'Proyecto aplicado integral',
            'Evaluacion integradora final',
          ],
          difficultyRange: [9, 10],
          problemMix: 'contextualized',
          questionCountRange: [6, 6],
          lessons: [
            {
              title: 'Modelacion algebraica multietapa',
              difficulty: 9,
              questionCount: 6,
              problemMix: 'contextualized',
              subtopics: ['ecuaciones', 'interpretacion', 'verificacion'],
              skills: ['modelacion-multietapa', 'coherencia'],
            },
            {
              title: 'Integracion de funciones lineales',
              difficulty: 9,
              questionCount: 6,
              problemMix: 'contextualized',
              subtopics: ['pendiente', 'intercepto', 'comparacion de funciones'],
              skills: ['funciones-integradas', 'analisis-lineal'],
            },
            {
              title: 'Sistemas aplicados en contexto real',
              difficulty: 10,
              questionCount: 6,
              problemMix: 'contextualized',
              subtopics: ['dos condiciones simultaneas', 'decision'],
              skills: ['sistemas-contexto-real', 'modelacion'],
            },
            {
              title: 'Restricciones con inecuaciones',
              difficulty: 10,
              questionCount: 6,
              problemMix: 'contextualized',
              subtopics: ['presupuestos', 'minimos', 'maximos', 'interseccion'],
              skills: ['inecuaciones-restricciones', 'optimizacion-basica'],
            },
            {
              title: 'Integracion geometrica avanzada',
              difficulty: 10,
              questionCount: 6,
              problemMix: 'contextualized',
              subtopics: ['pendiente', 'punto medio', 'ecuacion de recta'],
              skills: ['integracion-algebra-geometria', 'estructura-espacial'],
            },
            {
              title: 'Analisis probabilistico aplicado',
              difficulty: 10,
              questionCount: 6,
              problemMix: 'contextualized',
              subtopics: ['espacio muestral', 'conteo', 'eventos compuestos'],
              skills: ['probabilidad-aplicada', 'analisis-riesgo'],
            },
            {
              title: 'Proyecto aplicado integral',
              difficulty: 10,
              questionCount: 6,
              problemMix: 'contextualized',
              subtopics: ['plan', 'optimizacion', 'decision basada en datos'],
              skills: ['proyecto-integral', 'integracion-matematica'],
            },
            {
              title: 'Evaluacion integradora final',
              difficulty: 10,
              questionCount: 6,
              problemMix: 'contextualized',
              subtopics: ['razonamiento profundo', 'integracion total'],
              skills: ['dominio-anual', 'elite-total'],
            },
          ],
        }),
      ],
    },
  ],
  finalExam: {
    id: 'grade-1-annual-final-elite',
    name: 'Examen Final Anual Integrado Elite - 1ro Secundaria',
    questionRange: [52, 52],
    passingScore: 0.75,
    xpMultiplier: 3,
    aiHelpAllowed: false,
    sections: [
      {
        id: 'parte-i-algebra-avanzada',
        name: 'Parte I - Algebra Avanzada',
        count: 18,
        topicIds: [
          'ecuaciones-lineales-primer-grado',
          'sistemas-ecuaciones-lineales-introduccion',
          'inecuaciones-modelacion-restricciones',
        ],
      },
      {
        id: 'parte-ii-funciones-geometria-analitica',
        name: 'Parte II - Funciones y Geometria Analitica',
        count: 12,
        topicIds: ['relaciones-funciones-lineales-iniciales', 'geometria-analitica-inicial'],
      },
      {
        id: 'parte-iii-expresiones-factorizacion',
        name: 'Parte III - Expresiones y Factorizacion',
        count: 6,
        topicIds: ['productos-notables-completos', 'factorizacion-completa'],
      },
      {
        id: 'parte-iv-estadistica-probabilidad',
        name: 'Parte IV - Estadistica y Probabilidad',
        count: 10,
        topicIds: ['estadistica-analisis-datos', 'probabilidad-conteo-inicial'],
      },
      {
        id: 'parte-v-integracion-total-elite',
        name: 'Parte V - Integracion Total Elite',
        count: 6,
        topicIds: ['proyecto-integrador-matematico'],
      },
    ],
    distribution: [
      { topicId: 'ecuaciones-lineales-primer-grado', count: 2, difficultyRange: [8, 8] },
      { topicId: 'ecuaciones-lineales-primer-grado', count: 2, difficultyRange: [9, 9] },
      { topicId: 'ecuaciones-lineales-primer-grado', count: 2, difficultyRange: [10, 10] },

      { topicId: 'sistemas-ecuaciones-lineales-introduccion', count: 2, difficultyRange: [8, 8] },
      { topicId: 'sistemas-ecuaciones-lineales-introduccion', count: 2, difficultyRange: [9, 9] },
      { topicId: 'sistemas-ecuaciones-lineales-introduccion', count: 2, difficultyRange: [10, 10] },

      { topicId: 'inecuaciones-modelacion-restricciones', count: 2, difficultyRange: [8, 8] },
      { topicId: 'inecuaciones-modelacion-restricciones', count: 2, difficultyRange: [9, 9] },
      { topicId: 'inecuaciones-modelacion-restricciones', count: 2, difficultyRange: [10, 10] },

      { topicId: 'relaciones-funciones-lineales-iniciales', count: 2, difficultyRange: [8, 8] },
      { topicId: 'relaciones-funciones-lineales-iniciales', count: 2, difficultyRange: [9, 9] },
      { topicId: 'relaciones-funciones-lineales-iniciales', count: 2, difficultyRange: [10, 10] },

      { topicId: 'geometria-analitica-inicial', count: 2, difficultyRange: [8, 8] },
      { topicId: 'geometria-analitica-inicial', count: 2, difficultyRange: [9, 9] },
      { topicId: 'geometria-analitica-inicial', count: 2, difficultyRange: [10, 10] },

      { topicId: 'productos-notables-completos', count: 3, difficultyRange: [9, 10] },
      { topicId: 'factorizacion-completa', count: 3, difficultyRange: [9, 10] },

      { topicId: 'estadistica-analisis-datos', count: 2, difficultyRange: [8, 8] },
      { topicId: 'estadistica-analisis-datos', count: 2, difficultyRange: [9, 9] },
      { topicId: 'estadistica-analisis-datos', count: 1, difficultyRange: [10, 10] },

      { topicId: 'probabilidad-conteo-inicial', count: 2, difficultyRange: [8, 8] },
      { topicId: 'probabilidad-conteo-inicial', count: 2, difficultyRange: [9, 9] },
      { topicId: 'probabilidad-conteo-inicial', count: 1, difficultyRange: [10, 10] },

      { topicId: 'proyecto-integrador-matematico', count: 6, difficultyRange: [10, 10] },
    ],
    mixDistribution: [
      { mix: 'contextualized', count: 32 },
      { mix: 'mechanical', count: 14 },
      { mix: 'advanced-modeling', count: 6 },
    ],
    metadata: {
      questionBank: {
        total: 280,
        sourceEvaluations: ['bimestre-1', 'bimestre-2', 'bimestre-3', 'bimestre-4'],
        byDomain: [
          { domainId: 'algebra-avanzada', count: 80 },
          { domainId: 'funciones-geometria-analitica', count: 60 },
          { domainId: 'expresiones-factorizacion', count: 40 },
          { domainId: 'estadistica-probabilidad', count: 50 },
          { domainId: 'integracion-total', count: 50 },
        ],
      },
      performanceBands: [
        { label: 'Basico', minScore: 0, maxScore: 0.5999 },
        { label: 'Competente', minScore: 0.6, maxScore: 0.7499 },
        { label: 'Avanzado', minScore: 0.75, maxScore: 0.8999 },
        { label: 'Elite', minScore: 0.9, maxScore: 1 },
      ],
      annualFocus: 'Integracion total con dificultad elevada',
    },
  },
}

export default grade1
