import { createLesson } from '../core/shared.js'

const buildTopic = ({
  id,
  name,
  subtopics = [],
  difficultyRange = [8, 10],
  problemMix = 'mixed',
  questionCountRange = [5, 6],
  lessons = [],
}) => ({
  id,
  name,
  subtopics,
  difficultyRange,
  problemMix,
  questionCountRange,
  lessons: lessons.map((lesson, index) =>
    createLesson({
      topicId: id,
      index: index + 1,
      ...lesson,
      problemMix: lesson.problemMix || problemMix,
      subtopics: lesson.subtopics || [],
    }),
  ),
})

const grade4 = {
  id: 'grade-4',
  gradeNumber: 4,
  name: '4to Secundaria - Matematica (Alto Rendimiento)',
  objective:
    'Consolidar fundamentos algebraicos superiores para funciones cuadraticas, sistemas mas complejos y razonamiento algebraico avanzado.',
  areas: [
    {
      id: 'algebra-superior-i-bimestre',
      name: 'I Bimestre - Fundamentos Algebraicos Superiores',
      topics: [
        buildTopic({
          id: 'algebra-estructural-avanzada',
          name: 'Unidad 1 - Algebra Estructural Avanzada',
          subtopics: [
            'Simplificacion algebraica avanzada',
            'Productos notables',
            'Factorizacion avanzada',
            'Ecuaciones cuadraticas',
            'Modelacion con segundo grado',
          ],
          difficultyRange: [8, 10],
          problemMix: 'mixed',
          questionCountRange: [5, 6],
          lessons: [
            {
              title: 'Simplificacion algebraica avanzada',
              difficulty: 8,
              questionCount: 5,
              subtopics: ['multiples parentesis', 'terminos semejantes', 'manejo de signos'],
              skills: ['simplificacion-avanzada', 'terminos-semejantes', 'control-signos'],
            },
            {
              title: 'Productos notables basicos estructurados',
              difficulty: 8,
              questionCount: 5,
              subtopics: ['cuadrado de binomio', 'binomios conjugados', 'patrones algebraicos'],
              skills: ['productos-notables', 'expansion', 'patrones'],
            },
            {
              title: 'Productos notables con coeficientes',
              difficulty: 9,
              questionCount: 5,
              subtopics: ['binomios con coeficientes', 'expansiones complejas'],
              skills: ['productos-con-coeficientes', 'expansion-avanzada'],
            },
            {
              title: 'Factorizacion por factor comun y agrupacion',
              difficulty: 9,
              questionCount: 5,
              subtopics: ['factor comun', 'agrupacion estrategica'],
              skills: ['factor-comun', 'agrupacion', 'reorganizacion'],
            },
            {
              title: 'Diferencia de cuadrados y estructuras derivadas',
              difficulty: 8,
              questionCount: 5,
              subtopics: ['diferencia de cuadrados', 'integracion con simplificacion'],
              skills: ['diferencia-cuadrados', 'factorizacion'],
            },
            {
              title: 'Trinomio cuadrado perfecto',
              difficulty: 9,
              questionCount: 5,
              subtopics: ['patron cuadratico perfecto', 'verificacion estructural'],
              skills: ['trinomio-cuadrado-perfecto', 'factorizacion'],
            },
            {
              title: 'Trinomios de la forma x^2 + bx + c',
              difficulty: 9,
              questionCount: 5,
              subtopics: ['suma-producto', 'busqueda de factores'],
              skills: ['trinomio-simple', 'factorizacion'],
            },
            {
              title: 'Trinomios de la forma ax^2 + bx + c',
              difficulty: 10,
              questionCount: 6,
              subtopics: ['metodo AC', 'descomposicion del termino central'],
              skills: ['trinomio-general', 'metodo-ac', 'agrupacion'],
            },
            {
              title: 'Ecuaciones cuadraticas por factorizacion',
              difficulty: 10,
              questionCount: 6,
              subtopics: ['igualacion a cero', 'soluciones reales'],
              skills: ['ecuaciones-cuadraticas', 'factorizacion', 'analisis-raices'],
            },
            {
              title: 'Ecuaciones cuadraticas contextualizadas',
              difficulty: 10,
              questionCount: 6,
              problemMix: 'contextualized',
              subtopics: ['modelacion', 'interpretacion de raices'],
              skills: ['modelacion-cuadratica', 'interpretacion'],
            },
            {
              title: 'Integracion algebraica avanzada',
              difficulty: 10,
              questionCount: 6,
              subtopics: ['productos combinados', 'factorizacion multiple', 'ecuaciones encadenadas'],
              skills: ['integracion-algebraica', 'resolucion-multietapa'],
            },
            {
              title: 'Evaluacion estructural de la unidad',
              type: 'exam',
              difficulty: 10,
              questionCount: 10,
              subtopics: ['integracion total de metodos'],
              skills: ['evaluacion-unidad', 'dominio-integral'],
            },
          ],
        }),
        buildTopic({
          id: 'racionalizacion-expresiones-fraccionarias',
          name: 'Unidad 2 - Racionalizacion y Expresiones Algebraicas Fraccionarias',
          subtopics: [
            'Fracciones algebraicas',
            'Restricciones del dominio',
            'Racionalizacion',
            'Ecuaciones fraccionarias',
            'Modelacion racional',
          ],
          difficultyRange: [8, 10],
          problemMix: 'mixed',
          questionCountRange: [5, 6],
          lessons: [
            {
              title: 'Fracciones algebraicas basicas',
              difficulty: 8,
              questionCount: 5,
              subtopics: ['numerador y denominador algebraico', 'restricciones del dominio'],
              skills: ['fracciones-algebraicas', 'dominio'],
            },
            {
              title: 'Simplificacion por factorizacion',
              difficulty: 9,
              questionCount: 5,
              subtopics: ['factorizacion de numerador y denominador', 'cancelacion correcta'],
              skills: ['simplificacion-racional', 'factorizacion'],
            },
            {
              title: 'Multiplicacion y division de fracciones algebraicas',
              difficulty: 8,
              questionCount: 5,
              subtopics: ['producto directo', 'inverso multiplicativo'],
              skills: ['multiplicacion-racional', 'division-racional'],
            },
            {
              title: 'Suma y resta con igual denominador',
              difficulty: 8,
              questionCount: 5,
              subtopics: ['operaciones directas', 'reduccion posterior'],
              skills: ['suma-racional', 'resta-racional'],
            },
            {
              title: 'Suma y resta con distinto denominador',
              difficulty: 9,
              questionCount: 5,
              subtopics: ['mcd algebraico', 'factorizacion previa'],
              skills: ['mcd-racional', 'suma-resta-racional'],
            },
            {
              title: 'Expresiones racionales compuestas',
              difficulty: 9,
              questionCount: 5,
              subtopics: ['fracciones dentro de fracciones', 'multiplicacion cruzada'],
              skills: ['racional-compuesta', 'reorganizacion'],
            },
            {
              title: 'Racionalizacion con una raiz en el denominador',
              difficulty: 9,
              questionCount: 5,
              subtopics: ['eliminacion de raiz simple', 'radical adecuado'],
              skills: ['racionalizacion-simple', 'radicales'],
            },
            {
              title: 'Racionalizacion con binomio conjugado',
              difficulty: 10,
              questionCount: 6,
              subtopics: ['conjugados', 'diferencia de cuadrados'],
              skills: ['racionalizacion-conjugado', 'diferencia-cuadrados'],
            },
            {
              title: 'Ecuaciones fraccionarias basicas',
              difficulty: 9,
              questionCount: 5,
              subtopics: ['mcd', 'eliminacion de denominadores', 'verificacion de restricciones'],
              skills: ['ecuacion-fraccionaria', 'dominio'],
            },
            {
              title: 'Ecuaciones fraccionarias avanzadas',
              difficulty: 10,
              questionCount: 6,
              subtopics: ['multiples fracciones', 'soluciones invalidas'],
              skills: ['ecuacion-racional-avanzada', 'analisis-soluciones'],
            },
            {
              title: 'Modelacion con expresiones racionales',
              difficulty: 10,
              questionCount: 6,
              problemMix: 'contextualized',
              subtopics: ['velocidad', 'trabajo conjunto', 'proporcionalidad racional'],
              skills: ['modelacion-racional', 'aplicaciones'],
            },
            {
              title: 'Integracion racional avanzada',
              type: 'exam',
              difficulty: 10,
              questionCount: 10,
              subtopics: ['operaciones combinadas', 'racionalizacion', 'ecuaciones fraccionarias'],
              skills: ['evaluacion-racional', 'dominio-completo'],
            },
          ],
        }),
        buildTopic({
          id: 'sistemas-lineales-modelacion-avanzada',
          name: 'Unidad 3 - Sistemas Lineales y Modelacion Avanzada',
          subtopics: [
            'Resolucion estructural de sistemas',
            'Interpretacion geometrica',
            'Sistemas con parametros',
            'Modelacion con restricciones',
            'Sistemas no lineales basicos',
          ],
          difficultyRange: [9, 10],
          problemMix: 'mixed',
          questionCountRange: [5, 6],
          lessons: [
            {
              title: 'Repaso estructural de ecuaciones lineales',
              difficulty: 9,
              questionCount: 5,
              subtopics: ['variables en ambos lados', 'simplificacion previa'],
              skills: ['ecuaciones-lineales', 'estructura'],
            },
            {
              title: 'Sistemas por metodo de sustitucion',
              difficulty: 9,
              questionCount: 5,
              subtopics: ['despeje', 'sustitucion ordenada'],
              skills: ['sistemas', 'sustitucion'],
            },
            {
              title: 'Sistemas por metodo de eliminacion',
              difficulty: 9,
              questionCount: 5,
              subtopics: ['eliminacion de variable', 'simplificacion'],
              skills: ['sistemas', 'eliminacion'],
            },
            {
              title: 'Sistemas con coeficientes negativos y fraccionarios',
              difficulty: 9,
              questionCount: 5,
              subtopics: ['manejo de signos', 'fracciones'],
              skills: ['sistemas-complejos', 'control-signos'],
            },
            {
              title: 'Interpretacion geometrica de sistemas',
              difficulty: 9,
              questionCount: 5,
              subtopics: ['interseccion de rectas', 'compatibilidad'],
              skills: ['interpretacion-geometrica', 'sistemas-lineales'],
            },
            {
              title: 'Sistemas dependientes e independientes',
              difficulty: 9,
              questionCount: 5,
              subtopics: ['infinitas soluciones', 'sin solucion'],
              skills: ['clasificacion-sistemas', 'analisis'],
            },
            {
              title: 'Sistemas aplicados en contexto real',
              difficulty: 10,
              questionCount: 6,
              problemMix: 'contextualized',
              subtopics: ['produccion y costos', 'movimiento', 'mezcla'],
              skills: ['modelacion-sistemas', 'contexto'],
            },
            {
              title: 'Sistemas con parametros',
              difficulty: 10,
              questionCount: 6,
              subtopics: ['condiciones de existencia', 'analisis de parametros'],
              skills: ['parametros', 'condiciones-solucion'],
            },
            {
              title: 'Modelacion con restricciones multiples',
              difficulty: 10,
              questionCount: 6,
              problemMix: 'contextualized',
              subtopics: ['sistemas con inecuaciones', 'region solucion'],
              skills: ['restricciones', 'region-factible'],
            },
            {
              title: 'Sistemas no lineales basicos',
              difficulty: 10,
              questionCount: 6,
              subtopics: ['sistema lineal-cuadratico', 'multiples soluciones'],
              skills: ['sistemas-mixtos', 'sustitucion'],
            },
            {
              title: 'Optimizacion basica con sistemas',
              difficulty: 10,
              questionCount: 6,
              subtopics: ['interpretacion grafica', 'decision optima'],
              skills: ['optimizacion-basica', 'toma-decisiones'],
            },
            {
              title: 'Integracion avanzada de sistemas',
              type: 'exam',
              difficulty: 10,
              questionCount: 10,
              subtopics: ['parametros', 'restricciones', 'modelacion multietapa'],
              skills: ['evaluacion-sistemas', 'integracion-total'],
            },
          ],
        }),
      ],
    },
  ],
  finalExam: {
    id: 'grade-4-final-exam',
    name: 'Examen Final 4to Secundaria - Fundamentos Algebraicos Superiores',
    questionRange: [50, 60],
    passingScore: 0.75,
    xpMultiplier: 2,
    aiHelpAllowed: false,
    distribution: [
      { topicId: 'algebra-estructural-avanzada', count: 18, difficultyRange: [8, 10] },
      { topicId: 'racionalizacion-expresiones-fraccionarias', count: 18, difficultyRange: [8, 10] },
      { topicId: 'sistemas-lineales-modelacion-avanzada', count: 18, difficultyRange: [9, 10] },
    ],
  },
}

export default grade4
