INSERT INTO math_skills (id, name, description, domain, difficulty_level, mastery_threshold, xp_reward) VALUES
('arith_counting_objects_to_20', 'Counting Objects to 20', 'Count concrete objects and quantities from 0 to 20.', 'arithmetic', 1, 64, 10),
('arith_counting_to_100', 'Counting to 100', 'Count forward and backward up to 100.', 'arithmetic', 1, 65, 11),
('arith_number_line_basics', 'Number Line Basics', 'Locate and interpret whole numbers on a number line.', 'arithmetic', 1, 65, 11),
('arith_place_value_tens', 'Place Value to Tens', 'Represent numbers using ones and tens.', 'arithmetic', 1, 66, 12),
('arith_place_value_hundreds', 'Place Value to Hundreds', 'Read, write, and decompose numbers to hundreds.', 'arithmetic', 1, 66, 12),
('arith_place_value_thousands', 'Place Value to Thousands', 'Read, write, and decompose numbers to thousands.', 'arithmetic', 2, 67, 13),
('arith_compare_whole_numbers', 'Compare Whole Numbers', 'Compare whole numbers using <, >, and =.', 'arithmetic', 1, 66, 12),
('arith_order_whole_numbers', 'Order Whole Numbers', 'Order lists of whole numbers ascending and descending.', 'arithmetic', 2, 67, 13),
('arith_round_whole_numbers', 'Round Whole Numbers', 'Round whole numbers to tens, hundreds, and thousands.', 'arithmetic', 2, 68, 14),
('arith_even_odd_patterns', 'Even and Odd Patterns', 'Identify even/odd numbers and simple parity patterns.', 'arithmetic', 2, 67, 13),
('arith_factors_multiples_intro', 'Factors and Multiples Intro', 'Find factors and multiples of whole numbers.', 'arithmetic', 2, 68, 14),
('arith_divisibility_rules', 'Divisibility Rules', 'Use divisibility rules for 2, 3, 5, 9, and 10.', 'arithmetic', 3, 70, 16),
('arith_addition_within_20', 'Addition Within 20', 'Add whole numbers within 20 accurately.', 'arithmetic', 1, 65, 12),
('arith_addition_multi_digit', 'Multi-digit Addition', 'Add multi-digit whole numbers with regrouping.', 'arithmetic', 2, 67, 14),
('arith_subtraction_within_20', 'Subtraction Within 20', 'Subtract whole numbers within 20 accurately.', 'arithmetic', 1, 65, 12),
('arith_subtraction_multi_digit', 'Multi-digit Subtraction', 'Subtract multi-digit whole numbers with regrouping.', 'arithmetic', 2, 67, 14),
('arith_multiplication_as_repeated_addition', 'Multiplication as Repeated Addition', 'Interpret multiplication as equal groups and repeated addition.', 'arithmetic', 2, 68, 15),
('arith_multiplication_facts', 'Multiplication Facts', 'Recall multiplication facts fluently.', 'arithmetic', 2, 69, 15),
('arith_multi_digit_multiplication', 'Multi-digit Multiplication', 'Multiply multi-digit numbers using standard algorithms.', 'arithmetic', 3, 71, 18),
('arith_division_as_sharing', 'Division as Sharing', 'Interpret division as sharing and grouping.', 'arithmetic', 2, 69, 15),
('arith_division_facts', 'Division Facts', 'Recall division facts fluently.', 'arithmetic', 3, 70, 16),
('arith_long_division', 'Long Division', 'Divide multi-digit numbers using long division.', 'arithmetic', 3, 72, 18),
('arith_inverse_operations', 'Inverse Operations', 'Use inverse relationships between operations to solve checks.', 'arithmetic', 3, 70, 16),
('arith_order_of_operations_basic', 'Order of Operations Basic', 'Evaluate expressions using operation priority without exponents.', 'arithmetic', 3, 72, 18),
('arith_order_of_operations_grouping', 'Order of Operations with Grouping', 'Evaluate grouped expressions with parentheses and brackets.', 'arithmetic', 4, 74, 20),
('arith_integer_number_line', 'Integer Number Line', 'Represent positive and negative integers on the number line.', 'arithmetic', 3, 70, 16),
('arith_compare_order_integers', 'Compare and Order Integers', 'Compare and order integers including negatives.', 'arithmetic', 3, 71, 17),
('arith_absolute_value', 'Absolute Value', 'Interpret and compute absolute value as distance from zero.', 'arithmetic', 3, 71, 17),
('arith_add_integers', 'Add Integers', 'Add positive and negative integers correctly.', 'arithmetic', 4, 74, 20),
('arith_subtract_integers', 'Subtract Integers', 'Subtract integers using sign rules and number line logic.', 'arithmetic', 4, 75, 20),
('arith_multiply_integers', 'Multiply Integers', 'Multiply integers using sign rules.', 'arithmetic', 4, 75, 21),
('arith_divide_integers', 'Divide Integers', 'Divide integers using sign rules.', 'arithmetic', 4, 76, 21),
('arith_integer_multi_step_expressions', 'Integer Multi-step Expressions', 'Solve multi-step arithmetic expressions with integers.', 'arithmetic', 5, 78, 24),
('arith_fraction_part_of_whole', 'Fractions as Part of a Whole', 'Interpret fractions as parts of equal wholes.', 'arithmetic', 2, 68, 15),
('arith_equivalent_fractions', 'Equivalent Fractions', 'Generate and recognize equivalent fractions.', 'arithmetic', 3, 71, 17),
('arith_simplify_fractions', 'Simplifying Fractions', 'Reduce fractions to simplest form using GCD ideas.', 'arithmetic', 3, 72, 18),
('arith_compare_order_fractions', 'Compare and Order Fractions', 'Compare and order fractions using common strategies.', 'arithmetic', 3, 72, 18),
('arith_add_subtract_fractions_like_den', 'Add/Subtract Fractions (Like Denominators)', 'Add and subtract fractions with equal denominators.', 'arithmetic', 3, 72, 18),
('arith_add_subtract_fractions_unlike_den', 'Add/Subtract Fractions (Unlike Denominators)', 'Add and subtract fractions with different denominators.', 'arithmetic', 4, 75, 21),
('arith_multiply_fractions', 'Multiply Fractions', 'Multiply fractions and simplify results.', 'arithmetic', 4, 75, 21),
('arith_divide_fractions', 'Divide Fractions', 'Divide fractions using reciprocal relationships.', 'arithmetic', 5, 78, 24),
('arith_mixed_numbers_operations', 'Mixed Number Operations', 'Operate with mixed numbers across all four operations.', 'arithmetic', 5, 78, 24),
('arith_decimal_place_value', 'Decimal Place Value', 'Read, write, and decompose decimal numbers.', 'arithmetic', 3, 71, 17),
('arith_compare_order_decimals', 'Compare and Order Decimals', 'Compare and order decimal values.', 'arithmetic', 3, 72, 18),
('arith_decimal_add_subtract', 'Decimal Addition and Subtraction', 'Add and subtract decimals with place-value alignment.', 'arithmetic', 4, 74, 20),
('arith_decimal_multiply', 'Decimal Multiplication', 'Multiply decimals and place decimal points correctly.', 'arithmetic', 4, 75, 21),
('arith_decimal_divide', 'Decimal Division', 'Divide decimals using scaling and long division.', 'arithmetic', 5, 78, 24),
('arith_fraction_decimal_conversion', 'Fraction-Decimal Conversion', 'Convert values between fraction and decimal forms.', 'arithmetic', 4, 75, 21),
('arith_ratio_basics', 'Ratio Basics', 'Represent and simplify ratios in multiple forms.', 'arithmetic', 3, 72, 18),
('arith_unit_rates', 'Unit Rates', 'Compute and interpret unit rates in contexts.', 'arithmetic', 4, 74, 20),
('arith_proportions', 'Proportions', 'Set up and solve proportional relationships.', 'arithmetic', 4, 75, 21),
('arith_percent_basics', 'Percent Basics', 'Interpret percentages as per-hundred quantities.', 'arithmetic', 4, 75, 21),
('arith_percent_of_quantity', 'Percent of a Quantity', 'Compute percentages of numbers using equivalent forms.', 'arithmetic', 4, 76, 22),
('arith_percent_increase_decrease', 'Percent Increase and Decrease', 'Solve increase/decrease and discount/tax problems.', 'arithmetic', 5, 79, 25),
('arith_percent_word_problems', 'Percent Word Problems', 'Apply percentages and proportions in multistep contexts.', 'arithmetic', 5, 80, 26),
('arith_exponents_basics', 'Exponents Basics', 'Interpret repeated multiplication with exponents.', 'arithmetic', 4, 75, 21),
('arith_powers_of_ten', 'Powers of Ten', 'Use powers of ten in place value and scaling.', 'arithmetic', 4, 76, 22),
('arith_square_roots_perfect_squares', 'Square Roots of Perfect Squares', 'Compute square roots of perfect squares and inverse links.', 'arithmetic', 5, 79, 25),
('arith_order_of_operations_with_exponents', 'Order of Operations with Exponents', 'Evaluate arithmetic expressions including powers and roots.', 'arithmetic', 5, 80, 26),
('arith_pre_algebra_numeric_expressions', 'Pre-Algebra Numeric Expressions', 'Solve rich numeric expressions that bridge arithmetic to algebra.', 'arithmetic', 5, 82, 30),
('alg_variables_constants_terms', 'Variables, Constants, and Terms', 'Identify variables, constants, coefficients, and terms in algebraic expressions.', 'algebra', 3, 70, 18),
('alg_translate_verbal_expressions', 'Translate Verbal Phrases to Expressions', 'Convert verbal statements into algebraic expressions.', 'algebra', 3, 70, 18),
('alg_evaluate_expressions_substitution', 'Evaluate Expressions by Substitution', 'Evaluate algebraic expressions by replacing variables with values.', 'algebra', 3, 70, 18),
('alg_order_of_operations_algebraic', 'Order of Operations in Algebraic Contexts', 'Apply operation priority when evaluating expressions with variables.', 'algebra', 3, 72, 22),
('alg_like_terms_identification', 'Identify Like Terms', 'Recognize terms that can be combined in algebraic expressions.', 'algebra', 3, 70, 18),
('alg_simplify_like_terms', 'Simplify by Combining Like Terms', 'Simplify expressions by combining compatible terms.', 'algebra', 3, 72, 22),
('alg_distributive_property', 'Distributive Property', 'Apply the distributive property to expand expressions.', 'algebra', 3, 72, 22),
('alg_combining_distributive_like_terms', 'Expand and Simplify Expressions', 'Use distribution and combining like terms in multi-step simplification.', 'algebra', 3, 72, 22),
('alg_rational_coefficients_expressions', 'Expressions with Rational Coefficients', 'Simplify expressions containing fractional and decimal coefficients.', 'algebra', 3, 72, 22),
('alg_absolute_value_expressions', 'Absolute Value in Expressions', 'Evaluate and simplify expressions involving absolute value.', 'algebra', 3, 72, 22),
('alg_exponent_rules_basic_algebra', 'Basic Exponent Rules in Algebra', 'Apply product, quotient, and power rules in algebraic expressions.', 'algebra', 3, 72, 22),
('alg_scientific_notation_algebraic', 'Scientific Notation in Algebra', 'Operate with scientific notation in algebraic settings.', 'algebra', 3, 72, 22),
('alg_formulas_rearrangement_intro', 'Formula Rearrangement Intro', 'Rearrange formulas to isolate a chosen variable.', 'algebra', 3, 72, 22),
('alg_one_step_equations_add_sub', 'One-step Equations (Add/Subtract)', 'Solve one-step linear equations using addition and subtraction.', 'algebra', 3, 72, 22),
('alg_one_step_equations_mul_div', 'One-step Equations (Multiply/Divide)', 'Solve one-step linear equations using multiplication and division.', 'algebra', 3, 72, 22),
('alg_two_step_linear_equations', 'Two-step Linear Equations', 'Solve two-step linear equations with inverse operations.', 'algebra', 4, 75, 27),
('alg_multi_step_linear_equations', 'Multi-step Linear Equations', 'Solve multi-step linear equations with simplification and balancing.', 'algebra', 4, 75, 27),
('alg_linear_equations_parentheses', 'Linear Equations with Parentheses', 'Solve equations requiring distribution before isolating variables.', 'algebra', 4, 75, 27),
('alg_linear_equations_fractions', 'Linear Equations with Fractions', 'Solve linear equations containing fractional coefficients and terms.', 'algebra', 4, 75, 27),
('alg_literal_equations', 'Literal Equations', 'Solve equations for a specified variable in symbolic form.', 'algebra', 4, 75, 27),
('alg_linear_equations_word_problems', 'Linear Equation Word Problems', 'Model contexts with linear equations and solve.', 'algebra', 4, 75, 27),
('alg_linear_equations_parameters', 'Linear Equations with Parameters', 'Analyze linear equations containing parameters.', 'algebra', 4, 75, 27),
('alg_linear_equation_identities_contradictions', 'Identities and Contradictions', 'Classify equations as one solution, no solution, or infinitely many.', 'algebra', 4, 75, 27),
('alg_absolute_value_linear_equations', 'Absolute Value Linear Equations', 'Solve linear equations with absolute value by case analysis.', 'algebra', 4, 75, 27),
('alg_solution_sets_interval_intro', 'Solution Sets and Interval Intro', 'Express solution sets using set and interval notation basics.', 'algebra', 4, 75, 27),
('alg_inequality_basics', 'Inequality Basics', 'Interpret and manipulate inequality symbols in algebraic statements.', 'algebra', 4, 75, 27),
('alg_one_step_inequalities', 'One-step Inequalities', 'Solve one-step inequalities and represent solutions.', 'algebra', 4, 75, 27),
('alg_two_step_inequalities', 'Two-step Inequalities', 'Solve two-step inequalities including sign changes.', 'algebra', 4, 75, 27),
('alg_multi_step_inequalities', 'Multi-step Inequalities', 'Solve multi-step inequalities with simplification and transformations.', 'algebra', 4, 75, 27),
('alg_compound_inequalities_and', 'Compound Inequalities (AND)', 'Solve compound inequalities connected by AND.', 'algebra', 4, 75, 27),
('alg_compound_inequalities_or', 'Compound Inequalities (OR)', 'Solve compound inequalities connected by OR.', 'algebra', 4, 75, 27),
('alg_interval_notation_inequalities', 'Interval Notation for Inequalities', 'Express compound inequality solutions in interval notation.', 'algebra', 5, 78, 33),
('alg_absolute_value_inequalities', 'Absolute Value Inequalities', 'Solve and graph absolute value inequalities by cases.', 'algebra', 5, 78, 33),
('alg_linear_inequalities_word_problems', 'Linear Inequality Word Problems', 'Model constraints with inequalities and interpret feasible sets.', 'algebra', 5, 78, 33),
('alg_graph_inequalities_number_line', 'Graph Inequalities on Number Line', 'Represent inequality solution sets graphically on a number line.', 'algebra', 5, 78, 33),
('alg_systems_linear_inequalities_two_var', 'Systems of Linear Inequalities (2 Variables)', 'Find feasible regions satisfying two-variable linear inequalities.', 'algebra', 5, 78, 33),
('alg_coordinate_plane_foundations', 'Coordinate Plane Foundations', 'Plot points, identify quadrants, and read coordinates.', 'algebra', 4, 75, 27),
('alg_graph_linear_equations', 'Graph Linear Equations', 'Graph linear equations in two variables.', 'algebra', 4, 75, 27),
('alg_slope_from_points', 'Slope from Two Points', 'Compute slope using coordinate pairs and rate interpretation.', 'algebra', 4, 75, 27),
('alg_slope_intercept_form', 'Slope-Intercept Form', 'Interpret and use y = mx + b for graphing and analysis.', 'algebra', 4, 75, 27),
('alg_point_slope_form', 'Point-Slope Form', 'Build and transform linear equations using point-slope form.', 'algebra', 4, 75, 27),
('alg_standard_form_linear', 'Standard Form of Linear Equations', 'Convert and interpret linear equations in standard form.', 'algebra', 4, 75, 27),
('alg_systems_two_var_graphing', 'Systems of Two Variables by Graphing', 'Solve systems of linear equations graphically.', 'algebra', 5, 78, 33),
('alg_systems_two_var_substitution', 'Systems by Substitution', 'Solve systems of two equations using substitution.', 'algebra', 5, 78, 33),
('alg_systems_two_var_elimination', 'Systems by Elimination', 'Solve systems of two equations using elimination.', 'algebra', 5, 78, 33),
('alg_systems_two_var_word_problems', 'Systems Word Problems', 'Model real situations with linear systems and solve.', 'algebra', 5, 78, 33),
('alg_systems_three_var_intro', 'Systems of Three Variables Intro', 'Set up and solve basic three-variable linear systems.', 'algebra', 6, 81, 39),
('alg_systems_three_var_elimination', 'Three-variable Elimination', 'Solve 3x3 systems systematically by elimination.', 'algebra', 6, 81, 39),
('alg_systems_solution_classification', 'System Solution Classification', 'Classify systems as consistent/inconsistent and dependent/independent.', 'algebra', 6, 81, 39),
('alg_linear_programming_intro', 'Linear Programming Intro', 'Optimize a linear objective under linear constraints.', 'algebra', 6, 81, 39),
('alg_polynomial_terms_degree', 'Polynomial Terms and Degree', 'Classify polynomials by terms, degree, and leading coefficient.', 'algebra', 5, 78, 33),
('alg_add_subtract_polynomials', 'Add and Subtract Polynomials', 'Perform addition and subtraction with polynomial expressions.', 'algebra', 5, 78, 33),
('alg_multiply_monomial_polynomial', 'Multiply Monomial and Polynomial', 'Multiply monomials across polynomial terms using distribution.', 'algebra', 5, 78, 33),
('alg_multiply_binomials', 'Multiply Binomials', 'Multiply binomials accurately using structured expansion.', 'algebra', 5, 78, 33),
('alg_multiply_polynomials_general', 'General Polynomial Multiplication', 'Multiply higher-degree polynomials systematically.', 'algebra', 5, 78, 33),
('alg_special_products_square_binomial', 'Special Products: Square of a Binomial', 'Use identities for squares of binomials.', 'algebra', 5, 78, 33),
('alg_special_products_conjugates', 'Special Products: Conjugates', 'Use conjugate identities to simplify products quickly.', 'algebra', 5, 78, 33),
('alg_polynomial_long_division', 'Polynomial Long Division', 'Divide polynomials using long division.', 'algebra', 6, 81, 39),
('alg_synthetic_division', 'Synthetic Division', 'Perform polynomial division efficiently with synthetic division.', 'algebra', 6, 81, 39),
('alg_remainder_factor_theorem', 'Remainder and Factor Theorem', 'Use theorem-based tests to analyze polynomial factors and roots.', 'algebra', 6, 81, 39),
('alg_polynomial_evaluation', 'Polynomial Evaluation', 'Evaluate polynomial functions at given inputs.', 'algebra', 5, 78, 33),
('alg_polynomial_graph_features_intro', 'Polynomial Graph Features Intro', 'Relate polynomial form to zeros, intercepts, and shape features.', 'algebra', 6, 81, 39),
('alg_polynomial_end_behavior', 'Polynomial End Behavior', 'Analyze end behavior using degree and leading coefficient.', 'algebra', 6, 81, 39),
('alg_polynomial_roots_multiplicity_intro', 'Roots and Multiplicity Intro', 'Interpret roots and multiplicities in polynomial behavior.', 'algebra', 6, 81, 39),
('alg_factor_gcf', 'Factor by Greatest Common Factor', 'Factor expressions by extracting the GCF.', 'algebra', 5, 78, 33),
('alg_factor_trinomials_monic', 'Factor Monic Trinomials', 'Factor trinomials with leading coefficient 1.', 'algebra', 6, 81, 39),
('alg_factor_trinomials_non_monic', 'Factor Non-Monic Trinomials', 'Factor trinomials with leading coefficients other than 1.', 'algebra', 6, 81, 39),
('alg_factor_difference_of_squares', 'Factor Difference of Squares', 'Recognize and factor expressions of the form a^2 - b^2.', 'algebra', 6, 81, 39),
('alg_factor_perfect_square_trinomials', 'Factor Perfect Square Trinomials', 'Identify and factor perfect square trinomials.', 'algebra', 6, 81, 39),
('alg_factor_sum_difference_cubes', 'Factor Sum and Difference of Cubes', 'Apply cube identities to factor cubic expressions.', 'algebra', 6, 81, 39),
('alg_factor_by_grouping', 'Factor by Grouping', 'Factor multi-term polynomials using grouping patterns.', 'algebra', 6, 81, 39),
('alg_factoring_strategy_selection', 'Factoring Strategy Selection', 'Select efficient factoring methods for mixed expression types.', 'algebra', 7, 84, 45),
('alg_solve_polynomial_equations_factoring', 'Solve Polynomial Equations by Factoring', 'Solve polynomial equations using zero-product reasoning.', 'algebra', 7, 84, 45),
('alg_rational_expressions_simplify', 'Simplify Rational Expressions', 'Simplify rational expressions through factoring and cancellation.', 'algebra', 6, 81, 39),
('alg_rational_expressions_multiply_divide', 'Multiply and Divide Rational Expressions', 'Perform multiplication and division of rational expressions.', 'algebra', 6, 81, 39),
('alg_rational_expressions_add_subtract', 'Add and Subtract Rational Expressions', 'Add and subtract rational expressions using common denominators.', 'algebra', 6, 81, 39),
('alg_rational_equations_linear', 'Linear Rational Equations', 'Solve linear equations containing rational expressions with restrictions.', 'algebra', 7, 84, 45),
('alg_quadratic_forms_and_structure', 'Quadratic Forms and Structure', 'Recognize standard, factored, and vertex forms of quadratics.', 'algebra', 6, 81, 39),
('alg_solve_quadratics_factoring', 'Solve Quadratics by Factoring', 'Solve quadratic equations using factorization methods.', 'algebra', 7, 84, 45),
('alg_solve_quadratics_square_root', 'Solve Quadratics by Square Root Method', 'Solve quadratics reducible to squared binomial forms.', 'algebra', 7, 84, 45),
('alg_complete_the_square', 'Complete the Square', 'Transform quadratics by completing the square.', 'algebra', 7, 84, 45),
('alg_quadratic_formula', 'Quadratic Formula', 'Solve quadratic equations with the quadratic formula.', 'algebra', 7, 84, 45),
('alg_quadratic_discriminant', 'Quadratic Discriminant Analysis', 'Use the discriminant to predict root types and counts.', 'algebra', 7, 84, 45),
('alg_convert_to_vertex_form', 'Convert to Vertex Form', 'Rewrite quadratic expressions into vertex form.', 'algebra', 7, 84, 45),
('alg_graph_quadratic_functions', 'Graph Quadratic Functions', 'Graph quadratic functions and identify key graph features.', 'algebra', 7, 84, 45),
('alg_quadratic_vertex_axis', 'Vertex and Axis of Symmetry', 'Determine vertex and axis of symmetry from equation forms.', 'algebra', 7, 84, 45),
('alg_quadratic_intercepts', 'Quadratic Intercepts', 'Find and interpret x- and y-intercepts of quadratic functions.', 'algebra', 7, 84, 45),
('alg_quadratic_modeling_word_problems', 'Quadratic Modeling Word Problems', 'Model and solve contextual problems with quadratic functions.', 'algebra', 7, 84, 45),
('alg_quadratic_inequalities', 'Quadratic Inequalities', 'Solve quadratic inequalities with interval reasoning.', 'algebra', 8, 86, 52),
('alg_complex_numbers_intro', 'Complex Numbers Intro', 'Introduce imaginary unit and basic complex number operations.', 'algebra', 7, 84, 45),
('alg_quadratics_complex_solutions', 'Quadratics with Complex Solutions', 'Solve quadratics whose roots are complex.', 'algebra', 8, 86, 52),
('alg_function_concept_domain_range', 'Function Concept, Domain, and Range', 'Define functions and determine domain/range in basic representations.', 'algebra', 5, 78, 33),
('alg_function_notation_evaluation', 'Function Notation and Evaluation', 'Use function notation and evaluate functions at given inputs.', 'algebra', 5, 78, 33),
('alg_functions_tables_graphs_mapping', 'Functions: Tables, Graphs, and Mapping', 'Relate tabular, graphical, and mapping representations of functions.', 'algebra', 5, 78, 33),
('alg_rate_of_change_average', 'Average Rate of Change', 'Compute and interpret average rate of change between points.', 'algebra', 5, 78, 33),
('alg_linear_function_modeling', 'Linear Function Modeling', 'Build linear models for contextual relationships.', 'algebra', 6, 81, 39),
('alg_piecewise_functions_intro', 'Piecewise Functions Intro', 'Interpret and evaluate piecewise-defined functions.', 'algebra', 6, 81, 39),
('alg_inverse_functions_intro', 'Inverse Functions Intro', 'Identify and compute inverses of basic functions.', 'algebra', 6, 81, 39),
('alg_function_composition_intro', 'Function Composition Intro', 'Compose functions and evaluate composite expressions.', 'algebra', 6, 81, 39),
('alg_function_transformations', 'Function Transformations', 'Apply shifts, stretches, reflections, and compressions to graphs.', 'algebra', 6, 81, 39),
('alg_parent_function_families', 'Parent Function Families', 'Compare key families of functions by shape and behavior.', 'algebra', 6, 81, 39),
('alg_exponential_functions_intro', 'Exponential Functions Intro', 'Understand exponential form and core graph behavior.', 'algebra', 6, 81, 39),
('alg_exponential_growth_decay', 'Exponential Growth and Decay', 'Model growth and decay processes with exponentials.', 'algebra', 6, 81, 39),
('alg_logarithm_concept_intro', 'Logarithm Concept Intro', 'Interpret logarithms as inverse operations of exponentials.', 'algebra', 7, 84, 45),
('alg_logarithm_properties', 'Logarithm Properties', 'Apply product, quotient, and power properties of logarithms.', 'algebra', 7, 84, 45),
('alg_solve_exponential_equations_logs', 'Solve Exponential Equations with Logs', 'Solve exponential equations using logarithmic transformations.', 'algebra', 8, 86, 52),
('alg_solve_logarithmic_equations', 'Solve Logarithmic Equations', 'Solve logarithmic equations and verify valid domains.', 'algebra', 8, 86, 52),
('alg_sequence_patterns_intro', 'Sequence Pattern Intro', 'Recognize and extend arithmetic and geometric patterns.', 'algebra', 5, 78, 33),
('alg_arithmetic_sequence_nth_term', 'Arithmetic Sequence nth Term', 'Derive and use explicit formulas for arithmetic sequences.', 'algebra', 6, 81, 39),
('alg_arithmetic_series_sum', 'Arithmetic Series Sum', 'Compute finite sums of arithmetic sequences.', 'algebra', 6, 81, 39),
('alg_geometric_sequence_nth_term', 'Geometric Sequence nth Term', 'Derive and use explicit formulas for geometric sequences.', 'algebra', 6, 81, 39),
('alg_geometric_series_sum', 'Geometric Series Sum', 'Compute finite sums of geometric sequences.', 'algebra', 6, 81, 39),
('alg_recursive_sequences_intro', 'Recursive Sequences Intro', 'Define and analyze recursive sequences.', 'algebra', 6, 81, 39),
('alg_sigma_notation_series', 'Sigma Notation and Series', 'Represent and evaluate series using sigma notation.', 'algebra', 7, 84, 45),
('alg_series_convergence_intuition', 'Series Convergence Intuition', 'Develop intuition about boundedness and convergence patterns.', 'algebra', 7, 84, 45),
('alg_binomial_theorem_intro', 'Binomial Theorem Intro', 'Use binomial coefficients to expand binomial powers.', 'algebra', 7, 84, 45),
('alg_matrices_intro_systems', 'Matrices Intro for Systems', 'Represent systems of equations using matrices.', 'algebra', 6, 81, 39),
('alg_matrix_operations_basic', 'Basic Matrix Operations', 'Add, subtract, and multiply matrices in compatible dimensions.', 'algebra', 6, 81, 39),
('alg_matrix_determinant_2x2', 'Determinant of 2x2 Matrices', 'Compute determinants and interpret invertibility in 2x2 case.', 'algebra', 7, 84, 45),
('alg_inverse_matrix_method_systems', 'Inverse Matrix Method for Systems', 'Solve linear systems using matrix inverses.', 'algebra', 7, 84, 45),
('geom_skill_1', 'Geometry Skill 1', 'Understanding geometry skill 1', 'geometry', 5, 70, 18),
('geom_skill_2', 'Geometry Skill 2', 'Understanding geometry skill 2', 'geometry', 5, 70, 18),
('geom_skill_3', 'Geometry Skill 3', 'Understanding geometry skill 3', 'geometry', 5, 70, 18),
('geom_skill_4', 'Geometry Skill 4', 'Understanding geometry skill 4', 'geometry', 5, 70, 18),
('geom_skill_5', 'Geometry Skill 5', 'Understanding geometry skill 5', 'geometry', 5, 71, 18),
('geom_skill_6', 'Geometry Skill 6', 'Understanding geometry skill 6', 'geometry', 5, 71, 18),
('geom_skill_7', 'Geometry Skill 7', 'Understanding geometry skill 7', 'geometry', 5, 71, 18),
('geom_skill_8', 'Geometry Skill 8', 'Understanding geometry skill 8', 'geometry', 5, 71, 20),
('geom_skill_9', 'Geometry Skill 9', 'Understanding geometry skill 9', 'geometry', 5, 72, 20),
('geom_skill_10', 'Geometry Skill 10', 'Understanding geometry skill 10', 'geometry', 5, 72, 20),
('geom_skill_11', 'Geometry Skill 11', 'Understanding geometry skill 11', 'geometry', 5, 72, 20),
('geom_skill_12', 'Geometry Skill 12', 'Understanding geometry skill 12', 'geometry', 5, 72, 20),
('geom_skill_13', 'Geometry Skill 13', 'Understanding geometry skill 13', 'geometry', 5, 72, 20),
('geom_skill_14', 'Geometry Skill 14', 'Understanding geometry skill 14', 'geometry', 5, 73, 20),
('geom_skill_15', 'Geometry Skill 15', 'Understanding geometry skill 15', 'geometry', 5, 73, 20),
('geom_skill_16', 'Geometry Skill 16', 'Understanding geometry skill 16', 'geometry', 5, 73, 20),
('geom_skill_17', 'Geometry Skill 17', 'Understanding geometry skill 17', 'geometry', 5, 73, 20),
('geom_skill_18', 'Geometry Skill 18', 'Understanding geometry skill 18', 'geometry', 5, 74, 20),
('geom_skill_19', 'Geometry Skill 19', 'Understanding geometry skill 19', 'geometry', 5, 74, 20),
('geom_skill_20', 'Geometry Skill 20', 'Understanding geometry skill 20', 'geometry', 5, 74, 20),
('geom_skill_21', 'Geometry Skill 21', 'Understanding geometry skill 21', 'geometry', 5, 74, 20),
('geom_skill_22', 'Geometry Skill 22', 'Understanding geometry skill 22', 'geometry', 5, 74, 20),
('geom_skill_23', 'Geometry Skill 23', 'Understanding geometry skill 23', 'geometry', 6, 75, 22),
('geom_skill_24', 'Geometry Skill 24', 'Understanding geometry skill 24', 'geometry', 6, 75, 22),
('geom_skill_25', 'Geometry Skill 25', 'Understanding geometry skill 25', 'geometry', 6, 75, 22),
('geom_skill_26', 'Geometry Skill 26', 'Understanding geometry skill 26', 'geometry', 6, 75, 22),
('geom_skill_27', 'Geometry Skill 27', 'Understanding geometry skill 27', 'geometry', 6, 76, 22),
('geom_skill_28', 'Geometry Skill 28', 'Understanding geometry skill 28', 'geometry', 6, 76, 22),
('geom_skill_29', 'Geometry Skill 29', 'Understanding geometry skill 29', 'geometry', 6, 76, 22),
('geom_skill_30', 'Geometry Skill 30', 'Understanding geometry skill 30', 'geometry', 6, 76, 22),
('geom_skill_31', 'Geometry Skill 31', 'Understanding geometry skill 31', 'geometry', 6, 76, 22),
('geom_skill_32', 'Geometry Skill 32', 'Understanding geometry skill 32', 'geometry', 6, 77, 22),
('geom_skill_33', 'Geometry Skill 33', 'Understanding geometry skill 33', 'geometry', 6, 77, 22),
('geom_skill_34', 'Geometry Skill 34', 'Understanding geometry skill 34', 'geometry', 6, 77, 22),
('geom_skill_35', 'Geometry Skill 35', 'Understanding geometry skill 35', 'geometry', 6, 77, 22),
('geom_skill_36', 'Geometry Skill 36', 'Understanding geometry skill 36', 'geometry', 6, 78, 22),
('geom_skill_37', 'Geometry Skill 37', 'Understanding geometry skill 37', 'geometry', 6, 78, 22),
('geom_skill_38', 'Geometry Skill 38', 'Understanding geometry skill 38', 'geometry', 7, 78, 24),
('geom_skill_39', 'Geometry Skill 39', 'Understanding geometry skill 39', 'geometry', 7, 78, 24),
('geom_skill_40', 'Geometry Skill 40', 'Understanding geometry skill 40', 'geometry', 7, 78, 24),
('geom_skill_41', 'Geometry Skill 41', 'Understanding geometry skill 41', 'geometry', 7, 79, 24),
('geom_skill_42', 'Geometry Skill 42', 'Understanding geometry skill 42', 'geometry', 7, 79, 24),
('geom_skill_43', 'Geometry Skill 43', 'Understanding geometry skill 43', 'geometry', 7, 79, 24),
('geom_skill_44', 'Geometry Skill 44', 'Understanding geometry skill 44', 'geometry', 7, 79, 24),
('geom_skill_45', 'Geometry Skill 45', 'Understanding geometry skill 45', 'geometry', 7, 80, 24),
('trig_skill_1', 'Trigonometry Skill 1', 'Understanding trigonometry skill 1', 'trigonometry', 7, 70, 24),
('trig_skill_2', 'Trigonometry Skill 2', 'Understanding trigonometry skill 2', 'trigonometry', 7, 70, 24),
('trig_skill_3', 'Trigonometry Skill 3', 'Understanding trigonometry skill 3', 'trigonometry', 7, 71, 24),
('trig_skill_4', 'Trigonometry Skill 4', 'Understanding trigonometry skill 4', 'trigonometry', 7, 71, 24),
('trig_skill_5', 'Trigonometry Skill 5', 'Understanding trigonometry skill 5', 'trigonometry', 7, 71, 24),
('trig_skill_6', 'Trigonometry Skill 6', 'Understanding trigonometry skill 6', 'trigonometry', 7, 72, 24),
('trig_skill_7', 'Trigonometry Skill 7', 'Understanding trigonometry skill 7', 'trigonometry', 7, 72, 24),
('trig_skill_8', 'Trigonometry Skill 8', 'Understanding trigonometry skill 8', 'trigonometry', 8, 72, 26),
('trig_skill_9', 'Trigonometry Skill 9', 'Understanding trigonometry skill 9', 'trigonometry', 8, 73, 26),
('trig_skill_10', 'Trigonometry Skill 10', 'Understanding trigonometry skill 10', 'trigonometry', 8, 73, 26),
('trig_skill_11', 'Trigonometry Skill 11', 'Understanding trigonometry skill 11', 'trigonometry', 8, 73, 26),
('trig_skill_12', 'Trigonometry Skill 12', 'Understanding trigonometry skill 12', 'trigonometry', 8, 74, 26),
('trig_skill_13', 'Trigonometry Skill 13', 'Understanding trigonometry skill 13', 'trigonometry', 8, 74, 26),
('trig_skill_14', 'Trigonometry Skill 14', 'Understanding trigonometry skill 14', 'trigonometry', 8, 74, 26),
('trig_skill_15', 'Trigonometry Skill 15', 'Understanding trigonometry skill 15', 'trigonometry', 8, 75, 26),
('trig_skill_16', 'Trigonometry Skill 16', 'Understanding trigonometry skill 16', 'trigonometry', 8, 75, 26),
('trig_skill_17', 'Trigonometry Skill 17', 'Understanding trigonometry skill 17', 'trigonometry', 8, 75, 26),
('trig_skill_18', 'Trigonometry Skill 18', 'Understanding trigonometry skill 18', 'trigonometry', 8, 76, 26),
('trig_skill_19', 'Trigonometry Skill 19', 'Understanding trigonometry skill 19', 'trigonometry', 8, 76, 26),
('trig_skill_20', 'Trigonometry Skill 20', 'Understanding trigonometry skill 20', 'trigonometry', 8, 76, 26),
('trig_skill_21', 'Trigonometry Skill 21', 'Understanding trigonometry skill 21', 'trigonometry', 8, 77, 26),
('trig_skill_22', 'Trigonometry Skill 22', 'Understanding trigonometry skill 22', 'trigonometry', 8, 77, 26),
('trig_skill_23', 'Trigonometry Skill 23', 'Understanding trigonometry skill 23', 'trigonometry', 9, 77, 28),
('trig_skill_24', 'Trigonometry Skill 24', 'Understanding trigonometry skill 24', 'trigonometry', 9, 78, 28),
('trig_skill_25', 'Trigonometry Skill 25', 'Understanding trigonometry skill 25', 'trigonometry', 9, 78, 28),
('trig_skill_26', 'Trigonometry Skill 26', 'Understanding trigonometry skill 26', 'trigonometry', 9, 78, 28),
('trig_skill_27', 'Trigonometry Skill 27', 'Understanding trigonometry skill 27', 'trigonometry', 9, 79, 28),
('trig_skill_28', 'Trigonometry Skill 28', 'Understanding trigonometry skill 28', 'trigonometry', 9, 79, 28),
('trig_skill_29', 'Trigonometry Skill 29', 'Understanding trigonometry skill 29', 'trigonometry', 9, 79, 28),
('trig_skill_30', 'Trigonometry Skill 30', 'Understanding trigonometry skill 30', 'trigonometry', 9, 80, 28),
('prob_skill_1', 'Probability Stats Skill 1', 'Understanding probability stats skill 1', 'probability_stats', 5, 70, 20),
('prob_skill_2', 'Probability Stats Skill 2', 'Understanding probability stats skill 2', 'probability_stats', 5, 70, 20),
('prob_skill_3', 'Probability Stats Skill 3', 'Understanding probability stats skill 3', 'probability_stats', 5, 70, 20),
('prob_skill_4', 'Probability Stats Skill 4', 'Understanding probability stats skill 4', 'probability_stats', 5, 71, 20),
('prob_skill_5', 'Probability Stats Skill 5', 'Understanding probability stats skill 5', 'probability_stats', 5, 71, 20),
('prob_skill_6', 'Probability Stats Skill 6', 'Understanding probability stats skill 6', 'probability_stats', 6, 71, 22),
('prob_skill_7', 'Probability Stats Skill 7', 'Understanding probability stats skill 7', 'probability_stats', 6, 72, 22),
('prob_skill_8', 'Probability Stats Skill 8', 'Understanding probability stats skill 8', 'probability_stats', 6, 72, 22),
('prob_skill_9', 'Probability Stats Skill 9', 'Understanding probability stats skill 9', 'probability_stats', 6, 72, 22),
('prob_skill_10', 'Probability Stats Skill 10', 'Understanding probability stats skill 10', 'probability_stats', 6, 72, 22),
('prob_skill_11', 'Probability Stats Skill 11', 'Understanding probability stats skill 11', 'probability_stats', 6, 73, 22),
('prob_skill_12', 'Probability Stats Skill 12', 'Understanding probability stats skill 12', 'probability_stats', 6, 73, 22),
('prob_skill_13', 'Probability Stats Skill 13', 'Understanding probability stats skill 13', 'probability_stats', 6, 73, 22),
('prob_skill_14', 'Probability Stats Skill 14', 'Understanding probability stats skill 14', 'probability_stats', 6, 74, 22),
('prob_skill_15', 'Probability Stats Skill 15', 'Understanding probability stats skill 15', 'probability_stats', 6, 74, 22),
('prob_skill_16', 'Probability Stats Skill 16', 'Understanding probability stats skill 16', 'probability_stats', 6, 74, 22),
('prob_skill_17', 'Probability Stats Skill 17', 'Understanding probability stats skill 17', 'probability_stats', 6, 74, 22),
('prob_skill_18', 'Probability Stats Skill 18', 'Understanding probability stats skill 18', 'probability_stats', 7, 75, 24),
('prob_skill_19', 'Probability Stats Skill 19', 'Understanding probability stats skill 19', 'probability_stats', 7, 75, 24),
('prob_skill_20', 'Probability Stats Skill 20', 'Understanding probability stats skill 20', 'probability_stats', 7, 75, 24),
('prob_skill_21', 'Probability Stats Skill 21', 'Understanding probability stats skill 21', 'probability_stats', 7, 76, 24),
('prob_skill_22', 'Probability Stats Skill 22', 'Understanding probability stats skill 22', 'probability_stats', 7, 76, 24),
('prob_skill_23', 'Probability Stats Skill 23', 'Understanding probability stats skill 23', 'probability_stats', 7, 76, 24),
('prob_skill_24', 'Probability Stats Skill 24', 'Understanding probability stats skill 24', 'probability_stats', 7, 76, 24),
('prob_skill_25', 'Probability Stats Skill 25', 'Understanding probability stats skill 25', 'probability_stats', 7, 77, 24),
('prob_skill_26', 'Probability Stats Skill 26', 'Understanding probability stats skill 26', 'probability_stats', 7, 77, 24),
('prob_skill_27', 'Probability Stats Skill 27', 'Understanding probability stats skill 27', 'probability_stats', 7, 77, 24),
('prob_skill_28', 'Probability Stats Skill 28', 'Understanding probability stats skill 28', 'probability_stats', 7, 78, 24),
('prob_skill_29', 'Probability Stats Skill 29', 'Understanding probability stats skill 29', 'probability_stats', 7, 78, 24),
('prob_skill_30', 'Probability Stats Skill 30', 'Understanding probability stats skill 30', 'probability_stats', 8, 78, 26),
('prob_skill_31', 'Probability Stats Skill 31', 'Understanding probability stats skill 31', 'probability_stats', 8, 78, 26),
('prob_skill_32', 'Probability Stats Skill 32', 'Understanding probability stats skill 32', 'probability_stats', 8, 79, 26),
('prob_skill_33', 'Probability Stats Skill 33', 'Understanding probability stats skill 33', 'probability_stats', 8, 79, 26),
('prob_skill_34', 'Probability Stats Skill 34', 'Understanding probability stats skill 34', 'probability_stats', 8, 79, 26),
('prob_skill_35', 'Probability Stats Skill 35', 'Understanding probability stats skill 35', 'probability_stats', 8, 80, 26),
('logic_skill_1', 'Logic Discrete Skill 1', 'Understanding logic discrete skill 1', 'logic_discrete', 6, 70, 22),
('logic_skill_2', 'Logic Discrete Skill 2', 'Understanding logic discrete skill 2', 'logic_discrete', 6, 70, 22),
('logic_skill_3', 'Logic Discrete Skill 3', 'Understanding logic discrete skill 3', 'logic_discrete', 6, 71, 22),
('logic_skill_4', 'Logic Discrete Skill 4', 'Understanding logic discrete skill 4', 'logic_discrete', 6, 71, 22),
('logic_skill_5', 'Logic Discrete Skill 5', 'Understanding logic discrete skill 5', 'logic_discrete', 6, 71, 22),
('logic_skill_6', 'Logic Discrete Skill 6', 'Understanding logic discrete skill 6', 'logic_discrete', 6, 72, 22),
('logic_skill_7', 'Logic Discrete Skill 7', 'Understanding logic discrete skill 7', 'logic_discrete', 6, 72, 22),
('logic_skill_8', 'Logic Discrete Skill 8', 'Understanding logic discrete skill 8', 'logic_discrete', 7, 72, 24),
('logic_skill_9', 'Logic Discrete Skill 9', 'Understanding logic discrete skill 9', 'logic_discrete', 7, 73, 24),
('logic_skill_10', 'Logic Discrete Skill 10', 'Understanding logic discrete skill 10', 'logic_discrete', 7, 73, 24),
('logic_skill_11', 'Logic Discrete Skill 11', 'Understanding logic discrete skill 11', 'logic_discrete', 7, 73, 24),
('logic_skill_12', 'Logic Discrete Skill 12', 'Understanding logic discrete skill 12', 'logic_discrete', 7, 74, 24),
('logic_skill_13', 'Logic Discrete Skill 13', 'Understanding logic discrete skill 13', 'logic_discrete', 7, 74, 24),
('logic_skill_14', 'Logic Discrete Skill 14', 'Understanding logic discrete skill 14', 'logic_discrete', 7, 74, 24),
('logic_skill_15', 'Logic Discrete Skill 15', 'Understanding logic discrete skill 15', 'logic_discrete', 7, 75, 24),
('logic_skill_16', 'Logic Discrete Skill 16', 'Understanding logic discrete skill 16', 'logic_discrete', 7, 75, 24),
('logic_skill_17', 'Logic Discrete Skill 17', 'Understanding logic discrete skill 17', 'logic_discrete', 7, 75, 24),
('logic_skill_18', 'Logic Discrete Skill 18', 'Understanding logic discrete skill 18', 'logic_discrete', 7, 76, 24),
('logic_skill_19', 'Logic Discrete Skill 19', 'Understanding logic discrete skill 19', 'logic_discrete', 7, 76, 24),
('logic_skill_20', 'Logic Discrete Skill 20', 'Understanding logic discrete skill 20', 'logic_discrete', 7, 76, 24),
('logic_skill_21', 'Logic Discrete Skill 21', 'Understanding logic discrete skill 21', 'logic_discrete', 7, 77, 24),
('logic_skill_22', 'Logic Discrete Skill 22', 'Understanding logic discrete skill 22', 'logic_discrete', 7, 77, 24),
('logic_skill_23', 'Logic Discrete Skill 23', 'Understanding logic discrete skill 23', 'logic_discrete', 8, 77, 26),
('logic_skill_24', 'Logic Discrete Skill 24', 'Understanding logic discrete skill 24', 'logic_discrete', 8, 78, 26),
('logic_skill_25', 'Logic Discrete Skill 25', 'Understanding logic discrete skill 25', 'logic_discrete', 8, 78, 26),
('logic_skill_26', 'Logic Discrete Skill 26', 'Understanding logic discrete skill 26', 'logic_discrete', 8, 78, 26),
('logic_skill_27', 'Logic Discrete Skill 27', 'Understanding logic discrete skill 27', 'logic_discrete', 8, 79, 26),
('logic_skill_28', 'Logic Discrete Skill 28', 'Understanding logic discrete skill 28', 'logic_discrete', 8, 79, 26),
('logic_skill_29', 'Logic Discrete Skill 29', 'Understanding logic discrete skill 29', 'logic_discrete', 8, 79, 26),
('logic_skill_30', 'Logic Discrete Skill 30', 'Understanding logic discrete skill 30', 'logic_discrete', 8, 80, 26),
('calc_skill_1', 'Calculus Skill 1', 'Understanding calculus skill 1', 'calculus', 9, 70, 28),
('calc_skill_2', 'Calculus Skill 2', 'Understanding calculus skill 2', 'calculus', 9, 70, 28),
('calc_skill_3', 'Calculus Skill 3', 'Understanding calculus skill 3', 'calculus', 9, 70, 28),
('calc_skill_4', 'Calculus Skill 4', 'Understanding calculus skill 4', 'calculus', 9, 71, 28),
('calc_skill_5', 'Calculus Skill 5', 'Understanding calculus skill 5', 'calculus', 9, 71, 28),
('calc_skill_6', 'Calculus Skill 6', 'Understanding calculus skill 6', 'calculus', 9, 71, 28),
('calc_skill_7', 'Calculus Skill 7', 'Understanding calculus skill 7', 'calculus', 9, 72, 28),
('calc_skill_8', 'Calculus Skill 8', 'Understanding calculus skill 8', 'calculus', 9, 72, 28),
('calc_skill_9', 'Calculus Skill 9', 'Understanding calculus skill 9', 'calculus', 9, 72, 28),
('calc_skill_10', 'Calculus Skill 10', 'Understanding calculus skill 10', 'calculus', 9, 72, 28),
('calc_skill_11', 'Calculus Skill 11', 'Understanding calculus skill 11', 'calculus', 9, 73, 28),
('calc_skill_12', 'Calculus Skill 12', 'Understanding calculus skill 12', 'calculus', 9, 73, 28),
('calc_skill_13', 'Calculus Skill 13', 'Understanding calculus skill 13', 'calculus', 9, 73, 28),
('calc_skill_14', 'Calculus Skill 14', 'Understanding calculus skill 14', 'calculus', 9, 74, 28),
('calc_skill_15', 'Calculus Skill 15', 'Understanding calculus skill 15', 'calculus', 9, 74, 28),
('calc_skill_16', 'Calculus Skill 16', 'Understanding calculus skill 16', 'calculus', 9, 74, 28),
('calc_skill_17', 'Calculus Skill 17', 'Understanding calculus skill 17', 'calculus', 9, 74, 28),
('calc_skill_18', 'Calculus Skill 18', 'Understanding calculus skill 18', 'calculus', 10, 75, 30),
('calc_skill_19', 'Calculus Skill 19', 'Understanding calculus skill 19', 'calculus', 10, 75, 30),
('calc_skill_20', 'Calculus Skill 20', 'Understanding calculus skill 20', 'calculus', 10, 75, 30),
('calc_skill_21', 'Calculus Skill 21', 'Understanding calculus skill 21', 'calculus', 10, 76, 30),
('calc_skill_22', 'Calculus Skill 22', 'Understanding calculus skill 22', 'calculus', 10, 76, 30),
('calc_skill_23', 'Calculus Skill 23', 'Understanding calculus skill 23', 'calculus', 10, 76, 30),
('calc_skill_24', 'Calculus Skill 24', 'Understanding calculus skill 24', 'calculus', 10, 76, 30),
('calc_skill_25', 'Calculus Skill 25', 'Understanding calculus skill 25', 'calculus', 10, 77, 30),
('calc_skill_26', 'Calculus Skill 26', 'Understanding calculus skill 26', 'calculus', 10, 77, 30),
('calc_skill_27', 'Calculus Skill 27', 'Understanding calculus skill 27', 'calculus', 10, 77, 30),
('calc_skill_28', 'Calculus Skill 28', 'Understanding calculus skill 28', 'calculus', 10, 78, 30),
('calc_skill_29', 'Calculus Skill 29', 'Understanding calculus skill 29', 'calculus', 10, 78, 30),
('calc_skill_30', 'Calculus Skill 30', 'Understanding calculus skill 30', 'calculus', 10, 78, 30),
('calc_skill_31', 'Calculus Skill 31', 'Understanding calculus skill 31', 'calculus', 10, 78, 30),
('calc_skill_32', 'Calculus Skill 32', 'Understanding calculus skill 32', 'calculus', 10, 79, 30),
('calc_skill_33', 'Calculus Skill 33', 'Understanding calculus skill 33', 'calculus', 10, 79, 30),
('calc_skill_34', 'Calculus Skill 34', 'Understanding calculus skill 34', 'calculus', 10, 79, 30),
('calc_skill_35', 'Calculus Skill 35', 'Understanding calculus skill 35', 'calculus', 10, 80, 30);
