-- Seed: Arithmetic skill prerequisite edges (DAG)
-- Each row means: source_skill_id is a prerequisite of target_skill_id

INSERT INTO skill_edges (
  source_skill_id,
  target_skill_id,
  edge_type,
  required_mastery
) VALUES
  ('arith_counting_objects_to_20', 'arith_counting_to_100', 'prerequisite', 65),
  ('arith_counting_objects_to_20', 'arith_number_line_basics', 'prerequisite', 65),

  ('arith_counting_to_100', 'arith_place_value_tens', 'prerequisite', 66),
  ('arith_number_line_basics', 'arith_place_value_tens', 'prerequisite', 66),
  ('arith_place_value_tens', 'arith_place_value_hundreds', 'prerequisite', 66),
  ('arith_place_value_hundreds', 'arith_place_value_thousands', 'prerequisite', 67),

  ('arith_place_value_tens', 'arith_compare_whole_numbers', 'prerequisite', 66),
  ('arith_compare_whole_numbers', 'arith_order_whole_numbers', 'prerequisite', 67),
  ('arith_place_value_thousands', 'arith_round_whole_numbers', 'prerequisite', 68),
  ('arith_order_whole_numbers', 'arith_round_whole_numbers', 'prerequisite', 68),

  ('arith_counting_to_100', 'arith_even_odd_patterns', 'prerequisite', 67),
  ('arith_compare_whole_numbers', 'arith_even_odd_patterns', 'prerequisite', 67),
  ('arith_even_odd_patterns', 'arith_factors_multiples_intro', 'prerequisite', 68),
  ('arith_order_whole_numbers', 'arith_factors_multiples_intro', 'prerequisite', 68),
  ('arith_factors_multiples_intro', 'arith_divisibility_rules', 'prerequisite', 70),
  ('arith_round_whole_numbers', 'arith_divisibility_rules', 'prerequisite', 70),

  ('arith_counting_objects_to_20', 'arith_addition_within_20', 'prerequisite', 65),
  ('arith_number_line_basics', 'arith_addition_within_20', 'prerequisite', 65),
  ('arith_place_value_hundreds', 'arith_addition_multi_digit', 'prerequisite', 67),
  ('arith_addition_within_20', 'arith_addition_multi_digit', 'prerequisite', 67),
  ('arith_addition_within_20', 'arith_subtraction_within_20', 'prerequisite', 65),
  ('arith_addition_multi_digit', 'arith_subtraction_multi_digit', 'prerequisite', 67),
  ('arith_subtraction_within_20', 'arith_subtraction_multi_digit', 'prerequisite', 67),

  ('arith_addition_within_20', 'arith_multiplication_as_repeated_addition', 'prerequisite', 68),
  ('arith_even_odd_patterns', 'arith_multiplication_as_repeated_addition', 'prerequisite', 68),
  ('arith_multiplication_as_repeated_addition', 'arith_multiplication_facts', 'prerequisite', 69),
  ('arith_multiplication_facts', 'arith_multi_digit_multiplication', 'prerequisite', 71),
  ('arith_addition_multi_digit', 'arith_multi_digit_multiplication', 'prerequisite', 71),

  ('arith_multiplication_facts', 'arith_division_as_sharing', 'prerequisite', 69),
  ('arith_subtraction_multi_digit', 'arith_division_as_sharing', 'prerequisite', 69),
  ('arith_division_as_sharing', 'arith_division_facts', 'prerequisite', 70),
  ('arith_multi_digit_multiplication', 'arith_long_division', 'prerequisite', 72),
  ('arith_division_facts', 'arith_long_division', 'prerequisite', 72),
  ('arith_subtraction_multi_digit', 'arith_inverse_operations', 'prerequisite', 70),
  ('arith_division_as_sharing', 'arith_inverse_operations', 'prerequisite', 70),
  ('arith_multi_digit_multiplication', 'arith_order_of_operations_basic', 'prerequisite', 72),
  ('arith_long_division', 'arith_order_of_operations_basic', 'prerequisite', 72),
  ('arith_inverse_operations', 'arith_order_of_operations_basic', 'prerequisite', 72),
  ('arith_order_of_operations_basic', 'arith_order_of_operations_grouping', 'prerequisite', 74),

  ('arith_number_line_basics', 'arith_integer_number_line', 'prerequisite', 70),
  ('arith_order_whole_numbers', 'arith_integer_number_line', 'prerequisite', 70),
  ('arith_integer_number_line', 'arith_compare_order_integers', 'prerequisite', 71),
  ('arith_integer_number_line', 'arith_absolute_value', 'prerequisite', 71),
  ('arith_compare_order_integers', 'arith_add_integers', 'prerequisite', 74),
  ('arith_absolute_value', 'arith_add_integers', 'prerequisite', 74),
  ('arith_addition_within_20', 'arith_add_integers', 'prerequisite', 74),
  ('arith_add_integers', 'arith_subtract_integers', 'prerequisite', 75),
  ('arith_absolute_value', 'arith_subtract_integers', 'prerequisite', 75),
  ('arith_add_integers', 'arith_multiply_integers', 'prerequisite', 75),
  ('arith_multiplication_facts', 'arith_multiply_integers', 'prerequisite', 75),
  ('arith_multiply_integers', 'arith_divide_integers', 'prerequisite', 76),
  ('arith_division_facts', 'arith_divide_integers', 'prerequisite', 76),
  ('arith_divide_integers', 'arith_integer_multi_step_expressions', 'prerequisite', 78),
  ('arith_order_of_operations_grouping', 'arith_integer_multi_step_expressions', 'prerequisite', 78),

  ('arith_place_value_hundreds', 'arith_fraction_part_of_whole', 'prerequisite', 68),
  ('arith_addition_within_20', 'arith_fraction_part_of_whole', 'prerequisite', 68),
  ('arith_fraction_part_of_whole', 'arith_equivalent_fractions', 'prerequisite', 71),
  ('arith_multiplication_facts', 'arith_equivalent_fractions', 'prerequisite', 71),
  ('arith_equivalent_fractions', 'arith_simplify_fractions', 'prerequisite', 72),
  ('arith_factors_multiples_intro', 'arith_simplify_fractions', 'prerequisite', 72),
  ('arith_equivalent_fractions', 'arith_compare_order_fractions', 'prerequisite', 72),
  ('arith_order_whole_numbers', 'arith_compare_order_fractions', 'prerequisite', 72),
  ('arith_fraction_part_of_whole', 'arith_add_subtract_fractions_like_den', 'prerequisite', 72),
  ('arith_addition_within_20', 'arith_add_subtract_fractions_like_den', 'prerequisite', 72),
  ('arith_simplify_fractions', 'arith_add_subtract_fractions_unlike_den', 'prerequisite', 75),
  ('arith_add_subtract_fractions_like_den', 'arith_add_subtract_fractions_unlike_den', 'prerequisite', 75),
  ('arith_simplify_fractions', 'arith_multiply_fractions', 'prerequisite', 75),
  ('arith_multi_digit_multiplication', 'arith_multiply_fractions', 'prerequisite', 75),
  ('arith_multiply_fractions', 'arith_divide_fractions', 'prerequisite', 78),
  ('arith_inverse_operations', 'arith_divide_fractions', 'prerequisite', 78),
  ('arith_add_subtract_fractions_unlike_den', 'arith_mixed_numbers_operations', 'prerequisite', 78),
  ('arith_multiply_fractions', 'arith_mixed_numbers_operations', 'prerequisite', 78),

  ('arith_place_value_thousands', 'arith_decimal_place_value', 'prerequisite', 71),
  ('arith_fraction_part_of_whole', 'arith_decimal_place_value', 'prerequisite', 71),
  ('arith_decimal_place_value', 'arith_compare_order_decimals', 'prerequisite', 72),
  ('arith_order_whole_numbers', 'arith_compare_order_decimals', 'prerequisite', 72),
  ('arith_decimal_place_value', 'arith_decimal_add_subtract', 'prerequisite', 74),
  ('arith_addition_multi_digit', 'arith_decimal_add_subtract', 'prerequisite', 74),
  ('arith_decimal_add_subtract', 'arith_decimal_multiply', 'prerequisite', 75),
  ('arith_multi_digit_multiplication', 'arith_decimal_multiply', 'prerequisite', 75),
  ('arith_decimal_multiply', 'arith_decimal_divide', 'prerequisite', 78),
  ('arith_long_division', 'arith_decimal_divide', 'prerequisite', 78),
  ('arith_simplify_fractions', 'arith_fraction_decimal_conversion', 'prerequisite', 75),
  ('arith_decimal_place_value', 'arith_fraction_decimal_conversion', 'prerequisite', 75),

  ('arith_factors_multiples_intro', 'arith_ratio_basics', 'prerequisite', 72),
  ('arith_compare_order_fractions', 'arith_ratio_basics', 'prerequisite', 72),
  ('arith_ratio_basics', 'arith_unit_rates', 'prerequisite', 74),
  ('arith_long_division', 'arith_unit_rates', 'prerequisite', 74),
  ('arith_ratio_basics', 'arith_proportions', 'prerequisite', 75),
  ('arith_add_subtract_fractions_unlike_den', 'arith_proportions', 'prerequisite', 75),
  ('arith_ratio_basics', 'arith_percent_basics', 'prerequisite', 75),
  ('arith_decimal_place_value', 'arith_percent_basics', 'prerequisite', 75),
  ('arith_percent_basics', 'arith_percent_of_quantity', 'prerequisite', 76),
  ('arith_multi_digit_multiplication', 'arith_percent_of_quantity', 'prerequisite', 76),
  ('arith_percent_of_quantity', 'arith_percent_increase_decrease', 'prerequisite', 79),
  ('arith_unit_rates', 'arith_percent_increase_decrease', 'prerequisite', 79),
  ('arith_percent_increase_decrease', 'arith_percent_word_problems', 'prerequisite', 80),
  ('arith_proportions', 'arith_percent_word_problems', 'prerequisite', 80),

  ('arith_multiplication_facts', 'arith_exponents_basics', 'prerequisite', 75),
  ('arith_order_of_operations_basic', 'arith_exponents_basics', 'prerequisite', 75),
  ('arith_exponents_basics', 'arith_powers_of_ten', 'prerequisite', 76),
  ('arith_decimal_place_value', 'arith_powers_of_ten', 'prerequisite', 76),
  ('arith_exponents_basics', 'arith_square_roots_perfect_squares', 'prerequisite', 79),
  ('arith_factors_multiples_intro', 'arith_square_roots_perfect_squares', 'prerequisite', 79),
  ('arith_powers_of_ten', 'arith_order_of_operations_with_exponents', 'prerequisite', 80),
  ('arith_square_roots_perfect_squares', 'arith_order_of_operations_with_exponents', 'prerequisite', 80),
  ('arith_order_of_operations_grouping', 'arith_order_of_operations_with_exponents', 'prerequisite', 80),

  ('arith_integer_multi_step_expressions', 'arith_pre_algebra_numeric_expressions', 'prerequisite', 82),
  ('arith_percent_word_problems', 'arith_pre_algebra_numeric_expressions', 'prerequisite', 82),
  ('arith_order_of_operations_with_exponents', 'arith_pre_algebra_numeric_expressions', 'prerequisite', 82)
ON CONFLICT (source_skill_id, target_skill_id) DO NOTHING;
