-- Seed: Arithmetic skills (domain = arithmetic)
-- Compatible with scripts/db/skill_graph_schema.sql

INSERT INTO skills (
  id,
  name,
  description,
  domain,
  difficulty_level,
  mastery_threshold,
  xp_reward
) VALUES
  ('arith_counting_objects_to_20', 'Counting Objects to 20', 'Count concrete objects and quantities from 0 to 20.', 'arithmetic', 1, 64, 10),
  ('arith_counting_to_100', 'Counting to 100', 'Count forward and backward up to 100.', 'arithmetic', 1, 65, 11),
  ('arith_number_line_basics', 'Number Line Basics', 'Locate and interpret whole numbers on a number line.', 'arithmetic', 1, 65, 11),
  ('arith_place_value_tens', 'Place Value to Tens', 'Represent numbers using ones and tens.', 'arithmetic', 1, 66, 12),
  ('arith_place_value_hundreds', 'Place Value to Hundreds', 'Read, write, and decompose numbers to hundreds.', 'arithmetic', 1, 66, 12),
  ('arith_place_value_thousands', 'Place Value to Thousands', 'Read, write, and decompose numbers to thousands.', 'arithmetic', 2, 67, 13),
  ('arith_compare_whole_numbers', 'Compare Whole Numbers', 'Compare whole numbers using <, >, and =.', 'arithmetic', 1, 66, 12),
  ('arith_order_whole_numbers', 'Order Whole Numbers', 'Order lists of whole numbers ascending and descending.', 'arithmetic', 2, 67, 13),
  ('arith_round_whole_numbers', 'Round Whole Numbers', 'Round whole numbers to tens, hundreds, and thousands.', 'arithmetic', 2, 68, 14),
  ('arith_even_odd_patterns', 'Even and Odd Patterns', 'Identify even/odd numbers and simple parity patterns.', 'arithmetic', 2, 67, 13),
  ('arith_factors_multiples_intro', 'Factors and Multiples Intro', 'Find factors and multiples of whole numbers.', 'arithmetic', 2, 68, 14),
  ('arith_divisibility_rules', 'Divisibility Rules', 'Use divisibility rules for 2, 3, 5, 9, and 10.', 'arithmetic', 3, 70, 16),
  ('arith_addition_within_20', 'Addition Within 20', 'Add whole numbers within 20 accurately.', 'arithmetic', 1, 65, 12),
  ('arith_addition_multi_digit', 'Multi-digit Addition', 'Add multi-digit whole numbers with regrouping.', 'arithmetic', 2, 67, 14),
  ('arith_subtraction_within_20', 'Subtraction Within 20', 'Subtract whole numbers within 20 accurately.', 'arithmetic', 1, 65, 12),
  ('arith_subtraction_multi_digit', 'Multi-digit Subtraction', 'Subtract multi-digit whole numbers with regrouping.', 'arithmetic', 2, 67, 14),
  ('arith_multiplication_as_repeated_addition', 'Multiplication as Repeated Addition', 'Interpret multiplication as equal groups and repeated addition.', 'arithmetic', 2, 68, 15),
  ('arith_multiplication_facts', 'Multiplication Facts', 'Recall multiplication facts fluently.', 'arithmetic', 2, 69, 15),
  ('arith_multi_digit_multiplication', 'Multi-digit Multiplication', 'Multiply multi-digit numbers using standard algorithms.', 'arithmetic', 3, 71, 18),
  ('arith_division_as_sharing', 'Division as Sharing', 'Interpret division as sharing and grouping.', 'arithmetic', 2, 69, 15),
  ('arith_division_facts', 'Division Facts', 'Recall division facts fluently.', 'arithmetic', 3, 70, 16),
  ('arith_long_division', 'Long Division', 'Divide multi-digit numbers using long division.', 'arithmetic', 3, 72, 18),
  ('arith_inverse_operations', 'Inverse Operations', 'Use inverse relationships between operations to solve checks.', 'arithmetic', 3, 70, 16),
  ('arith_order_of_operations_basic', 'Order of Operations Basic', 'Evaluate expressions using operation priority without exponents.', 'arithmetic', 3, 72, 18),
  ('arith_order_of_operations_grouping', 'Order of Operations with Grouping', 'Evaluate grouped expressions with parentheses and brackets.', 'arithmetic', 4, 74, 20),
  ('arith_integer_number_line', 'Integer Number Line', 'Represent positive and negative integers on the number line.', 'arithmetic', 3, 70, 16),
  ('arith_compare_order_integers', 'Compare and Order Integers', 'Compare and order integers including negatives.', 'arithmetic', 3, 71, 17),
  ('arith_absolute_value', 'Absolute Value', 'Interpret and compute absolute value as distance from zero.', 'arithmetic', 3, 71, 17),
  ('arith_add_integers', 'Add Integers', 'Add positive and negative integers correctly.', 'arithmetic', 4, 74, 20),
  ('arith_subtract_integers', 'Subtract Integers', 'Subtract integers using sign rules and number line logic.', 'arithmetic', 4, 75, 20),
  ('arith_multiply_integers', 'Multiply Integers', 'Multiply integers using sign rules.', 'arithmetic', 4, 75, 21),
  ('arith_divide_integers', 'Divide Integers', 'Divide integers using sign rules.', 'arithmetic', 4, 76, 21),
  ('arith_integer_multi_step_expressions', 'Integer Multi-step Expressions', 'Solve multi-step arithmetic expressions with integers.', 'arithmetic', 5, 78, 24),
  ('arith_fraction_part_of_whole', 'Fractions as Part of a Whole', 'Interpret fractions as parts of equal wholes.', 'arithmetic', 2, 68, 15),
  ('arith_equivalent_fractions', 'Equivalent Fractions', 'Generate and recognize equivalent fractions.', 'arithmetic', 3, 71, 17),
  ('arith_simplify_fractions', 'Simplifying Fractions', 'Reduce fractions to simplest form using GCD ideas.', 'arithmetic', 3, 72, 18),
  ('arith_compare_order_fractions', 'Compare and Order Fractions', 'Compare and order fractions using common strategies.', 'arithmetic', 3, 72, 18),
  ('arith_add_subtract_fractions_like_den', 'Add/Subtract Fractions (Like Denominators)', 'Add and subtract fractions with equal denominators.', 'arithmetic', 3, 72, 18),
  ('arith_add_subtract_fractions_unlike_den', 'Add/Subtract Fractions (Unlike Denominators)', 'Add and subtract fractions with different denominators.', 'arithmetic', 4, 75, 21),
  ('arith_multiply_fractions', 'Multiply Fractions', 'Multiply fractions and simplify results.', 'arithmetic', 4, 75, 21),
  ('arith_divide_fractions', 'Divide Fractions', 'Divide fractions using reciprocal relationships.', 'arithmetic', 5, 78, 24),
  ('arith_mixed_numbers_operations', 'Mixed Number Operations', 'Operate with mixed numbers across all four operations.', 'arithmetic', 5, 78, 24),
  ('arith_decimal_place_value', 'Decimal Place Value', 'Read, write, and decompose decimal numbers.', 'arithmetic', 3, 71, 17),
  ('arith_compare_order_decimals', 'Compare and Order Decimals', 'Compare and order decimal values.', 'arithmetic', 3, 72, 18),
  ('arith_decimal_add_subtract', 'Decimal Addition and Subtraction', 'Add and subtract decimals with place-value alignment.', 'arithmetic', 4, 74, 20),
  ('arith_decimal_multiply', 'Decimal Multiplication', 'Multiply decimals and place decimal points correctly.', 'arithmetic', 4, 75, 21),
  ('arith_decimal_divide', 'Decimal Division', 'Divide decimals using scaling and long division.', 'arithmetic', 5, 78, 24),
  ('arith_fraction_decimal_conversion', 'Fraction-Decimal Conversion', 'Convert values between fraction and decimal forms.', 'arithmetic', 4, 75, 21),
  ('arith_ratio_basics', 'Ratio Basics', 'Represent and simplify ratios in multiple forms.', 'arithmetic', 3, 72, 18),
  ('arith_unit_rates', 'Unit Rates', 'Compute and interpret unit rates in contexts.', 'arithmetic', 4, 74, 20),
  ('arith_proportions', 'Proportions', 'Set up and solve proportional relationships.', 'arithmetic', 4, 75, 21),
  ('arith_percent_basics', 'Percent Basics', 'Interpret percentages as per-hundred quantities.', 'arithmetic', 4, 75, 21),
  ('arith_percent_of_quantity', 'Percent of a Quantity', 'Compute percentages of numbers using equivalent forms.', 'arithmetic', 4, 76, 22),
  ('arith_percent_increase_decrease', 'Percent Increase and Decrease', 'Solve increase/decrease and discount/tax problems.', 'arithmetic', 5, 79, 25),
  ('arith_percent_word_problems', 'Percent Word Problems', 'Apply percentages and proportions in multistep contexts.', 'arithmetic', 5, 80, 26),
  ('arith_exponents_basics', 'Exponents Basics', 'Interpret repeated multiplication with exponents.', 'arithmetic', 4, 75, 21),
  ('arith_powers_of_ten', 'Powers of Ten', 'Use powers of ten in place value and scaling.', 'arithmetic', 4, 76, 22),
  ('arith_square_roots_perfect_squares', 'Square Roots of Perfect Squares', 'Compute square roots of perfect squares and inverse links.', 'arithmetic', 5, 79, 25),
  ('arith_order_of_operations_with_exponents', 'Order of Operations with Exponents', 'Evaluate arithmetic expressions including powers and roots.', 'arithmetic', 5, 80, 26),
  ('arith_pre_algebra_numeric_expressions', 'Pre-Algebra Numeric Expressions', 'Solve rich numeric expressions that bridge arithmetic to algebra.', 'arithmetic', 6, 82, 30)
ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  domain = EXCLUDED.domain,
  difficulty_level = EXCLUDED.difficulty_level,
  mastery_threshold = EXCLUDED.mastery_threshold,
  xp_reward = EXCLUDED.xp_reward,
  updated_at = NOW();
