-- Seed: Algebra skills (domain = algebra)
-- Compatible with scripts/db/skill_graph_schema.sql

INSERT INTO skills (
  id,
  name,
  description,
  domain,
  difficulty_level,
  mastery_threshold,
  xp_reward
) VALUES
  ('alg_variables_constants_terms', 'Variables, Constants, and Terms', 'Identify variables, constants, coefficients, and terms in algebraic expressions.', 'algebra', 2, 70, 18),
  ('alg_translate_verbal_expressions', 'Translate Verbal Phrases to Expressions', 'Convert verbal statements into algebraic expressions.', 'algebra', 2, 70, 18),
  ('alg_evaluate_expressions_substitution', 'Evaluate Expressions by Substitution', 'Evaluate algebraic expressions by replacing variables with values.', 'algebra', 2, 70, 18),
  ('alg_order_of_operations_algebraic', 'Order of Operations in Algebraic Contexts', 'Apply operation priority when evaluating expressions with variables.', 'algebra', 3, 72, 22),
  ('alg_like_terms_identification', 'Identify Like Terms', 'Recognize terms that can be combined in algebraic expressions.', 'algebra', 2, 70, 18),
  ('alg_simplify_like_terms', 'Simplify by Combining Like Terms', 'Simplify expressions by combining compatible terms.', 'algebra', 3, 72, 22),
  ('alg_distributive_property', 'Distributive Property', 'Apply the distributive property to expand expressions.', 'algebra', 3, 72, 22),
  ('alg_combining_distributive_like_terms', 'Expand and Simplify Expressions', 'Use distribution and combining like terms in multi-step simplification.', 'algebra', 3, 72, 22),
  ('alg_rational_coefficients_expressions', 'Expressions with Rational Coefficients', 'Simplify expressions containing fractional and decimal coefficients.', 'algebra', 3, 72, 22),
  ('alg_absolute_value_expressions', 'Absolute Value in Expressions', 'Evaluate and simplify expressions involving absolute value.', 'algebra', 3, 72, 22),
  ('alg_exponent_rules_basic_algebra', 'Basic Exponent Rules in Algebra', 'Apply product, quotient, and power rules in algebraic expressions.', 'algebra', 3, 72, 22),
  ('alg_scientific_notation_algebraic', 'Scientific Notation in Algebra', 'Operate with scientific notation in algebraic settings.', 'algebra', 3, 72, 22),
  ('alg_formulas_rearrangement_intro', 'Formula Rearrangement Intro', 'Rearrange formulas to isolate a chosen variable.', 'algebra', 3, 72, 22),
  ('alg_one_step_equations_add_sub', 'One-step Equations (Add/Subtract)', 'Solve one-step linear equations using addition and subtraction.', 'algebra', 3, 72, 22),
  ('alg_one_step_equations_mul_div', 'One-step Equations (Multiply/Divide)', 'Solve one-step linear equations using multiplication and division.', 'algebra', 3, 72, 22),
  ('alg_two_step_linear_equations', 'Two-step Linear Equations', 'Solve two-step linear equations with inverse operations.', 'algebra', 4, 75, 27),
  ('alg_multi_step_linear_equations', 'Multi-step Linear Equations', 'Solve multi-step linear equations with simplification and balancing.', 'algebra', 4, 75, 27),
  ('alg_linear_equations_parentheses', 'Linear Equations with Parentheses', 'Solve equations requiring distribution before isolating variables.', 'algebra', 4, 75, 27),
  ('alg_linear_equations_fractions', 'Linear Equations with Fractions', 'Solve linear equations containing fractional coefficients and terms.', 'algebra', 4, 75, 27),
  ('alg_literal_equations', 'Literal Equations', 'Solve equations for a specified variable in symbolic form.', 'algebra', 4, 75, 27),
  ('alg_linear_equations_word_problems', 'Linear Equation Word Problems', 'Model contexts with linear equations and solve.', 'algebra', 4, 75, 27),
  ('alg_linear_equations_parameters', 'Linear Equations with Parameters', 'Analyze linear equations containing parameters.', 'algebra', 4, 75, 27),
  ('alg_linear_equation_identities_contradictions', 'Identities and Contradictions', 'Classify equations as one solution, no solution, or infinitely many.', 'algebra', 4, 75, 27),
  ('alg_absolute_value_linear_equations', 'Absolute Value Linear Equations', 'Solve linear equations with absolute value by case analysis.', 'algebra', 4, 75, 27),
  ('alg_solution_sets_interval_intro', 'Solution Sets and Interval Intro', 'Express solution sets using set and interval notation basics.', 'algebra', 4, 75, 27),
  ('alg_inequality_basics', 'Inequality Basics', 'Interpret and manipulate inequality symbols in algebraic statements.', 'algebra', 4, 75, 27),
  ('alg_one_step_inequalities', 'One-step Inequalities', 'Solve one-step inequalities and represent solutions.', 'algebra', 4, 75, 27),
  ('alg_two_step_inequalities', 'Two-step Inequalities', 'Solve two-step inequalities including sign changes.', 'algebra', 4, 75, 27),
  ('alg_multi_step_inequalities', 'Multi-step Inequalities', 'Solve multi-step inequalities with simplification and transformations.', 'algebra', 4, 75, 27),
  ('alg_compound_inequalities_and', 'Compound Inequalities (AND)', 'Solve compound inequalities connected by AND.', 'algebra', 4, 75, 27),
  ('alg_compound_inequalities_or', 'Compound Inequalities (OR)', 'Solve compound inequalities connected by OR.', 'algebra', 4, 75, 27),
  ('alg_interval_notation_inequalities', 'Interval Notation for Inequalities', 'Express compound inequality solutions in interval notation.', 'algebra', 5, 78, 33),
  ('alg_absolute_value_inequalities', 'Absolute Value Inequalities', 'Solve and graph absolute value inequalities by cases.', 'algebra', 5, 78, 33),
  ('alg_linear_inequalities_word_problems', 'Linear Inequality Word Problems', 'Model constraints with inequalities and interpret feasible sets.', 'algebra', 5, 78, 33),
  ('alg_graph_inequalities_number_line', 'Graph Inequalities on Number Line', 'Represent inequality solution sets graphically on a number line.', 'algebra', 5, 78, 33),
  ('alg_systems_linear_inequalities_two_var', 'Systems of Linear Inequalities (2 Variables)', 'Find feasible regions satisfying two-variable linear inequalities.', 'algebra', 5, 78, 33),
  ('alg_coordinate_plane_foundations', 'Coordinate Plane Foundations', 'Plot points, identify quadrants, and read coordinates.', 'algebra', 4, 75, 27),
  ('alg_graph_linear_equations', 'Graph Linear Equations', 'Graph linear equations in two variables.', 'algebra', 4, 75, 27),
  ('alg_slope_from_points', 'Slope from Two Points', 'Compute slope using coordinate pairs and rate interpretation.', 'algebra', 4, 75, 27),
  ('alg_slope_intercept_form', 'Slope-Intercept Form', 'Interpret and use y = mx + b for graphing and analysis.', 'algebra', 4, 75, 27),
  ('alg_point_slope_form', 'Point-Slope Form', 'Build and transform linear equations using point-slope form.', 'algebra', 4, 75, 27),
  ('alg_standard_form_linear', 'Standard Form of Linear Equations', 'Convert and interpret linear equations in standard form.', 'algebra', 4, 75, 27),
  ('alg_systems_two_var_graphing', 'Systems of Two Variables by Graphing', 'Solve systems of linear equations graphically.', 'algebra', 5, 78, 33),
  ('alg_systems_two_var_substitution', 'Systems by Substitution', 'Solve systems of two equations using substitution.', 'algebra', 5, 78, 33),
  ('alg_systems_two_var_elimination', 'Systems by Elimination', 'Solve systems of two equations using elimination.', 'algebra', 5, 78, 33),
  ('alg_systems_two_var_word_problems', 'Systems Word Problems', 'Model real situations with linear systems and solve.', 'algebra', 5, 78, 33),
  ('alg_systems_three_var_intro', 'Systems of Three Variables Intro', 'Set up and solve basic three-variable linear systems.', 'algebra', 6, 81, 39),
  ('alg_systems_three_var_elimination', 'Three-variable Elimination', 'Solve 3x3 systems systematically by elimination.', 'algebra', 6, 81, 39),
  ('alg_systems_solution_classification', 'System Solution Classification', 'Classify systems as consistent/inconsistent and dependent/independent.', 'algebra', 6, 81, 39),
  ('alg_linear_programming_intro', 'Linear Programming Intro', 'Optimize a linear objective under linear constraints.', 'algebra', 6, 81, 39),
  ('alg_polynomial_terms_degree', 'Polynomial Terms and Degree', 'Classify polynomials by terms, degree, and leading coefficient.', 'algebra', 5, 78, 33),
  ('alg_add_subtract_polynomials', 'Add and Subtract Polynomials', 'Perform addition and subtraction with polynomial expressions.', 'algebra', 5, 78, 33),
  ('alg_multiply_monomial_polynomial', 'Multiply Monomial and Polynomial', 'Multiply monomials across polynomial terms using distribution.', 'algebra', 5, 78, 33),
  ('alg_multiply_binomials', 'Multiply Binomials', 'Multiply binomials accurately using structured expansion.', 'algebra', 5, 78, 33),
  ('alg_multiply_polynomials_general', 'General Polynomial Multiplication', 'Multiply higher-degree polynomials systematically.', 'algebra', 5, 78, 33),
  ('alg_special_products_square_binomial', 'Special Products: Square of a Binomial', 'Use identities for squares of binomials.', 'algebra', 5, 78, 33),
  ('alg_special_products_conjugates', 'Special Products: Conjugates', 'Use conjugate identities to simplify products quickly.', 'algebra', 5, 78, 33),
  ('alg_polynomial_long_division', 'Polynomial Long Division', 'Divide polynomials using long division.', 'algebra', 6, 81, 39),
  ('alg_synthetic_division', 'Synthetic Division', 'Perform polynomial division efficiently with synthetic division.', 'algebra', 6, 81, 39),
  ('alg_remainder_factor_theorem', 'Remainder and Factor Theorem', 'Use theorem-based tests to analyze polynomial factors and roots.', 'algebra', 6, 81, 39),
  ('alg_polynomial_evaluation', 'Polynomial Evaluation', 'Evaluate polynomial functions at given inputs.', 'algebra', 5, 78, 33),
  ('alg_polynomial_graph_features_intro', 'Polynomial Graph Features Intro', 'Relate polynomial form to zeros, intercepts, and shape features.', 'algebra', 6, 81, 39),
  ('alg_polynomial_end_behavior', 'Polynomial End Behavior', 'Analyze end behavior using degree and leading coefficient.', 'algebra', 6, 81, 39),
  ('alg_polynomial_roots_multiplicity_intro', 'Roots and Multiplicity Intro', 'Interpret roots and multiplicities in polynomial behavior.', 'algebra', 6, 81, 39),
  ('alg_factor_gcf', 'Factor by Greatest Common Factor', 'Factor expressions by extracting the GCF.', 'algebra', 5, 78, 33),
  ('alg_factor_trinomials_monic', 'Factor Monic Trinomials', 'Factor trinomials with leading coefficient 1.', 'algebra', 6, 81, 39),
  ('alg_factor_trinomials_non_monic', 'Factor Non-Monic Trinomials', 'Factor trinomials with leading coefficients other than 1.', 'algebra', 6, 81, 39),
  ('alg_factor_difference_of_squares', 'Factor Difference of Squares', 'Recognize and factor expressions of the form a^2 - b^2.', 'algebra', 6, 81, 39),
  ('alg_factor_perfect_square_trinomials', 'Factor Perfect Square Trinomials', 'Identify and factor perfect square trinomials.', 'algebra', 6, 81, 39),
  ('alg_factor_sum_difference_cubes', 'Factor Sum and Difference of Cubes', 'Apply cube identities to factor cubic expressions.', 'algebra', 6, 81, 39),
  ('alg_factor_by_grouping', 'Factor by Grouping', 'Factor multi-term polynomials using grouping patterns.', 'algebra', 6, 81, 39),
  ('alg_factoring_strategy_selection', 'Factoring Strategy Selection', 'Select efficient factoring methods for mixed expression types.', 'algebra', 7, 84, 45),
  ('alg_solve_polynomial_equations_factoring', 'Solve Polynomial Equations by Factoring', 'Solve polynomial equations using zero-product reasoning.', 'algebra', 7, 84, 45),
  ('alg_rational_expressions_simplify', 'Simplify Rational Expressions', 'Simplify rational expressions through factoring and cancellation.', 'algebra', 6, 81, 39),
  ('alg_rational_expressions_multiply_divide', 'Multiply and Divide Rational Expressions', 'Perform multiplication and division of rational expressions.', 'algebra', 6, 81, 39),
  ('alg_rational_expressions_add_subtract', 'Add and Subtract Rational Expressions', 'Add and subtract rational expressions using common denominators.', 'algebra', 6, 81, 39),
  ('alg_rational_equations_linear', 'Linear Rational Equations', 'Solve linear equations containing rational expressions with restrictions.', 'algebra', 7, 84, 45),
  ('alg_quadratic_forms_and_structure', 'Quadratic Forms and Structure', 'Recognize standard, factored, and vertex forms of quadratics.', 'algebra', 6, 81, 39),
  ('alg_solve_quadratics_factoring', 'Solve Quadratics by Factoring', 'Solve quadratic equations using factorization methods.', 'algebra', 7, 84, 45),
  ('alg_solve_quadratics_square_root', 'Solve Quadratics by Square Root Method', 'Solve quadratics reducible to squared binomial forms.', 'algebra', 7, 84, 45),
  ('alg_complete_the_square', 'Complete the Square', 'Transform quadratics by completing the square.', 'algebra', 7, 84, 45),
  ('alg_quadratic_formula', 'Quadratic Formula', 'Solve quadratic equations with the quadratic formula.', 'algebra', 7, 84, 45),
  ('alg_quadratic_discriminant', 'Quadratic Discriminant Analysis', 'Use the discriminant to predict root types and counts.', 'algebra', 7, 84, 45),
  ('alg_convert_to_vertex_form', 'Convert to Vertex Form', 'Rewrite quadratic expressions into vertex form.', 'algebra', 7, 84, 45),
  ('alg_graph_quadratic_functions', 'Graph Quadratic Functions', 'Graph quadratic functions and identify key graph features.', 'algebra', 7, 84, 45),
  ('alg_quadratic_vertex_axis', 'Vertex and Axis of Symmetry', 'Determine vertex and axis of symmetry from equation forms.', 'algebra', 7, 84, 45),
  ('alg_quadratic_intercepts', 'Quadratic Intercepts', 'Find and interpret x- and y-intercepts of quadratic functions.', 'algebra', 7, 84, 45),
  ('alg_quadratic_modeling_word_problems', 'Quadratic Modeling Word Problems', 'Model and solve contextual problems with quadratic functions.', 'algebra', 7, 84, 45),
  ('alg_quadratic_inequalities', 'Quadratic Inequalities', 'Solve quadratic inequalities with interval reasoning.', 'algebra', 8, 86, 52),
  ('alg_complex_numbers_intro', 'Complex Numbers Intro', 'Introduce imaginary unit and basic complex number operations.', 'algebra', 7, 84, 45),
  ('alg_quadratics_complex_solutions', 'Quadratics with Complex Solutions', 'Solve quadratics whose roots are complex.', 'algebra', 8, 86, 52),
  ('alg_function_concept_domain_range', 'Function Concept, Domain, and Range', 'Define functions and determine domain/range in basic representations.', 'algebra', 5, 78, 33),
  ('alg_function_notation_evaluation', 'Function Notation and Evaluation', 'Use function notation and evaluate functions at given inputs.', 'algebra', 5, 78, 33),
  ('alg_functions_tables_graphs_mapping', 'Functions: Tables, Graphs, and Mapping', 'Relate tabular, graphical, and mapping representations of functions.', 'algebra', 5, 78, 33),
  ('alg_rate_of_change_average', 'Average Rate of Change', 'Compute and interpret average rate of change between points.', 'algebra', 5, 78, 33),
  ('alg_linear_function_modeling', 'Linear Function Modeling', 'Build linear models for contextual relationships.', 'algebra', 6, 81, 39),
  ('alg_piecewise_functions_intro', 'Piecewise Functions Intro', 'Interpret and evaluate piecewise-defined functions.', 'algebra', 6, 81, 39),
  ('alg_inverse_functions_intro', 'Inverse Functions Intro', 'Identify and compute inverses of basic functions.', 'algebra', 6, 81, 39),
  ('alg_function_composition_intro', 'Function Composition Intro', 'Compose functions and evaluate composite expressions.', 'algebra', 6, 81, 39),
  ('alg_function_transformations', 'Function Transformations', 'Apply shifts, stretches, reflections, and compressions to graphs.', 'algebra', 6, 81, 39),
  ('alg_parent_function_families', 'Parent Function Families', 'Compare key families of functions by shape and behavior.', 'algebra', 6, 81, 39),
  ('alg_exponential_functions_intro', 'Exponential Functions Intro', 'Understand exponential form and core graph behavior.', 'algebra', 6, 81, 39),
  ('alg_exponential_growth_decay', 'Exponential Growth and Decay', 'Model growth and decay processes with exponentials.', 'algebra', 6, 81, 39),
  ('alg_logarithm_concept_intro', 'Logarithm Concept Intro', 'Interpret logarithms as inverse operations of exponentials.', 'algebra', 7, 84, 45),
  ('alg_logarithm_properties', 'Logarithm Properties', 'Apply product, quotient, and power properties of logarithms.', 'algebra', 7, 84, 45),
  ('alg_solve_exponential_equations_logs', 'Solve Exponential Equations with Logs', 'Solve exponential equations using logarithmic transformations.', 'algebra', 8, 86, 52),
  ('alg_solve_logarithmic_equations', 'Solve Logarithmic Equations', 'Solve logarithmic equations and verify valid domains.', 'algebra', 8, 86, 52),
  ('alg_sequence_patterns_intro', 'Sequence Pattern Intro', 'Recognize and extend arithmetic and geometric patterns.', 'algebra', 5, 78, 33),
  ('alg_arithmetic_sequence_nth_term', 'Arithmetic Sequence nth Term', 'Derive and use explicit formulas for arithmetic sequences.', 'algebra', 6, 81, 39),
  ('alg_arithmetic_series_sum', 'Arithmetic Series Sum', 'Compute finite sums of arithmetic sequences.', 'algebra', 6, 81, 39),
  ('alg_geometric_sequence_nth_term', 'Geometric Sequence nth Term', 'Derive and use explicit formulas for geometric sequences.', 'algebra', 6, 81, 39),
  ('alg_geometric_series_sum', 'Geometric Series Sum', 'Compute finite sums of geometric sequences.', 'algebra', 6, 81, 39),
  ('alg_recursive_sequences_intro', 'Recursive Sequences Intro', 'Define and analyze recursive sequences.', 'algebra', 6, 81, 39),
  ('alg_sigma_notation_series', 'Sigma Notation and Series', 'Represent and evaluate series using sigma notation.', 'algebra', 7, 84, 45),
  ('alg_series_convergence_intuition', 'Series Convergence Intuition', 'Develop intuition about boundedness and convergence patterns.', 'algebra', 7, 84, 45),
  ('alg_binomial_theorem_intro', 'Binomial Theorem Intro', 'Use binomial coefficients to expand binomial powers.', 'algebra', 7, 84, 45),
  ('alg_matrices_intro_systems', 'Matrices Intro for Systems', 'Represent systems of equations using matrices.', 'algebra', 6, 81, 39),
  ('alg_matrix_operations_basic', 'Basic Matrix Operations', 'Add, subtract, and multiply matrices in compatible dimensions.', 'algebra', 6, 81, 39),
  ('alg_matrix_determinant_2x2', 'Determinant of 2x2 Matrices', 'Compute determinants and interpret invertibility in 2x2 case.', 'algebra', 7, 84, 45),
  ('alg_inverse_matrix_method_systems', 'Inverse Matrix Method for Systems', 'Solve linear systems using matrix inverses.', 'algebra', 7, 84, 45)
ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  domain = EXCLUDED.domain,
  difficulty_level = EXCLUDED.difficulty_level,
  mastery_threshold = EXCLUDED.mastery_threshold,
  xp_reward = EXCLUDED.xp_reward,
  updated_at = NOW();
